"""W23: self-consistency single-cost baseline from the RECORDED LM programs.

The strongest 'one cost from text' recipe short of ours: sample several
LM-generated ``violated(s)`` programs for the same rule (already recorded in
results/paper_extra/llm_codegen/*.json -- no new LM calls), majority-vote them into
ONE cost, and train against that single cost.  Under CORSET's thesis this
must still under-protect: a vote over samples reduces generation variance but
still commits to one reading of the sentence.

Run:  SAORL_CONFORMAL=1 PYTHONPATH=. python3 -m saorl.baseline_llm_selfconsistency
Writes results/conformal/selfconsistency.json + paper/generated/gen_selfcons.tex
"""
from __future__ import annotations

import glob
import json
import os
from pathlib import Path
from typing import Callable, List

import numpy as np

from .baseline_llm_codegen import (
    EPS,
    MAINT,
    RULE_SET,
    RULE_SETS,
    CodeRow,
    as_candidate,
    evaluate_code,
    safe_compile,
    _summ,
)

N_SEEDS = 15


def load_recorded_programs() -> List[Callable[[dict], bool]]:
    files = sorted(glob.glob(str(Path(__file__).parent.parent.parent /
                                 "results/paper_extra" / "llm_codegen" / "*.json")))
    d = json.load(open(files[-1]))
    fns = []
    for s in d["samples"]:
        code = s.get("code") or s.get("raw", "")
        if "```" in code:  # strip markdown fences from raw replies
            inner = code.split("```")
            code = next((b for b in inner if "def violated" in b), code)
            code = code.removeprefix("python\n").removeprefix("python\r\n")
        try:
            fns.append(safe_compile(code))
        except Exception:
            continue
    return fns


def main() -> None:
    assert os.environ.get("SAORL_CONFORMAL") == "1", "run under the conformal sets"
    fns = load_recorded_programs()
    k = len(fns)
    need = k // 2 + 1
    print(f"self-consistency vote over {k} recorded valid programs "
          f"(majority = >= {need})")

    def vote(s: dict) -> bool:
        return sum(1 for f in fns if f(s)) >= need

    rows = evaluate_code(vote, sample=-1, seeds=range(N_SEEDS))
    _summ(rows, "self-consistency majority vote")

    out = {
        "n_programs": k,
        "majority": need,
        "rows": [r.__dict__ for r in rows],
    }
    od = Path(__file__).parent.parent.parent / "results/conformal"
    json.dump(out, open(od / "selfconsistency.json", "w"), indent=1)

    # fragment: one row per policy
    lines = ["% AUTO-GENERATED by saorl/baseline_llm_selfconsistency.py\n"]
    for name, label in (("llm-code", "Self-consistency vote (single cost)"),
                        ("SA-ORL", "\\corset{} (conformal set)")):
        rs = [r for r in rows if r.policy == name]
        ret = np.array([r.ret for r in rs])
        wc = np.array([r.worst for r in rs])
        ch = np.array([r.chance for r in rs])
        lines.append(f"{label} & ${ret.mean():.1f}\\pm{ret.std():.1f}$ & "
                     f"${wc.mean():.3f}\\pm{wc.std():.3f}$ & ${ch.mean():.3f}$ \\\\\n")
    gen = Path(__file__).parent.parent.parent / "paper" / "generated" / "gen_selfcons.tex"
    open(gen, "w").write("".join(lines))
    print("wrote", gen)


if __name__ == "__main__":
    main()
