"""Why end-to-end coverage is 3.6%, and what would move it.

Two questions, both answered from frozen archives (no new test outcome is
produced here; this is post-hoc stratification of the already-executed
v11 pass plus a deterministic re-parse of the hidden targets):

1. ANATOMY of delta_expr. Which eligibility failure, which construct,
   which repository. The headline: the declared six-tuple grammar
   compares a metric to a GRID CONSTANT, and the corpus's dominant
   construct compares it to another SERIES.

2. GRAMMAR REACH CURVE. Expressibility is a property of the declared
   grammar, not of ARROW: the decision theory needs only a finite set of
   evaluable readings. So we measure reach under three grammars, each a
   strict superset of the last:

     G0   the frozen six-tuple (threshold in the decade grid)
     G1   G0 with the threshold axis generalized to an evaluable
          REFERENCE EXPRESSION (metric > on(...) group_left ref)
     G2   G1 closed under conjunction ((A > k) and on(...) (B > k'))

   G1 and G2 are reach measurements only: they say how much of the corpus
   a generator COULD address, and bound nothing about licensing or
   retention, which would need their own registered pass. Reported as a
   ceiling, labelled as such.

Run: PYTHONPATH=. python3 corset_e2e/analysis/coverage_anatomy.py
Writes results/e2e/coverage_anatomy.json
"""
from __future__ import annotations

import json
import os
import re
import sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
sys.path.insert(0, os.path.join(str(ROOT), "src"))

from corset_e2e.dsl.schema import (  # noqa: E402
    COMPARATORS, FOR_S, IN_DSL, classify_target)

OUT = os.path.join(ROOT, "results/e2e")
CMP = (">=", "<=", "==", "!=", ">", "<")
_VM = re.compile(r"\bon\s*\(|\bignoring\s*\(|group_left|group_right")
_METRIC = re.compile(r"[a-z_][a-z0-9_]*(?::[a-z0-9_]+)*")


def vis(rid):
    with open(os.path.join(OUT, "visible_store", f"{rid}.json")) as fh:
        return json.load(fh)


def hid(rid):
    with open(os.path.join(OUT, "hidden_store", f"{rid}.target.json")) as fh:
        return json.load(fh)


def toplevel_split(s: str):
    """Split on a top-level comparator, respecting () {} [] nesting."""
    depth = 0
    for i, ch in enumerate(s):
        if ch in "({[":
            depth += 1
        elif ch in ")}]":
            depth -= 1
        elif depth == 0:
            for c in CMP:
                if s.startswith(c, i):
                    return s[:i].strip(), c, s[i + len(c):].strip()
    return None


def reach_g1(h: dict) -> bool:
    """G1: metric CMP <reference series>, all non-threshold axes in grid."""
    x = (h.get("raw_expr") or "").strip()
    sp = toplevel_split(x)
    if sp is None:
        return False
    lhs, c, rhs = sp
    if c not in COMPARATORS:
        return False
    if float(h.get("for_s", 0.0)) not in set(FOR_S):
        return False
    # right-hand side must name a series through a vector match, not a constant
    head = rhs.split("{")[0][:48]
    if not (_VM.search(head) and _METRIC.search(rhs)):
        return False
    return bool(_METRIC.match(lhs.strip().lstrip("(").strip()))


def reach_g2(h: dict) -> bool:
    """G2: G1 closed under a top-level set-op conjunction of comparisons."""
    x = (h.get("raw_expr") or "").strip()
    if not _VM.search(x):
        return False
    if float(h.get("for_s", 0.0)) not in set(FOR_S):
        return False
    parts = re.split(r"\band\b|\bunless\b", x)
    if len(parts) < 2:
        return False
    # at least one conjunct is a comparison against a constant or a series
    return sum(1 for p in parts if toplevel_split(p) is not None) >= 1


def main() -> None:
    led = json.load(open(os.path.join(OUT, "cluster_ledger.json")))
    test = [e for e in led if e["split"] == "test"]
    rows = {r["rid"]: r for r in json.load(
        open(os.path.join(OUT, "e2e_test_rows_v11_complete.json")))}

    reasons = Counter()
    per_repo = defaultdict(lambda: dict(n=0, expr=0, ret=0))
    shapes = Counter()
    g0 = g1 = g2 = 0
    by_text = defaultdict(list)
    n_auto = 0
    for e in test:
        rid = e["rule_id"]
        h = hid(rid)
        cls = classify_target(h)
        reasons[cls] += 1
        pr = per_repo[e["repo"]]
        pr["n"] += 1
        r = rows.get(rid)
        ok_expr = cls == IN_DSL
        pr["expr"] += ok_expr
        ret = bool(r and r["label"] == IN_DSL and r.get("retained_gold"))
        pr["ret"] += ret
        v = vis(rid)
        by_text[(v.get("alert_name", "").strip(),
                 " ".join((v.get("text") or "").split()))].append(e)
        n_auto += "autogenerated" in e["cluster_id"]
        # grammar reach
        if ok_expr:
            g0 += 1
            g1 += 1
            g2 += 1
        else:
            r1, r2 = reach_g1(h), reach_g2(h)
            g1 += r1
            g2 += bool(r1 or r2)
        if cls == "PARSER_FAILURE":
            x = h.get("raw_expr") or ""
            if _VM.search(x):
                sp = toplevel_split(x.strip())
                if sp is None:
                    shapes["vm_conjunction"] += 1
                elif re.search(r"\bon\s*\(|group_", sp[2].split("{")[0][:48]):
                    shapes["vm_reference_threshold"] += 1
                else:
                    shapes["vm_other"] += 1
            else:
                shapes["non_vm"] += 1

    n = len(test)
    # denominators
    dedup = {}
    for key, units in by_text.items():
        e = sorted(units, key=lambda u: u["rule_id"])[0]
        r = rows.get(e["rule_id"])
        dedup[key] = bool(r and r["label"] == IN_DSL and r.get("retained_gold"))
    nonauto = [e for e in test if "autogenerated" not in e["cluster_id"]]
    na_ret = sum(1 for e in nonauto
                 if (rows.get(e["rule_id"]) or {}).get("retained_gold")
                 and rows[e["rule_id"]]["label"] == IN_DSL)
    micro_ret = sum(1 for e in test
                    if (rows.get(e["rule_id"]) or {}).get("retained_gold")
                    and rows[e["rule_id"]]["label"] == IN_DSL)
    repo_rates = {k: v["ret"] / v["n"] for k, v in per_repo.items()}

    # the sentences the paper will state, asserted
    assert reasons["PARSER_FAILURE"] / n > 0.75, "parser is no longer the wall"
    assert shapes["vm_reference_threshold"] + shapes["vm_conjunction"] > \
        0.9 * sum(v for k, v in shapes.items() if k.startswith("vm")), \
        "the two vector-matching shapes no longer dominate"
    assert per_repo["gitlab-runbooks"]["n"] / n > 0.85, \
        "gitlab no longer dominates the corpus mass"
    assert g1 > g0 and g2 >= g1
    assert abs(micro_ret / n - 0.036) < 0.003, "published 3.6% moved"

    payload = dict(
        note=("post-hoc stratification of the frozen v11 test pass plus a "
              "deterministic re-parse of hidden targets; G1/G2 are REACH "
              "CEILINGS (what a generator could address), not measured "
              "end-to-end coverage"),
        n_units=n,
        eligibility={k: dict(n=v, frac=v / n) for k, v in reasons.most_common()},
        parser_failure_shapes={k: dict(n=v, frac_of_corpus=v / n)
                               for k, v in shapes.most_common()},
        grammar_reach=dict(
            G0_frozen=dict(n=g0, frac=g0 / n),
            G1_reference_threshold=dict(n=g1, frac=g1 / n),
            G2_plus_conjunction=dict(n=g2, frac=g2 / n)),
        denominators=dict(
            micro_units=dict(n=n, e2e=micro_ret / n),
            distinct_written_rules=dict(
                n=len(dedup), e2e=sum(dedup.values()) / len(dedup)),
            non_template_units=dict(
                n=len(nonauto), e2e=na_ret / len(nonauto)),
            repo_macro=dict(n=len(repo_rates),
                            e2e=sum(repo_rates.values()) / len(repo_rates))),
        template_mass=dict(n_autogenerated=n_auto, frac=n_auto / n),
        per_repo={k: dict(n=v["n"], expr=v["expr"] / v["n"],
                          e2e=v["ret"] / v["n"])
                  for k, v in sorted(per_repo.items(),
                                     key=lambda kv: -kv[1]["n"])})
    with open(os.path.join(OUT, "coverage_anatomy.json"), "w") as fh:
        json.dump(payload, fh, indent=1)
    print(json.dumps({k: v for k, v in payload.items()
                      if k != "per_repo"}, indent=1))
    print("per_repo:", json.dumps(payload["per_repo"], indent=1))


if __name__ == "__main__":
    main()
