"""Coverage funnel of the frozen v11 test pass, stratified by repository:
raw units -> unique rules -> non-template -> in-grammar (G0) -> faithful
executable target -> governing reading proposed -> governing reading
retained. Two views: the NESTED chain (one representative per distinct
written rule, then the filters in order) and the UNIT-level chain (the
paper's counts). Read-out only; nothing is re-run.

Run: PYTHONPATH=. python3 corset_e2e/analysis/coverage_funnel.py
Writes results/e2e/coverage_funnel.json
"""
from __future__ import annotations

import json
import os
import sys
from collections import Counter, OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
sys.path.insert(0, os.path.join(str(ROOT), "src"))

from corset_e2e.analysis.grammar_taxonomy import features_for  # noqa: E402
from corset_e2e.dsl.schema import IN_DSL, classify_target  # noqa: E402
from corset_e2e.calibration.run_e2e_v4 import hid, vis  # noqa: E402

OUT = os.path.join(ROOT, "results/e2e")
STRUCTURAL = frozenset(("arith_vector", "setop_and", "setop_or", "setop_unless", "nested_comparison", "no_comparison",
                        "threshold_expr_vector", "agg_nested", "agg_param", "subquery", "unary"))
STAGES = ("raw", "unique", "non_template", "in_grammar", "faithful", "proposed", "retained")


def faithful_g0(h) -> bool:
    feats, _how = features_for(h)
    return feats is not None and not set(feats)


def main():
    led = json.load(open(os.path.join(OUT, "cluster_ledger.json")))
    test = [e for e in led if e["split"] == "test"]
    rows = {r["rid"]: r for r in json.load(open(os.path.join(OUT, "e2e_test_rows_v11_complete.json")))}
    units = []
    for e in test:
        rid = e["rule_id"]; h = hid(rid); v = vis(rid); r = rows.get(rid, {})
        ing = classify_target(h) == IN_DSL
        units.append(dict(rid=rid, repo=e["repo"], template=("autogenerated" in e["cluster_id"]),
                          textkey=(v.get("alert_name", "").strip(), " ".join((v.get("text") or "").split())),
                          in_grammar=ing, faithful=(ing and faithful_g0(h)), proposed=(r.get("label") == IN_DSL),
                          retained=bool(r.get("label") == IN_DSL and r.get("retained_gold"))))
    repos = [k for k, _ in Counter(u["repo"] for u in units).most_common()]

    def chain_nested(us):
        """dedup first (one representative per distinct written rule: smallest rid), then filters in order."""
        reps = {}
        for u in sorted(us, key=lambda u: u["rid"]):
            reps.setdefault(u["textkey"], u)
        c = OrderedDict(raw=len(us), unique=len(reps))
        cur = [u for u in reps.values() if not u["template"]]; c["non_template"] = len(cur)
        cur = [u for u in cur if u["in_grammar"]]; c["in_grammar"] = len(cur)
        cur = [u for u in cur if u["faithful"]]; c["faithful"] = len(cur)
        cur = [u for u in cur if u["proposed"]]; c["proposed"] = len(cur)
        cur = [u for u in cur if u["retained"]]; c["retained"] = len(cur)
        return c

    def chain_units(us):
        """unit level (the paper's counts): raw -> in-grammar -> faithful -> proposed -> retained; unique and non-template reported as side counts."""
        c = OrderedDict(raw=len(us), unique=len({u["textkey"] for u in us}), non_template=sum(1 for u in us if not u["template"]))
        cur = [u for u in us if u["in_grammar"]]; c["in_grammar"] = len(cur)
        cur = [u for u in cur if u["faithful"]]; c["faithful"] = len(cur)
        cur = [u for u in cur if u["proposed"]]; c["proposed"] = len(cur)
        cur = [u for u in cur if u["retained"]]; c["retained"] = len(cur)
        return c

    def pct(c, nested):
        out = OrderedDict(); prev = None
        for i, k in enumerate(STAGES):
            n = c[k]; base = c["raw"]
            if nested:
                cond = (n / prev) if (prev not in (None, 0)) else None
            else:
                # unit view: unique/non_template are side counts against raw; the chain is raw -> in_grammar -> ...
                if k in ("unique", "non_template"):
                    cond = n / base if base else None
                else:
                    cond = (n / prev) if (prev not in (None, 0)) else None
            out[k] = dict(n=n, conditional=cond, unconditional=(n / base if base else None))
            if nested or k not in ("unique", "non_template"):
                prev = n
        return out

    res = dict(n_units=len(units), stages=list(STAGES), nested={}, unit_level={})
    for repo in repos + ["ALL"]:
        us = units if repo == "ALL" else [u for u in units if u["repo"] == repo]
        res["nested"][repo] = pct(chain_nested(us), True); res["unit_level"][repo] = pct(chain_units(us), False)
    json.dump(res, open(os.path.join(OUT, "coverage_funnel.json"), "w"), indent=1)

    def table(view, title):
        print(f"\n{title}")
        hdr = "repo".ljust(28) + "".join(f"{s:>22s}" for s in STAGES); print(hdr)
        for repo, st in res[view].items():
            line = repo.ljust(28)
            for s in STAGES:
                x = st[s]; cond = "" if x["conditional"] is None else f"{100*x['conditional']:.0f}%"; unc = f"{100*x['unconditional']:.1f}%"
                line += f"{x['n']:>7d} {cond:>5s} {unc:>7s} "
            print(line)
    table("nested", "NESTED CHAIN (n, conditional % of previous stage, unconditional % of raw); dedup first, then non-template, in-grammar, faithful, proposed, retained")
    table("unit_level", "UNIT LEVEL (n, conditional %, unconditional %); unique and non-template are side counts vs raw; chain raw -> in-grammar -> faithful -> proposed -> retained")
    print("\nwrote results/e2e/coverage_funnel.json")


if __name__ == "__main__":
    main()
