"""W1 / W6 / W7: guarantee accounting on faithful gold, disjoint corpus
funnels, and the operational pipeline funnel.

Every number is recomputed from per-unit archives (no aggregate is copied):
  results/e2e/cluster_ledger.json          test units, repo, cluster
  results/e2e/e2e_test_rows_v11_complete.json   frozen grammar (G0) pass
  results/e2e/e2e_test_rows_g1.json + e2e_report_g1_mondrian.json   widened grammar (G1)
  results/e2e/visible_store, hidden_store  written text / hidden target
  the gold-faithfulness audit's own classifier (features_for, STRUCTURAL)
  results/conformal/benchmark_sg/report.json + parse.py   pinned public rules
  results/e2e/downstream_provenance.json, class_ladder.json, policy_class_budget.json
  results/conformal/lp/expected_cost_certificate.json   controlled-domain ships

Populations (rows of the accounting table): raw units; distinct written
rules; non-template units; grammar-expressible (G0); widened grammar (G1).
Stages (columns): grammar reach, generator proposal 1-delta_gen,
conditional retention 1-delta_sem, generated+retained; each on the recorded
gold and on the faithful expression-tree gold.  Where a stage was not
measured for a population it is written as null and typeset as
"not measured".

Run: SAORL_CONFORMAL=1 PYTHONPATH=. python3 corset_e2e/analysis/guarantee_accounting.py
Writes results/e2e/guarantee_accounting.json
"""
from __future__ import annotations

import json
import os
import sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
sys.path.insert(0, os.path.join(str(ROOT), "src"))

from corset_e2e.analysis.gold_faithfulness_audit import (  # noqa: E402
    G1_ENCODED, STRUCTURAL)
from corset_e2e.analysis.grammar_taxonomy import features_for  # noqa: E402
from corset_e2e.dsl.schema import IN_DSL, classify_target  # noqa: E402
from corset_e2e.dsl.schema_g1 import IN_G1_REF, classify_target_g1  # noqa: E402

R = os.path.join(ROOT, "results/e2e")
OUT = os.path.join(R, "guarantee_accounting.json")


def J(*p):
    return json.load(open(os.path.join(ROOT, *p)))


def hid(rid):
    return json.load(open(os.path.join(R, "hidden_store", f"{rid}.target.json")))


def vis(rid):
    return json.load(open(os.path.join(R, "visible_store", f"{rid}.json")))


def faithful_flag(h, cls_g0, cls_g1):
    """None if the gold is not representable in either grammar class; else bool."""
    if cls_g0 == IN_DSL:
        enc = frozenset()
    elif cls_g1 == IN_G1_REF:
        enc = G1_ENCODED
    else:
        return None
    feats, _how = features_for(h)
    if feats is None:
        return False
    extra = feats - enc
    return not extra          # strict: the audit's 'faithful' bucket; representational extras are its 'other' bucket


def rates(units, key_expr, key_lic, key_ret, faithful):
    """Stage rates for a population; faithful=None -> recorded gold."""
    def sel(u):
        return faithful is None or u["faithful"] is True
    n = len(units)
    expr = [u for u in units if u[key_expr] and (faithful is None or u["faithful"] is True)]
    lic = [u for u in expr if u[key_lic]]
    ret = [u for u in lic if u[key_ret]]
    return dict(n=n, expressible=len(expr), licensed=len(lic), retained=len(ret),
                reach=len(expr) / n if n else None,
                proposal=len(lic) / len(expr) if expr else None,
                retention=len(ret) / len(lic) if lic else None,
                e2e=len(ret) / n if n else None)


def main():
    led = [e for e in J("results/e2e", "cluster_ledger.json") if e["split"] == "test"]
    rows0 = {r["rid"]: r for r in J("results/e2e", "e2e_test_rows_v11_complete.json")}
    rows1 = {r["rid"]: r for r in J("results/e2e", "e2e_test_rows_g1.json")}
    mond = J("results/e2e", "e2e_report_g1_mondrian.json")["per_class"]
    qh = {k: v["qhat"] for k, v in mond.items()}
    units = []
    by_text = defaultdict(list)
    for e in led:
        rid = e["rule_id"]
        h = hid(rid)
        c0 = classify_target(h)
        c1 = classify_target_g1(h)
        r0 = rows0[rid]
        r1 = rows1.get(rid, {})
        u = dict(rid=rid, repo=e["repo"], template=("autogenerated" in e["cluster_id"]),
                 g0_expr=(c0 == IN_DSL), g0_lic=(r0["label"] == IN_DSL), g0_ret=bool(r0.get("retained_gold")),
                 g1_expr=(c0 == IN_DSL or c1 == IN_G1_REF), g1_lic=(r1.get("label") in qh),
                 g1_ret=bool(r1.get("label") in qh and r1.get("gold_score") is not None
                             and r1["gold_score"] >= qh[r1["label"]]),
                 faithful=faithful_flag(h, c0, c1))
        assert not (u["g0_lic"] and not u["g0_expr"]), rid
        assert not (u["g0_ret"] and not u["g0_lic"]), rid
        assert not (u["g1_ret"] and not u["g1_lic"]), rid
        v = vis(rid)
        by_text[(v.get("alert_name", "").strip(), " ".join((v.get("text") or "").split()))].append(u)
        units.append(u)
    # the four published anchors, asserted
    assert sum(u["g0_expr"] for u in units) == 315
    assert sum(u["g0_lic"] for u in units) == 181
    assert sum(u["g0_ret"] for u in units) == 158
    assert sum(u["g1_expr"] for u in units) == 1511
    assert sum(u["g1_lic"] for u in units) == 595 and sum(u["g1_ret"] for u in units) == 563
    assert sum(1 for u in units if u["g0_ret"] and u["faithful"]) == 102
    assert sum(1 for u in units if u["g1_ret"] and u["faithful"]) == 417
    distinct = [sorted(us, key=lambda x: x["rid"])[0] for us in by_text.values()]
    nontmpl = [u for u in units if not u["template"]]
    assert len(distinct) == 1471 and len(nontmpl) == 588
    g0pop = [u for u in units if u["g0_expr"]]
    g1pop = [u for u in units if u["g1_expr"]]
    pops = [("raw_units", units), ("distinct_rules", distinct), ("non_template_units", nontmpl),
            ("grammar_expressible_G0", g0pop), ("widened_grammar_G1", g1pop)]
    table = {}
    for name, pop in pops:
        table[name] = dict(
            recorded_G0=rates(pop, "g0_expr", "g0_lic", "g0_ret", None),
            faithful_G0=rates(pop, "g0_expr", "g0_lic", "g0_ret", True),
            recorded_G1=rates(pop, "g1_expr", "g1_lic", "g1_ret", None),
            faithful_G1=rates(pop, "g1_expr", "g1_lic", "g1_ret", True),
            faithful_share_of_expressible_G0=(sum(1 for u in pop if u["g0_expr"] and u["faithful"]) /
                                              max(1, sum(1 for u in pop if u["g0_expr"]))))
    # availability is measured only on the G0 expressible population (v4u catalogue)
    e2e = J("results/e2e", "e2e_report_v11.json")["modes"]["complete"]["test"]
    avail = J("results/e2e", "e2e_report_v11.json")["licensing_endpoints"]
    table["grammar_expressible_G0"]["availability_v4u"] = avail["availability_v4u"]
    table["grammar_expressible_G0"]["retained_set_median"] = e2e["set_size"]["median"]
    table["grammar_expressible_G0"]["antichain_median"] = e2e["maximal_set_size"]["median"]

    # ---- monitoring funnel (disjoint at every level)
    rep = J("results/conformal", "benchmark_sg", "report.json")
    cp = rep["counts"]["prometheus"]
    prov = J("results/e2e", "downstream_provenance.json")["verdicts"]
    anchor = J("results/e2e", "class_ladder.json")["compiled_anchor"]
    ct = Counter((anchor[k]["status"], prov[k]["verdict"]) for k in anchor)
    pcb = J("results/e2e", "policy_class_budget.json")
    fires = {r["rule_id"]: r["screen_fires"] for r in pcb["rows"] if r["policy_class"] == "monitoring_compiled"
             and abs(r["budget"] - 0.05) < 1e-9 and r["status"] == "compiled"}
    fire_f = sum(1 for k, f in fires.items() if f and prov[k]["verdict"] == "FAITHFUL")
    fire_all = sum(1 for f in fires.values() if f)
    monitoring = dict(
        rule_records=cp["parsed"] + cp["skipped"]["out_of_dsl_expr"] + cp["skipped"]["no_text"] + cp["skipped"]["not_alert"],
        recording_rules_not_alerts=cp["skipped"]["not_alert"],
        alerts=cp["parsed"] + cp["skipped"]["out_of_dsl_expr"] + cp["skipped"]["no_text"],
        alerts_without_text=cp["skipped"]["no_text"],
        alerts_with_text=cp["parsed"] + cp["skipped"]["out_of_dsl_expr"],
        outside_six_tuple_grammar=cp["skipped"]["out_of_dsl_expr"],
        compiled=cp["parsed"],
        compiled_faithful=sum(v for (s, f), v in ct.items() if f == "FAITHFUL"),
        compiled_lossy=sum(v for (s, f), v in ct.items() if f == "LOSSY"),
        analyzable=sum(v for (s, f), v in ct.items() if s in ("compiled", "provably_clear_nested")),
        solved=sum(v for (s, f), v in ct.items() if s == "compiled"),
        clear_by_nesting=sum(v for (s, f), v in ct.items() if s == "provably_clear_nested"),
        outside_compiled_control_grammar=sum(v for (s, f), v in ct.items() if s == "unanalyzed_outside_grammar"),
        analyzable_faithful=sum(v for (s, f), v in ct.items() if s in ("compiled", "provably_clear_nested") and f == "FAITHFUL"),
        solved_faithful=ct[("compiled", "FAITHFUL")], nested_faithful=ct[("provably_clear_nested", "FAITHFUL")],
        unanalyzed_faithful=ct[("unanalyzed_outside_grammar", "FAITHFUL")],
        screen_fires=fire_all, screen_fires_faithful=fire_f)
    assert monitoring["compiled"] == 88 and monitoring["analyzable"] == 60 and monitoring["solved"] == 28
    assert monitoring["analyzable_faithful"] == 26 and monitoring["screen_fires"] == 1 and fire_f == 0

    # ---- admission funnel (rule level, disjoint), recomputed from the parser
    os.environ.setdefault("SAORL_CONFORMAL", "1")
    from saorl.benchmark_sg.parse import kyverno_oodsl, parse_kyverno
    kept, sk = parse_kyverno()
    ood = kyverno_oodsl()
    ck = rep["counts"]["kyverno"]
    assert sk["curated_kept"] == 44 == ck["n_pools"] and sk["raw_parsed"] == ck["skipped"]["raw_parsed"]
    assert sk["no_validate"] == ck["skipped"]["no_validate"] and sk["unmodelled_validate"] == ck["skipped"]["unmodelled_validate"]
    assert len(ood) == ck["oodsl_with_text"] == 260
    rule_total = sk["no_validate"] + sk["unmodelled_validate"] + sk.get("no_kinds", 0) + sk.get("duplicate", 0) + sk["raw_parsed"]
    admission = dict(
        validate_rules_in_policy_documents=rule_total,
        no_validate_block=sk["no_validate"], validate_outside_compiled_families=sk["unmodelled_validate"],
        no_match_kinds=sk.get("no_kinds", 0), duplicate_rules=sk.get("duplicate", 0),
        in_grammar_before_curation=sk["raw_parsed"], removed_by_curation=sk["raw_parsed"] - sk["curated_kept"],
        curated_pools=sk["curated_kept"],
        policies_out_of_grammar_with_text=len(ood),
        previously_printed_304_is=f"{sk['curated_kept']} pools + {len(ood)} out-of-grammar POLICIES (document level), not a rule-level partition",
        curation_rule="per-family caps (field_constraint 14, required_labels 11, others 8) and dedup on (policy, rule, structure)")

    # ---- operational funnel, three populations
    ec = J("results/conformal", "lp", "expected_cost_certificate.json")["domains"]
    dep = J("results/conformal", "lp", "deploy_certificate.json")["domains"]
    ships = {d: ec[d]["arms"]["corset"]["n_certified_at_budget"] for d in ec}
    ps = J("results/e2e", "policy_sufficiency.json")["aggregate_at_operating"]
    ksweep_note = "calibrated retained sets (antichain median %d) exceed the exact DECIDE threshold; PROTECT by the fallback rule" % e2e["maximal_set_size"]["median"]
    funnel = dict(
        open_corpus=dict(raw_rules=len(units), faithful_representable=sum(1 for u in units if u["g0_expr"] and u["faithful"]),
                         representable_recorded=sum(u["g0_expr"] for u in units),
                         generated=sum(u["g0_lic"] for u in units), generated_faithful=sum(1 for u in units if u["g0_lic"] and u["faithful"]),
                         retained=sum(u["g0_ret"] for u in units), retained_faithful=sum(1 for u in units if u["g0_ret"] and u["faithful"]),
                         decide="not run", decide_note=ksweep_note, learned=None, certificate=None, ships=None),
        pinned_public_rules=dict(raw_rules=monitoring["compiled"], faithful_representable=monitoring["compiled_faithful"],
                                 analyzable=monitoring["analyzable"], analyzable_faithful=monitoring["analyzable_faithful"],
                                 set_protected=monitoring["screen_fires"], set_protected_faithful=fire_f,
                                 singleton_certified=ps["n_policy_sufficient_exists"], singleton_candidates=ps["n_value_clear"],
                                 solved=ps["n_instances"], learned=None, certificate=None, ships=None),
        controlled_domains={d: dict(readings=len(dep[d]["U"]), maximal=dep[d]["w"], seeds=50, ships_set=ships[d],
                                    ships_single=ec[d]["arms"]["single"]["n_certified_at_budget"]) for d in ec})
    res = dict(registration="W1/W6/W7 accounting, 2026-09-02; per-unit recomputation; anchors asserted",
               accounting=table, monitoring_funnel=monitoring, admission_funnel=admission, operational_funnel=funnel,
               faithful_definition="gold needs no capability beyond its grammar class (the audit's strict 'faithful' bucket; structural and representational extras are excluded)")
    json.dump(res, open(OUT, "w"), indent=1)
    for name in table:
        t = table[name]
        print(f"{name:26s} n={t['recorded_G0']['n']:5d} G0 reach {t['recorded_G0']['reach']:.3f} prop {t['recorded_G0']['proposal'] or 0:.3f} "
              f"ret {t['recorded_G0']['retention'] or 0:.3f} e2e {t['recorded_G0']['e2e']:.4f} | faithful e2e {t['faithful_G0']['e2e']:.4f} "
              f"prop {t['faithful_G0']['proposal'] or 0:.3f} ret {t['faithful_G0']['retention'] or 0:.3f} || G1 e2e {t['recorded_G1']['e2e']:.4f} faithful {t['faithful_G1']['e2e']:.4f}")
    print(json.dumps(dict(monitoring=monitoring, admission=admission), indent=1))


if __name__ == "__main__":
    main()
