#!/usr/bin/env python3
"""Emit the fragments for the evidence added to Section 5 and the appendix:
the self-consistency language baseline, the safe-return frontier, and the
budget / tail-level operating-point sweeps.

Reads only archived run files and raises rather than emitting a placeholder,
so a build cannot contain an unresolved number.  Each claim the body makes
about these runs is asserted here, not just formatted: if a rerun ever flips
a direction, this refuses to emit and the sentence has to change.

Run: python3 scripts/paper/make_gen_extra.py
"""
from __future__ import annotations

import glob
import json
import os
import re
import statistics as st

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
GEN = os.path.join(ROOT, "paper", "generated")

HEAD = "% AUTO-GENERATED by paper/final/make_gen_extra.py -- do not edit\n"


def load(*parts: str):
    with open(os.path.join(REPO, *parts)) as fh:
        return json.load(fh)


def dig(obj, path: str):
    for key in path.split("/"):
        obj = obj[key]
    return obj


def write(name: str, text: str) -> None:
    with open(os.path.join(GEN, name), "w") as fh:
        fh.write(HEAD + text)
    print("wrote", os.path.join(GEN, name))


def selfconsistency() -> list[str]:
    """W23: majority-vote several recorded LM programs into ONE cost.

    The body's claim is that this is the strongest 'one cost from text'
    recipe short of keeping a set, and that it still under-protects at
    matched return -- so assert both halves: violation strictly worse, and
    return within a seed standard deviation.
    """
    d = load("results/conformal", "selfconsistency.json")
    by = {}
    for row in d["rows"]:
        by.setdefault(row["policy"], []).append(row)
    vote, arrow = by["llm-code"], by["SA-ORL"]
    if len(vote) != len(arrow):
        raise AssertionError("self-consistency arms have different seed counts")
    seeds = len(vote)

    def agg(rows, key):
        vals = [r[key] for r in rows]
        return st.mean(vals), st.pstdev(vals)

    v_ret, v_ret_sd = agg(vote, "ret")
    a_ret, a_ret_sd = agg(arrow, "ret")
    v_worst, v_worst_sd = agg(vote, "worst")
    a_worst, a_worst_sd = agg(arrow, "worst")
    v_viol, _ = agg(vote, "chance")
    a_viol, _ = agg(arrow, "chance")
    if not a_worst < v_worst or not a_viol < v_viol:
        raise AssertionError("the self-consistency vote no longer under-protects "
                             f"(worst {v_worst:.3f} vs {a_worst:.3f}, violation "
                             f"{v_viol:.3f} vs {a_viol:.3f}); Section 5.1 says it does")
    if abs(v_ret - a_ret) > v_ret_sd:
        raise AssertionError(f"returns are no longer matched ({v_ret:.1f} vs "
                             f"{a_ret:.1f}, sd {v_ret_sd:.1f}); Section 5.1 says they are")

    write("gen_selfcons_macros.tex", "".join([
        f"\\newcommand{{\\ScPrograms}}{{{d['n_programs']}}}\n",
        f"\\newcommand{{\\ScMajority}}{{{d['majority']}}}\n",
        f"\\newcommand{{\\ScSeeds}}{{{seeds}}}\n",
        f"\\newcommand{{\\ScViolVote}}{{{100 * v_viol:.1f}\\%}}\n",
        f"\\newcommand{{\\ScViolArrow}}{{{100 * a_viol:.1f}\\%}}\n",
    ]))
    return [
        f"Self-consistency vote (single cost) & ${v_ret:.1f}\\pm{v_ret_sd:.1f}$ & "
        f"${v_worst:.3f}\\pm{v_worst_sd:.3f}$ & ${v_viol:.3f}$ \\\\\n",
        f"Full retained set (calibrated) & ${a_ret:.1f}\\pm{a_ret_sd:.1f}$ & "
        f"${a_worst:.3f}\\pm{a_worst_sd:.3f}$ & ${a_viol:.3f}$ \\\\\n",
    ]


def frontier() -> None:
    """E5: the highest-return policy in the evaluated zoo that is actually
    safe against the retained set.  The body says the best safe competitor
    matches ARROW where one exists at all, so bound how far it can be ahead.
    """
    rows = open(os.path.join(GEN, "gen_frontier.tex")).read().splitlines()
    margins = []
    for row in rows:
        if row.startswith("%") or "&" not in row:
            continue
        cell = row.split("&")[-1].replace("\\\\", "").strip()
        if cell not in ("---", "--", ""):
            margins.append(float(cell.strip("$").replace("+", "")))
    if not margins:
        raise AssertionError("gen_frontier.tex has no numeric margins")
    if max(margins) >= 1.0:
        raise AssertionError(f"a safe competitor now beats ARROW by {max(margins)} "
                             "return; Section 5.3 says the frontier is matched")
    write("gen_frontier_macros.tex",
          f"\\newcommand{{\\FrontierMargin}}{{{max(margins):.2f}}}\n"
          f"\\newcommand{{\\FrontierNone}}{{{sum(1 for r in rows if 'none' in r)}}}\n")


def sweeps() -> None:
    """#8: is the headline operating point cherry-picked?  The budget arm
    RE-LEARNS both policies at each budget; the tail arm RE-SCORES the
    headline policies at each CVaR level (only CVaR_beta moves by
    construction).  The body distinguishes the two, so keep them separate.
    """
    path = sorted(glob.glob(os.path.join(REPO, "results/paper_extra", "pareto",
                                         "pareto_risk_*.json")))[-1]
    with open(path) as fh:
        d = json.load(fh)
    cfg = d["config"]
    label = {"real": "C-MAPSS", "synthetic": "Maint.\\ (synthetic)"}

    budget, n_budget = [], 0
    for dom, rows in d["budget"].items():
        for r in rows:
            s, a = r["single"], r["saorl"]
            if not (a["true_worst"][0] < s["true_worst"][0]
                    and a["chance"][0] < s["chance"][0]):
                raise AssertionError(f"budget cell {dom}/eps={r['eps']} no longer "
                                     "favours the retained set; Section 5.3 says every one does")
            n_budget += 1
            budget.append(f"{label[dom]} & ${r['eps']}$ & ${s['ret'][0]:.1f}$ & "
                          f"${s['true_worst'][0]:.3f}$ & ${s['chance'][0]:.3f}$ & "
                          f"${a['ret'][0]:.1f}$ & ${a['true_worst'][0]:.3f}$ & "
                          f"${a['chance'][0]:.3f}$ \\\\\n")

    tail, n_tail = [], 0
    for dom, rows in d["beta"].items():
        for r in rows:
            s, a = r["single"], r["saorl"]
            if not a["cvar"][0] < s["cvar"][0]:
                raise AssertionError(f"tail cell {dom}/beta={r['beta']} no longer "
                                     "favours the retained set; Section 5.3 says every one does")
            n_tail += 1
            tail.append(f"{label[dom]} & ${r['beta']}$ & ${s['cvar'][0]:.2f}$ & "
                        f"${a['cvar'][0]:.2f}$ \\\\\n")

    write("gen_sweep_budget.tex", "".join(budget))
    write("gen_sweep_tail.tex", "".join(tail))
    write("gen_sweep_macros.tex", "".join([
        f"\\newcommand{{\\SweepEpsLo}}{{{min(cfg['eps_grid'])}}}\n",
        f"\\newcommand{{\\SweepEpsHi}}{{{max(cfg['eps_grid'])}}}\n",
        f"\\newcommand{{\\SweepBetaLo}}{{{min(cfg['beta_grid'])}}}\n",
        f"\\newcommand{{\\SweepBetaHi}}{{{max(cfg['beta_grid'])}}}\n",
        f"\\newcommand{{\\SweepBudgetCells}}{{{n_budget}}}\n",
        f"\\newcommand{{\\SweepTailCells}}{{{n_tail}}}\n",
        f"\\newcommand{{\\SweepSeeds}}{{{len(cfg['seeds'])}}}\n",
    ]))


def funnel() -> None:
    """The end-to-end decomposition Section 5.4 states:
    P(psi_dagger in U) = P(in U | expressible) * P(expressible).
    Assert the three factors actually multiply out to the archived
    end-to-end rate before the body claims they do.
    """
    t4 = dig(load("results/e2e", "e2e_report_v4.json"), "modes/complete/test")
    expressible = t4["n_grammar_reachable"] / t4["n_units"]
    gen = dig(t4, "rho_gen/point")
    ret = dig(t4, "rho_ret_given_gen/point")
    e2e = dig(t4, "rho_e2e/point")
    if abs(expressible * gen * ret - e2e) > 5e-3:
        raise AssertionError(f"the funnel no longer multiplies out: "
                             f"{expressible:.4f}*{gen}*{ret} != {e2e}")
    write("gen_funnel.tex", "".join([
        f"\\newcommand{{\\FunnelUnits}}{{{t4['n_units']}}}\n",
        f"\\newcommand{{\\FunnelExprN}}{{{t4['n_grammar_reachable']}}}\n",
        f"\\newcommand{{\\FunnelExprPct}}{{{100 * expressible:.1f}\\%}}\n",
        f"\\newcommand{{\\FunnelEtePct}}{{{100 * e2e:.1f}\\%}}\n",
    ]))


def main() -> None:
    write("gen_selfcons_table.tex", "".join(selfconsistency()))
    frontier()
    sweeps()
    funnel()


if __name__ == "__main__":
    main()
