"""Emit generated/gen_e5_side.tex: Table 5's two panels laid out side by side.

Panel A (domains) and panel B (constraint mechanisms) each have four rows, so
the body table places them beside each other rather than stacked.  This joins
the two archive-derived fragments row by row instead of restating either, so
neither panel can drift from the numbers its own generator emitted.

Run: python3 scripts/paper/make_gen_e5_side.py   (after make_gen_e5b.py)
"""
import os

PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "paper"))
GEN = os.path.join(PAPER, "generated")


def rows(name):
    out = []
    for line in open(os.path.join(GEN, name)):
        line = line.strip()
        if line and not line.startswith("%"):
            out.append(line.rstrip("\\").strip())
    return out


a, b = rows("gen_learn_table.tex"), rows("gen_e5b.tex")
assert len(a) == len(b) == 4, (len(a), len(b))
joined = "".join(f"{ra} & {rb} \\\\\n" for ra, rb in zip(a, b))
path = os.path.join(GEN, "gen_e5_side.tex")
open(path, "w").write(
    "% AUTO-GENERATED by paper/final/make_gen_e5_side.py -- do not edit\n" + joined)
print("wrote", path)
print(joined)
