#!/usr/bin/env python3
"""Emit the budget-sweep fragments (Table 10 and its two macros) from the
archived pareto_risk run on the maintenance domains.

Reads only archived run files and raises rather than emitting a placeholder,
so a build cannot contain an unresolved number.  Each claim the body makes
about these runs is asserted here, not just formatted: if a rerun ever flips
a direction, this refuses to emit and the sentence has to change.

Run: python3 scripts/paper/make_gen_extra.py
"""
from __future__ import annotations

import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
GEN = os.path.join(ROOT, "paper", "generated")

HEAD = "% AUTO-GENERATED by scripts/paper/make_gen_extra.py -- do not edit\n"


def load(*parts: str):
    with open(os.path.join(REPO, *parts)) as fh:
        return json.load(fh)


def dig(obj, path: str):
    for key in path.split("/"):
        obj = obj[key]
    return obj


def write(name: str, text: str) -> None:
    with open(os.path.join(GEN, name), "w") as fh:
        fh.write(HEAD + text)
    print("wrote", os.path.join(GEN, name))


def sweeps() -> None:
    """Budget sweep on the maintenance domains (Table 10): both policies are
    re-learned at every budget, and every cell must favour the retained set.
    """
    path = sorted(glob.glob(os.path.join(REPO, "results/paper_extra", "pareto",
                                         "pareto_risk_*.json")))[-1]
    with open(path) as fh:
        d = json.load(fh)
    cfg = d["config"]
    label = {"real": "C-MAPSS", "synthetic": "Maint.\\ (synthetic)"}

    budget, n_budget = [], 0
    for dom, rows in d["budget"].items():
        for r in rows:
            s, a = r["single"], r["saorl"]
            if not (a["true_worst"][0] < s["true_worst"][0]
                    and a["chance"][0] < s["chance"][0]):
                raise AssertionError(f"budget cell {dom}/eps={r['eps']} no longer "
                                     "favours the retained set; Section 5.3 says every one does")
            n_budget += 1
            budget.append(f"{label[dom]} & ${float(r['eps']):.2f}$ & ${s['ret'][0]:.1f}$ & "
                          f"${s['true_worst'][0]:.3f}$ & ${s['chance'][0]:.3f}$ & "
                          f"${a['ret'][0]:.1f}$ & ${a['true_worst'][0]:.3f}$ & "
                          f"${a['chance'][0]:.3f}$ \\\\\n")

    write("gen_sweep_budget.tex", "".join(budget))
    write("gen_sweep_macros.tex", "".join([
        f"\\newcommand{{\\SweepBudgetCells}}{{{n_budget}}}\n",
        f"\\newcommand{{\\SweepSeeds}}{{{len(cfg['seeds'])}}}\n",
    ]))


def main() -> None:
    sweeps()


if __name__ == "__main__":
    main()
