#!/usr/bin/env python3
"""Emit generated/gen_sota.tex (paper repo) for the prior-lines comparison (Section 5.5):
the top-ranked reading's unsafe count on the compiled rules, from results/e2e/baseline_table.json."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(ROOT, "paper")); GEN = os.path.join(PAPER, "generated")
d = json.load(open(os.path.join(ROOT, "results/e2e", "baseline_table.json")))
c = d["compiled"]["summary"]; a = d["admission"]["summary"]
assert c["top1_unsafe"] == c["top1_unsafe_untied"] + 18, "top-1 tie accounting changed"   # 2 untied + 18 tie-broken unsafe
M = [f"\\newcommand{{\\BlTopUnsafeAll}}{{{c['top1_unsafe']}}}", f"\\newcommand{{\\BlAdmTopUnsafeAll}}{{{a['top1_unsafe']}}}"]
open(os.path.join(GEN, "gen_sota.tex"), "w").write("% AUTO-GENERATED by scripts/paper/make_gen_sota.py -- do not edit\n" + "\n".join(M) + "\n"); print("\n".join(M))
