#!/usr/bin/env python3
"""Emit generated/gen_artemis_decide.tex (into the paper repo) from results/e2e/artemis_decide.json
(REGISTRATION_V23): entailment structure of the ARTEMIS retained sets."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(ROOT, "paper")); GEN = os.path.join(PAPER, "generated")
d = json.load(open(os.path.join(ROOT, "results/e2e", "artemis_decide.json")))["pools"]["P2"]["overall"]
def pct(x): return f"{100*x:.1f}\\%"
M = [f"\\newcommand{{\\ArDecUnits}}{{{d['n_units']}}}", f"\\newcommand{{\\ArDecWOne}}{{{pct(d['frac_w1'])}}}",
     f"\\newcommand{{\\ArDecWLeTwo}}{{{pct(d['frac_w_le2'])}}}", f"\\newcommand{{\\ArDecWMedian}}{{{d['w_median']:g}}}",
     f"\\newcommand{{\\ArDecWMax}}{{{d['w_max']}}}", f"\\newcommand{{\\ArDecRetainedMedian}}{{{d['retained_median']:g}}}",
     f"\\newcommand{{\\ArDecJointSat}}{{{pct(d['frac_joint_sat'])}}}", f"\\newcommand{{\\ArDecJointNo}}{{{d['joint']['no']}}}",
     f"\\newcommand{{\\ArDecJointUndecided}}{{{d['joint']['undecided']}}}",
     f"\\newcommand{{\\ArDecWOneComp}}{{{pct(1 - d['frac_w1'])}}}"]
assert d["frac_w1"] < 0.2 and d["w_median"] >= 3
open(os.path.join(GEN, "gen_artemis_decide.tex"), "w").write("% AUTO-GENERATED by paper/final/make_gen_artemis_decide.py -- do not edit\n" + "\n".join(M) + "\n")
print("\n".join(M))
