"""Emit generated/gen_v13.tex: exact policy-sufficiency (optimal-face)
macros from the V13 registered study. Asserts back every sentence.

Run: python3 scripts/paper/make_gen_v13.py
"""
from __future__ import annotations

import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, "paper", "generated", "gen_v13.tex")


def load(name):
    return json.load(open(os.path.join(ROOT, "results/e2e", name)))


def pct(x, nd=0):
    return f"{100 * x:.{nd}f}\\%"


def main() -> None:
    ps = load("policy_sufficiency.json")
    fl = load("face_live.json")

    rows = ps["rows"]
    by = {}
    for r in rows:
        d = r["budget"]
        b = by.setdefault(d, dict(n=0, clear=0, pol=0, fail_r=0))
        b["n"] += 1
        b["clear"] += (not r["screen_fires"])
        b["pol"] += r["policy_sufficient_exists"]
        b["fail_r"] += sum(1 for p in r["readings"]
                           if not p["policy_sufficient"])
    # sentences the paper states, asserted:
    assert by[0.005]["pol"] == 0 and by[0.005]["clear"] == 22
    assert by[0.05]["pol"] == by[0.05]["clear"] == 27
    assert by[0.1]["pol"] == by[0.1]["clear"] == 28
    assert by[0.02]["clear"] - by[0.02]["pol"] == 5

    t5 = [p["tiebreak_safe_frac"] for r in rows if r["budget"] == 0.005
          for p in r["readings"] if "tiebreak_safe_frac" in p]
    top = [p["tiebreak_safe_frac"] for r in rows if r["budget"] == 0.05
           for p in r["readings"] if "tiebreak_safe_frac" in p]
    assert top and min(top) == 1.0, "operating-budget tie-breaks not all safe"
    assert t5 and max(t5) < 1.0, "separation-budget tie-breaks all safe?"
    ov5 = [p["W"] / r["budget"] for r in rows if r["budget"] == 0.005
           for p in r["readings"] if p["W"] is not None
           and not p["policy_sufficient"]]

    for pool in ("stipulated", "calibrated"):
        vs = fl["pools"][pool]["value_sufficient"]
        assert len(vs) == 1 and list(vs.values())[0]["policy_sufficient"]
        assert list(vs.values())[0]["face_size"] == 1

    m = ["% AUTO-GENERATED by scripts/paper/make_gen_v13.py -- do not edit",
         f"\\newcommand{{\\PsN}}{{{by[0.05]['n']}}}",
         f"\\newcommand{{\\PsClearOp}}{{{by[0.05]['clear']}}}",
         f"\\newcommand{{\\PsPolOp}}{{{by[0.05]['pol']}}}",
         f"\\newcommand{{\\PsClearTight}}{{{by[0.005]['clear']}}}",
         f"\\newcommand{{\\PsPolTight}}{{{by[0.005]['pol']}}}",
         f"\\newcommand{{\\PsClearMid}}{{{by[0.02]['clear']}}}",
         f"\\newcommand{{\\PsPolMid}}{{{by[0.02]['pol']}}}",
         f"\\newcommand{{\\PsOvershoot}}{{{np.median(ov5):.2f}$\\times$}}",
         f"\\newcommand{{\\PsTieLo}}{{{pct(min(t5))}}}",
         f"\\newcommand{{\\PsTieMed}}{{{pct(float(np.median(t5)))}}}",
         f"\\newcommand{{\\PsTieHi}}{{{pct(max(t5))}}}",
         f"\\newcommand{{\\PsTieN}}{{100}}",
         f"\\newcommand{{\\PsLiveFace}}{{1}}",
         ]
    for d, tag in ((0.005, "A"), (0.01, "B"), (0.02, "C"), (0.05, "D"),
                   (0.1, "E")):
        b = by[d]
        m += [f"\\newcommand{{\\PsG{tag}Clear}}{{{b['clear']}}}",
              f"\\newcommand{{\\PsG{tag}Pol}}{{{b['pol']}}}",
              f"\\newcommand{{\\PsG{tag}Gap}}{{{b['clear'] - b['pol']}}}"]
    with open(OUT, "w") as fh:
        fh.write("\n".join(m) + "\n")
    print("\n".join(m))


if __name__ == "__main__":
    main()
