"""Emit generated/gen_ladder.tex from results/e2e/class_ladder.json.

Every macro the class-ladder paragraphs use comes from here; each claim the
body states is asserted against the archive, so the build fails if a re-run
ever moves a number out from under its sentence.
"""
from __future__ import annotations

import json
import os
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(ROOT, "results/e2e", "class_ladder.json")
OUT = os.path.join(ROOT, "paper", "generated", "gen_ladder.tex")


def main() -> None:
    with open(SRC, encoding="utf8") as fh:
        a = json.load(fh)
    rows, OP = a["rows"], a["operating"]

    def sel(fam, k, fires=None):
        out = [r for r in rows if r["family"] == fam and r["k"] == k
               and r["budget"] == OP]
        if fires is not None:
            out = [r for r in out if r["screen_fires"] == fires]
        return out

    per = a["aggregate"]["prometheus"]["per_k"]
    kyv = a["aggregate"]["kyverno"]["per_k"]
    frontier = a["aggregate"]["prometheus"]["frontier"]
    fdist = Counter(str(v) for v in frontier.values())
    kyv_front = Counter(str(v)
                        for v in a["aggregate"]["kyverno"]["frontier"].values())

    # --- claims the body states, asserted against the archive -------------
    assert per["0"]["fires_some"] == 0 and kyv["0"]["fires_some"] == 0, \
        "a blind controller now needs set protection; Section 5.2 says never"
    free_prom = per["free"]
    assert free_prom["fires_some"] == free_prom["fires_all"], \
        "free rung has subset variation, which is impossible"
    k2p = sel("prometheus", 2)
    by_pool = {}
    for r in k2p:
        by_pool.setdefault(r["rule_id"], []).append(r)
    varies = sum(1 for rs in by_pool.values()
                 if len({r["screen_fires"] for r in rs}) == 2)
    multi = sum(1 for rs in by_pool.values() if len(rs) >= 2)
    trunc = sum(1 for rs in by_pool.values() if any(r["truncated"] for r in rs))
    kf2 = {r["rule_id"] for r in sel("kyverno", 2, True)}
    kff = {r["rule_id"] for r in sel("kyverno", "free", True)}
    assert kf2 == kff and len(kf2) == kyv["2"]["fires_some"], \
        "kyverno k=2 firing pools no longer match the published free pools"
    pf2 = {r["rule_id"] for r in sel("prometheus", 2, True)}
    pff = {r["rule_id"] for r in sel("prometheus", "free", True)}
    nonmono = len(pf2 - pff)
    assert nonmono > 0, \
        "no pool fires mid-ladder while clearing free; Section 5.2 states " \
        "non-monotonicity from that set"
    n_never = int(fdist.get("None", 0))
    assert int(fdist.get("1", 0)) + int(fdist.get("2", 0)) + n_never \
        == free_prom["n_pools"], "frontier accounting broke"

    m = []
    m.append("% AUTO-GENERATED by paper/final/make_gen_ladder.py -- do not edit")
    m.append(f"\\newcommand{{\\LadPromN}}{{{free_prom['n_pools']}}}")
    m.append(f"\\newcommand{{\\LadKyvN}}{{{kyv['free']['n_pools']}}}")
    m.append(f"\\newcommand{{\\LadKZeroFires}}{{{per['0']['fires_some']}}}")
    m.append(f"\\newcommand{{\\LadKOneFires}}{{{per['1']['fires_some']}}}")
    m.append(f"\\newcommand{{\\LadKTwoSome}}{{{per['2']['fires_some']}}}")
    m.append(f"\\newcommand{{\\LadKTwoSomeN}}{{{per['2']['n_pools']}}}")
    m.append(f"\\newcommand{{\\LadKTwoAll}}{{{per['2']['fires_all']}}}")
    m.append(f"\\newcommand{{\\LadKTwoVaries}}{{{varies}}}")
    m.append(f"\\newcommand{{\\LadKTwoVarN}}{{{multi}}}")
    m.append(f"\\newcommand{{\\LadKTwoTrunc}}{{{trunc}}}")
    m.append(f"\\newcommand{{\\LadFrontOne}}{{{fdist.get('1', 0)}}}")
    m.append(f"\\newcommand{{\\LadFrontTwo}}{{{fdist.get('2', 0)}}}")
    m.append(f"\\newcommand{{\\LadFrontNever}}{{{n_never}}}")
    m.append(f"\\newcommand{{\\LadFreeFires}}{{{free_prom['fires_some']}}}")
    m.append(f"\\newcommand{{\\LadNonMono}}{{{nonmono}}}")
    m.append(f"\\newcommand{{\\LadKyvFrontTwo}}{{{kyv_front.get('2', 0)}}}")
    m.append(f"\\newcommand{{\\LadKyvNever}}{{{kyv_front.get('None', 0)}}}")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf8") as fh:
        fh.write("\n".join(m) + "\n")
    print("\n".join(m))


if __name__ == "__main__":
    main()
