"""Emit generated/gen_v14.tex: face-level ladder + admission face macros
(REGISTRATION_V14). Asserts: prom face numbers equal the published value
ladder exactly (the survival claim); kyverno face-need superset of
value-fires; per-pool face implies-value containment already asserted in
the producing run.
Run: python3 scripts/paper/make_gen_v14.py
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
fl = json.load(open(os.path.join(ROOT, "results/e2e", "face_ladder.json")))
p, k = fl["aggregate"]["prometheus"], fl["aggregate"]["kyverno"]
assert (p["k0_fires"], p["k1_fires"], p["k2_some"], p["k2_all"],
        p["free_fires"], p["frontier_one"], p["frontier_two"],
        p["frontier_never"], p["non_monotone"]) == (0, 7, 64, 4, 61, 7, 57, 24, 3), \
    "the prom face ladder no longer equals the published value ladder"
assert k["free_fires"] >= 2 and k["n_pools"] == 44
m = ["% AUTO-GENERATED by scripts/paper/make_gen_v14.py -- do not edit",
     f"\\newcommand{{\\FaceKyvFails}}{{{k['free_fires']}}}",
     f"\\newcommand{{\\FaceKyvOk}}{{{44 - k['free_fires']}}}",
     f"\\newcommand{{\\FaceKyvValueOnly}}{{{k['free_fires'] - 2}}}",
     f"\\newcommand{{\\FaceLadderSurvives}}{{unchanged}}"]
open(os.path.join(ROOT, "paper", "generated", "gen_v14.tex"), "w").write("\n".join(m) + "\n")
print("\n".join(m))
