"""Emit generated/gen_v11b.tex: funnel, finer recall curve, k-sweep,
witnesses and axis shares (REGISTRATION_V11B endpoints). Every number
reconciled against its archive; directional asserts back each sentence.

Run: python3 scripts/paper/make_gen_v11b.py
"""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, "paper", "generated", "gen_v11b.tex")


def load(name):
    with open(os.path.join(ROOT, "results/e2e", name)) as fh:
        return json.load(fh)


def pct(x, nd=1):
    return f"{100 * x:.{nd}f}\\%"


def main() -> None:
    rd = load("v11b_readouts.json")
    pw = load("pool_axes_witnesses.json")
    ks = load("ksweep_v11.json")
    rep = load("e2e_report_v11.json")

    f = rd["funnel"]
    assert f["n_corpus"] == 4390 and f["n_expr"] == 315
    assert f["n_lic"] == rep["modes"]["complete"]["test"]["n_in_dsl"]
    assert f["n_lic_avail"] + f["n_lic_verbatim_only"] == f["n_lic"]
    assert abs(f["of_corpus"]["ret"] -
               rep["modes"]["complete"]["test"]["rho_e2e"]["point"]) < 5e-4

    rc = rd["recall_fine"]
    assert rc["1"] <= rc["4"] <= rc["16"] <= rc["64"] <= rc["256"]
    assert abs(rc["64"] - rep["licensing_endpoints"]["recall"]["v11"]["64"]) < 5e-4

    assert pw["witness_coverage"] == 1.0
    assert pw["classes_total"] < pw["candidates_total"], \
        "dedup removed nothing; the paraphrase sentence must change"
    ax = pw["axis_share"]
    assert ax["threshold"] == max(ax.values()), \
        "threshold is no longer the leading ambiguity axis"

    rows = {r["k"]: r for r in ks["rows"]}
    assert set(rows) == {16, 64, 256}
    assert rows[64].get("registered"), "k=64 row must come from its archive"
    assert rows[16]["rho_gen"]["point"] < rows[64]["rho_gen"]["point"] \
        < rows[256]["rho_gen"]["point"], "recall is not monotone in k"

    m = ["% AUTO-GENERATED by paper/final/make_gen_v11b.py -- do not edit"]
    m += [f"\\newcommand{{\\FvCorpus}}{{{f['n_corpus']}}}",
          f"\\newcommand{{\\FvExprN}}{{{f['n_expr']}}}",
          f"\\newcommand{{\\FvAvailN}}{{{f['n_avail']}}}",
          f"\\newcommand{{\\FvLicN}}{{{f['n_lic']}}}",
          f"\\newcommand{{\\FvRetN}}{{{f['n_ret']}}}",
          f"\\newcommand{{\\FvExprPct}}{{{pct(f['cond']['expr'])}}}",
          f"\\newcommand{{\\FvAvailPct}}{{{pct(f['cond']['avail'])}}}",
          f"\\newcommand{{\\FvLicAvailPct}}{{{pct(f['cond']['lic_given_avail'])}}}",
          f"\\newcommand{{\\FvRetLicPct}}{{{pct(f['cond']['ret_given_lic'])}}}",
          f"\\newcommand{{\\FvOcAvail}}{{{pct(f['of_corpus']['avail'])}}}",
          f"\\newcommand{{\\FvOcLic}}{{{pct(f['of_corpus']['lic'])}}}",
          f"\\newcommand{{\\FvOcRet}}{{{pct(f['of_corpus']['ret'])}}}",
          f"\\newcommand{{\\FvVerbOnly}}{{{f['n_lic_verbatim_only']}}}",
          f"\\newcommand{{\\RcOne}}{{{pct(rc['1'])}}}",
          f"\\newcommand{{\\RcFour}}{{{pct(rc['4'])}}}"]
    m += [f"\\newcommand{{\\WitPools}}{{{pw['n_pools']}}}",
          f"\\newcommand{{\\WitMulti}}{{{pw['n_pools_multi']}}}",
          f"\\newcommand{{\\WitPairs}}{{{pw['pairs_total']}}}",
          f"\\newcommand{{\\WitCands}}{{{pw['candidates_total']}}}",
          f"\\newcommand{{\\WitClasses}}{{{pw['classes_total']}}}",
          f"\\newcommand{{\\AxThr}}{{{pct(ax['threshold'])}}}",
          f"\\newcommand{{\\AxFor}}{{{pct(ax['for_s'])}}}",
          f"\\newcommand{{\\AxCmp}}{{{pct(ax['comparator'])}}}",
          f"\\newcommand{{\\AxAgg}}{{{pct(ax['aggregation'])}}}",
          f"\\newcommand{{\\AxWin}}{{{pct(ax['window'])}}}"]
    for k in (16, 64, 256):
        r = rows[k]
        tag = {16: "Sixteen", 64: "SixtyFour", 256: "TwoFiftySix"}[k]
        m += [f"\\newcommand{{\\Ks{tag}Gen}}{{{pct(r['rho_gen']['point'])}}}",
              f"\\newcommand{{\\Ks{tag}Ret}}{{{pct(r['rho_ret_given_gen']['point'])}}}",
              f"\\newcommand{{\\Ks{tag}Ete}}{{{pct(r['rho_e2e']['point'])}}}",
              f"\\newcommand{{\\Ks{tag}SetMed}}{{{r['set_size']['median']:,}}}",
              f"\\newcommand{{\\Ks{tag}MaxMed}}{{{r['maximal_set_size']['median']:,}}}"]
    with open(OUT, "w") as fh:
        fh.write("\n".join(m) + "\n")
    print("\n".join(m))


if __name__ == "__main__":
    main()
