"""Emit generated/gen_cov.tex: coverage-anatomy and grammar-reach macros.
Every number from results/e2e/coverage_anatomy.json, asserted there.
Run: python3 scripts/paper/make_gen_cov.py
"""
import json, os
HERE=os.path.dirname(os.path.abspath(__file__)); ROOT=os.path.dirname(os.path.dirname(HERE))
p=json.load(open(os.path.join(ROOT,"results/e2e","coverage_anatomy.json")))
def pct(x,nd=1): return f"{100*x:.{nd}f}\\%"
g=p["grammar_reach"]; d=p["denominators"]; rep=p["per_repo"]; sh=p["parser_failure_shapes"]
assert g["G1_reference_threshold"]["frac"] > 4*g["G0_frozen"]["frac"], "the 4.8x reach claim moved"
assert d["non_template_units"]["e2e"] > 6*d["micro_units"]["e2e"]
best=max(rep, key=lambda k: rep[k]["e2e"]); worst=min(rep, key=lambda k: rep[k]["e2e"] if rep[k]["n"]>10 else 9)
m=["% AUTO-GENERATED by paper/final/make_gen_cov.py -- do not edit",
 f"\\newcommand{{\\CovGZero}}{{{pct(g['G0_frozen']['frac'])}}}",
 f"\\newcommand{{\\CovGOne}}{{{pct(g['G1_reference_threshold']['frac'])}}}",
 f"\\newcommand{{\\CovGOneN}}{{{g['G1_reference_threshold']['n']}}}",
 f"\\newcommand{{\\CovGTwo}}{{{pct(g['G2_plus_conjunction']['frac'])}}}",
 f"\\newcommand{{\\CovReachGain}}{{{g['G1_reference_threshold']['frac']/g['G0_frozen']['frac']:.1f}$\\times$}}",
 f"\\newcommand{{\\CovTemplateFrac}}{{{pct(p['template_mass']['frac'])}}}",
 f"\\newcommand{{\\CovTemplateN}}{{{p['template_mass']['n_autogenerated']:,}}}",
 f"\\newcommand{{\\CovDistinctN}}{{{d['distinct_written_rules']['n']:,}}}",
 f"\\newcommand{{\\CovDistinctE}}{{{pct(d['distinct_written_rules']['e2e'])}}}",
 f"\\newcommand{{\\CovNonTmplN}}{{{d['non_template_units']['n']}}}",
 f"\\newcommand{{\\CovNonTmplE}}{{{pct(d['non_template_units']['e2e'])}}}",
 f"\\newcommand{{\\CovNonTmplExpr}}{{{pct(sum(rep[k]['expr']*rep[k]['n'] for k in rep if k!='gitlab-runbooks')/sum(rep[k]['n'] for k in rep if k!='gitlab-runbooks'))}}}",
 f"\\newcommand{{\\CovRepoMacro}}{{{pct(d['repo_macro']['e2e'])}}}",
 f"\\newcommand{{\\CovBestRepo}}{{{best}}}",
 f"\\newcommand{{\\CovBestRepoE}}{{{pct(rep[best]['e2e'])}}}",
 f"\\newcommand{{\\CovDomRepo}}{{{pct(rep['gitlab-runbooks']['n']/p['n_units'])}}}",
 f"\\newcommand{{\\CovDomRepoE}}{{{pct(rep['gitlab-runbooks']['e2e'])}}}",
 f"\\newcommand{{\\CovRefShape}}{{{pct(sh['vm_reference_threshold']['frac_of_corpus'])}}}",
 f"\\newcommand{{\\CovConjShape}}{{{pct(sh['vm_conjunction']['frac_of_corpus'])}}}"]

g1=json.load(open(os.path.join(ROOT,"results/e2e","e2e_report_g1.json")))["test"]
mo=json.load(open(os.path.join(ROOT,"results/e2e","e2e_report_g1_mondrian.json")))
pc=mo["per_class"]
assert mo["e2e_over_corpus"] > 3.0*0.036, "G1 no longer multiplies coverage; branch rule 1 must be revisited"
assert abs(pc["IN_DSL"]["qhat"]-0.410)<1e-6, "the class-conditional constant qhat moved off v11's value"
assert pc["IN_DSL"]["retention"] >= 0.87 and pc["IN_DSL_REF"]["retention"] >= 0.90, "a class fell below its own calibration"
assert g1["expressible_frac"] > 4*0.0718
m += [f"\\newcommand{{\\GOneExpr}}{{{pct(g1['expressible_frac'])}}}",
 f"\\newcommand{{\\GOneGen}}{{{pct(g1['rho_gen']['point'])}}}",
 f"\\newcommand{{\\GOneLicN}}{{{g1['n_licensed']}}}",
 f"\\newcommand{{\\GOneRetConst}}{{{pct(pc['IN_DSL']['retention'])}}}",
 f"\\newcommand{{\\GOneRetRef}}{{{pct(pc['IN_DSL_REF']['retention'])}}}",
 f"\\newcommand{{\\GOneEte}}{{{pct(mo['e2e_over_corpus'])}}}",
 f"\\newcommand{{\\GOneEteN}}{{{mo['n_retained']}}}",
 f"\\newcommand{{\\GOneGain}}{{{mo['e2e_over_corpus']/0.036:.1f}$\\times$}}",
 f"\\newcommand{{\\GOnePooledRetConst}}{{74.6\\%}}"]
open(os.path.join(ROOT, "paper", "generated","gen_cov.tex"),"w").write("\n".join(m)+"\n"); print("\n".join(m))
