"""Emit generated/gen_e5_prose.tex: prose macros for the cells of the body's
learned-policy table (domains panel A, constraint mechanisms panel B).

The Section 5.2 Finding quotes every violation rate and worst retained cost
in running text.  Those numbers live in gen_learn_table.tex and gen_e5b.tex,
which are table-row fragments, so this script lifts each cell into a named
macro and asserts the row labels it expects.  Nothing is recomputed here.

Run: python3 scripts/paper/make_gen_e5_prose.py   (after make_gen_e5_side.py)
"""
import os
import re

PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "paper"))
GEN = os.path.join(PAPER, "generated")


def rows(name):
    out = []
    for line in open(os.path.join(GEN, name)):
        line = line.strip()
        if line and not line.startswith("%"):
            out.append([c.strip() for c in line.rstrip("\\").split("&")])
    return out


def strip_math(cell):
    return cell.strip("$")


a, b = rows("gen_learn_table.tex"), rows("gen_e5b.tex")
labels_a = [r[0] for r in a]
labels_b = [r[0] for r in b]
assert labels_a == ["Synthetic maintenance", "C-MAPSS replay MDP",
                    "Warning-window", "Budget agent"], labels_a
assert labels_b == ["BCQ-FQI (tabular)", "CQL (neural)",
                    "PID-Lagrangian", "CPQ"], labels_b

keys_a = ["Syn", "Cmapss", "Warn", "Agent"]
keys_b = ["Bcq", "Cql", "Pid", "Cpq"]
L = ["% AUTO-GENERATED by paper/final/make_gen_e5_prose.py -- do not edit"]
for k, r in zip(keys_a, a):
    one, arrow, price = (strip_math(c) for c in r[1:4])
    for c in (one, arrow, price):
        assert re.fullmatch(r"\d+(\.\d+)?\\%", c), c
    L += [r"\newcommand{\LvOne%s}{%s}" % (k, one),
          r"\newcommand{\LvArrow%s}{%s}" % (k, arrow),
          r"\newcommand{\LvPrice%s}{%s}" % (k, price)]
for k, r in zip(keys_b, b):
    one, arrow = (strip_math(c) for c in r[1:3])
    for c in (one, arrow):
        assert re.fullmatch(r"\d\.\d{3}", c), c
    L += [r"\newcommand{\McOne%s}{%s}" % (k, one),
          r"\newcommand{\McArrow%s}{%s}" % (k, arrow)]
path = os.path.join(GEN, "gen_e5_prose.tex")
open(path, "w").write("\n".join(L) + "\n")
print("wrote", path)
print("\n".join(L))
