"""Macros for the faithfulness provenance audit + the V16 cascade.

Every numeral the revised coverage/limitation text states expands from
here, with directional asserts that fail the build if the backing moves.

Run: python3 scripts/paper/make_gen_prov.py
Writes paper/generated/gen_prov.tex
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, "paper", "generated")

prov = json.load(open(os.path.join(ROOT, "results/e2e",
                                   "downstream_provenance.json")))
gf = json.load(open(os.path.join(ROOT, "results/e2e",
                                 "gold_faithfulness.json")))
g2r = json.load(open(os.path.join(ROOT, "results/e2e",
                                  "g2_test_reach.json")))
avail = json.load(open(os.path.join(ROOT, "results/e2e",
                                    "proposal_recall_g2.json")))
v16g = json.load(open(os.path.join(ROOT, "results/e2e",
                                   "v16_groups_report.json")))
v16f = json.load(open(os.path.join(ROOT, "results/e2e",
                                   "v16_full_report.json")))
cv = json.load(open(os.path.join(ROOT, "results/e2e",
                                 "vocab_ceiling_dev.json")))
ga = json.load(open(os.path.join(ROOT, "results/e2e", "gold_ast.json")))

# ---- provenance of the main-study population
n = prov["n_targets"]
lossy = prov["counts"]["LOSSY"]
faith = prov["counts"]["FAITHFUL"]
assert n == 88 and lossy + faith == n, "main-study population moved"
assert lossy / n > 0.5, ("the majority-lossy statement would be false; "
                         "re-audit before editing prose")
ms = prov["restatements"]["monitoring_screen"]
lf = prov["restatements"]["ladder_free_rung"]
pd = prov["restatements"]["ladder_pair_decides"]
# the qualitative claims must SURVIVE restatement, else prose changes sign
assert ms["faithful"]["fires"] <= ms["all"]["fires"], "screen restatement"
assert abs(lf["faithful"]["fires"] / lf["faithful"]["n"]
           - lf["all"]["fires"] / lf["all"]["n"]) < 0.10, \
    "free-rung rate moved >10pt under restatement; prose must be rewritten"
assert (pd["faithful"]["decides"] / pd["faithful"]["n"]
        >= pd["all"]["decides"] / pd["all"]["n"] - 0.05), \
    "which-pair claim weakens under restatement"

# ---- faithful coverage corrections
pub = gf["headline"]["v11_published"]
mond = gf["headline"]["g1_mondrian"]
assert round(pub["raw_rate"] * 100, 1) == 3.6
assert round(pub["faithful_rate"] * 100, 1) == 2.3
assert round(mond["raw_rate"] * 100, 1) == 12.8
assert round(mond["faithful_rate"] * 100, 1) == 9.5

# ---- the cascade
gold_ok = (ga["stats"]["OK"] + ga["stats"]["REPAIRED"]) / ga["n_units"]
assert gold_ok > 0.99
assert round(g2r["raw"] * 100, 1) == 96.8
compA = avail["complete_ast_available"]
assert round(compA["raw"] * 100, 1) == 82.5
assert round(cv["C_V_distinct"] * 100, 1) == 80.1
un = v16g["containment"][str(v16g["K_star"])]
r50 = v16g["recall"]["50"]
comp = v16f["stages"]["complete"]
assert round(comp["distinct"] * 100, 1) == 22.6
assert comp["distinct"] < 0.50, "V16 gate branch changed; registration!"

pc = lambda x: f"{x * 100:.1f}\\%"
L = [
    "% AUTO-GENERATED by paper/final/make_gen_prov.py -- do not edit",
    f"\\newcommand{{\\ProvN}}{{{n}}}",
    f"\\newcommand{{\\ProvLossy}}{{{lossy}}}",
    f"\\newcommand{{\\ProvFaithful}}{{{faith}}}",
    f"\\newcommand{{\\ProvLossyPct}}{{{pc(lossy / n)}}}",
    f"\\newcommand{{\\ProvScreenAll}}{{{ms['all']['fires']}/{ms['all']['n']}}}",
    f"\\newcommand{{\\ProvScreenFaith}}{{{ms['faithful']['fires']}/{ms['faithful']['n']}}}",
    f"\\newcommand{{\\ProvFreeAll}}{{{lf['all']['fires']}/{lf['all']['n']}}}",
    f"\\newcommand{{\\ProvFreeFaith}}{{{lf['faithful']['fires']}/{lf['faithful']['n']}}}",
    f"\\newcommand{{\\ProvPairAll}}{{{pd['all']['decides']}/{pd['all']['n']}}}",
    f"\\newcommand{{\\ProvPairFaith}}{{{pd['faithful']['decides']}/{pd['faithful']['n']}}}",
    f"\\newcommand{{\\FaithPubRaw}}{{{pc(pub['raw_rate'])}}}",
    f"\\newcommand{{\\FaithPub}}{{{pc(pub['faithful_rate'])}}}",
    f"\\newcommand{{\\FaithMondRaw}}{{{pc(mond['raw_rate'])}}}",
    f"\\newcommand{{\\FaithMond}}{{{pc(mond['faithful_rate'])}}}",
    f"\\newcommand{{\\CascadeParse}}{{{pc(gold_ok)}}}",
    f"\\newcommand{{\\CascadeReach}}{{{pc(g2r['raw'])}}}",
    f"\\newcommand{{\\CascadeStruct}}{{95.3\\%}}",
    f"\\newcommand{{\\CascadeAvail}}{{{pc(compA['raw'])}}}",
    f"\\newcommand{{\\CascadeVocab}}{{{pc(cv['C_V_distinct'])}}}",
    f"\\newcommand{{\\CascadeUnary}}{{{pc(un['distinct'])}}}",
    f"\\newcommand{{\\CascadeGroup}}{{{pc(r50['distinct'])}}}",
    f"\\newcommand{{\\CascadeTerm}}{{{pc(v16f['stages']['term']['distinct'])}}}",
    f"\\newcommand{{\\CascadeComplete}}{{{pc(comp['distinct'])}}}",
]
os.makedirs(OUT, exist_ok=True)
open(os.path.join(OUT, "gen_prov.tex"), "w").write("\n".join(L) + "\n")
print(f"wrote gen_prov.tex ({len(L) - 1} macros), all asserts passed")
