#!/usr/bin/env python3
"""Macros for the oracle clarification study (Ql...) and the generation term of the deployment theorem on the ARTEMIS
union pool (ArKOneAny, ArKTenAny, ArGenMisses, ArDgenUcb). Every number asserted."""
import json, collections, re, os
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(os.path.dirname(HERE)) + "/"
GEN = os.path.join(ROOT, "paper", "generated") + "/"
out = []
def macro(n, v): out.append(f"\\newcommand{{\\{n}}}{{{v}}}")
def pct(x): return f"{100*x:.0f}\\%"
# ---- V26: oracle clarification ----
q = json.load(open(ROOT + "results/e2e/query_loop.json"))
assert q["branch"]["populations_where_poa_beats_split"] == 3 and q["operating_budget"] == 0.05
for pop in ("compiled", "admission", "monitoring_free"):
    for r in ("poa", "split", "random"): assert q["populations"][pop]["summary"]["rules"][r]["q"] == [0, 1, 2, 4]
cp, mf = q["populations"]["compiled"]["summary"]["rules"], q["populations"]["monitoring_free"]["summary"]["rules"]
assert abs(cp["poa"]["recovered_mean"][1] - 0.894) < 0.005 and abs(mf["poa"]["recovered_mean"][1] - 0.645) < 0.005
macro("QlBudget", "0.05"); macro("QlCompRec", pct(cp["poa"]["recovered_mean"][1])); macro("QlMonRec", pct(mf["poa"]["recovered_mean"][1]))
macro("QlCompSplit", pct(cp["split"]["recovered_mean"][1])); macro("QlMonSplit", pct(mf["split"]["recovered_mean"][1]))
macro("QlAdmRec", pct(q["populations"]["admission"]["summary"]["rules"]["poa"]["recovered_mean"][1]))
macro("QlCompN", cp and q["populations"]["compiled"]["summary"]["n"]); macro("QlMonN", q["populations"]["monitoring_free"]["summary"]["n"]); macro("QlAdmN", q["populations"]["admission"]["summary"]["n"])
# ---- ARTEMIS Recall@K ----
a = json.load(open(ROOT + "results/e2e/artemis_units.json"))
Ks = [1, 2, 5, 10, 20, None]
res = {}
for pool in ("P1", "P2"):
    per_k_cls, per_k_any = collections.defaultdict(list), collections.defaultdict(list)
    for u in a["units"]:
        trials = [t for t in u["trials"] if t["valid"] and (t["in_p1"] if pool == "P1" else True)]
        if not trials: continue
        first, cnt = {}, collections.Counter()
        for i, t in enumerate(trials):
            cnt[t["cls"]] += 1; first.setdefault(t["cls"], i)
        ranked = sorted(cnt, key=lambda c: (-cnt[c], first[c]))
        nlab = u["label_classes"]
        for K in Ks:
            top = ranked if K is None else ranked[:K]
            matched = set()
            for c in top: matched.update(u["cand_match"].get(str(c), []))
            per_k_cls[K].append(len(matched) / nlab if nlab else 0.0); per_k_any[K].append(1.0 if matched else 0.0)
    res[pool] = {K: (float(np.mean(per_k_cls[K])), float(np.mean(per_k_any[K])), len(per_k_cls[K])) for K in Ks}
# denominator: all 182 units (misses count as zero), the convention of tab:artemis; validate against the printed pool recall
gen_ar = open(GEN + "gen_artemis.tex").read()
printed = float(re.search(r"\\newcommand\{\\ArTwoPoolRecall\}\{([0-9.]+)\\%\}", gen_ar).group(1))
assert abs(100 * res["P2"][None][0] - printed) < 0.15, (res["P2"][None][0], printed)
assert res["P2"][None][2] == 182, res["P2"][None][2]
# generation term of the deployment theorem on the union pool: any-plausible coverage by candidate budget K, the number of
# generation misses among the 182 units, and a one-sided 95% Clopper-Pearson upper confidence bound on the miss probability
from scipy.stats import beta as _beta
_m = res["P2"][None][2]; _g = int(round(_m * (1 - res["P2"][None][1])))
assert _m == 182 and abs(_m * (1 - res["P2"][None][1]) - _g) < 1e-6, (_m, res["P2"][None][1])
assert res["P2"][1][1] < res["P2"][10][1] < res["P2"][None][1], "coverage must rise with the candidate budget; text must change"
macro("ArKOneAny", f"{100*res['P2'][1][1]:.1f}\\%"); macro("ArKTenAny", f"{100*res['P2'][10][1]:.1f}\\%"); macro("ArGenMisses", _g)
macro("ArDgenUcb", f"{100 * _beta.ppf(0.95, _g + 1, _m - _g):.1f}\\%")
open(GEN + "gen_applic.tex", "w").write("% generated by make_gen_applic.py -- do not edit\n" + "\n".join(out) + "\n")
print(f"gen_applic: {len(out)} macros")
print("ARTEMIS P2 recall@K:", {("all" if K is None else K): (round(res['P2'][K][0], 3), round(res['P2'][K][1], 3)) for K in Ks})
