"""Per-method comparison on the ARTEMIS benchmark (REGISTRATION_V17 data, per-method view).
Reads results/e2e/artemis_per_method.json (corset_e2e/external/artemis_per_method.py) and writes
  generated/gen_artemis_methods.tex          macros (prefix \Am...)
  generated/gen_artemis_methods_table.tex    main-body rows: one row per (method, backbone), year, per-dataset
                                             any-plausible coverage of the committed translation; then the
                                             same-sample selection rules and ARROW
  generated/gen_artemis_methods_app.tex      appendix rows: first sample / self-consistency / ARROW on the
                                             method's own samples / unfiltered samples (any, recall, size)
Asserts every direction the text states.  Run: python3 scripts/paper/make_gen_artemis_methods.py
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(os.path.dirname(HERE))
PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(ROOT, "paper")); GEN = os.path.join(PAPER, "generated")
HEAD = "% AUTO-GENERATED by paper/final/make_gen_artemis_methods.py -- do not edit\n"
d = json.load(open(os.path.join(ROOT, "results/e2e", "artemis_per_method.json")))
G = ("Ventilator", "Robotics", "LMCPS")
# artifact source name -> (display name, year, bib key); names as the artifact's own plots label them
METHODS = {
    "deepstl":             ("DeepSTL (FT)",            2022, "he2022deepstl"),
    "nl2spec":             ("nl2spec",                 2023, "hahn2022nl2spec"),
    "NL2TL":               ("NL2TL+",                  2023, "chen2023nl2tl"),
    "NL2TL-FT":            ("NL2TL+ (FT)",             2023, "chen2023nl2tl"),
    "synthtl":             ("SynthTL",                 2024, "mendoza2024synthtl"),
    "nl2ltl":              ("directTL",                2026, "mendoza2026artemis"),
    "nl2ltltemplate":      ("directTL-t",              2026, "mendoza2026artemis"),
    "nl2structnl":         ("ARTEMIS",                 2026, "mendoza2026artemis"),
    "nl2structnl-reflect": ("ARTEMIS + reflection",    2026, "mendoza2026artemis"),
}
ORDER = ["deepstl", "nl2spec", "NL2TL", "NL2TL-FT", "synthtl", "nl2ltl", "nl2ltltemplate", "nl2structnl", "nl2structnl-reflect"]
def pct(x, nd=1): return f"{100*x:.{nd}f}"
LLM = {"gemini-2.5-flash": "gemini", "gpt-4.1": "GPT"}   # as the artifact's own figures label them
def mac(name, val): return f"\\newcommand{{\\{name}}}{{{val}}}"
def cols(x, arm, key="any"): return [x["by_group"][g][arm][key] for g in G] + [x["overall"][arm][key]]

rows = []  # (src, backbone, meth, year, bib, any-cols, recall-cols)
for src in d["sources"]:
    backbone, meth = src.split("/")
    name, year, bib = METHODS[meth]
    x = d["sources"][src]
    rows.append((src, backbone, name, year, bib, cols(x, "top1"), cols(x, "top1", "recall")))
rows.sort(key=lambda r: (r[3], ORDER.index(r[0].split("/")[1]), r[1]))
assert len(rows) == 15 and all(x["overall"]["n"] == d["n_units"] == 182 for x in d["sources"].values())
U = d["union"]
best = [max(r[5][j] for r in rows) for j in range(4)]                      # best committed translation per column
best_src = [max(rows, key=lambda r: r[5][j])[0] for j in range(4)]
arrow = cols(U, "arrow"); maj = cols(U, "majority"); pool = cols(U, "pool")
# directions the text states
for j in range(4):
    assert arrow[j] > best[j], (j, arrow[j], best[j])          # ARROW beats every committed translation on every dataset
    assert arrow[j] <= pool[j] + 1e-12                          # and cannot exceed the unfiltered pool (an oracle ceiling)
    assert maj[j] < arrow[j]                                    # majority vote over the same samples does not close the gap
assert U["overall"]["arrow"]["size_median"] < U["overall"]["pool"]["size_median"] / 4
assert best_src[3].endswith("/nl2structnl") and best_src[3].startswith("gemini")
# ARROW on a single method's own samples retains (nearly) all of its distinct outputs: report the fact, not a claim
own_eq_pool = sum(1 for s, x in d["sources"].items() if x["overall"]["arrow"]["size_median"] == x["overall"]["pool"]["size_median"])
own_best = max(d["sources"].items(), key=lambda kv: kv[1]["overall"]["arrow"]["any"])
assert own_best[0].endswith("nl2structnl-reflect") and own_best[1]["overall"]["arrow"]["size_median"] == own_best[1]["overall"]["pool"]["size_median"]
ten = [x["overall"]["arrow"]["size_median"] for s_, x in d["sources"].items() if not s_.endswith("reflect")
       and x["overall"]["arrow"]["size_median"] == x["overall"]["pool"]["size_median"]]
assert ten and min(ten) >= 3 and max(ten) <= 5   # "three to five readings from ten samples"

# ---- the artifact's own metric (any of its ten samples plausible) must reproduce the ratios its paper reports
def ratio(backbone, g):
    art = d["sources"][f"{backbone}/nl2structnl"]["by_group"][g]["pool"]["any"]
    base = max(x["by_group"][g]["pool"]["any"] for s, x in d["sources"].items()
               if s.startswith(backbone) and not s.endswith("nl2structnl") and not s.endswith("nl2structnl-reflect"))
    return art / base
REPORTED = {("gemini-2.5-flash", "Ventilator"): 1.9, ("gemini-2.5-flash", "Robotics"): 1.57, ("gemini-2.5-flash", "LMCPS"): 1.25,
            ("gpt-4.1", "Ventilator"): 1.6, ("gpt-4.1", "Robotics"): 1.73, ("gpt-4.1", "LMCPS"): 1.08}   # ARTEMIS, Sec. 7.2
RATIOS = {k: ratio(*k) for k in REPORTED}
for k, v in REPORTED.items():   # within rounding and one requirement's checker disagreement (the archive lists 18 unaligned files)
    assert abs(RATIOS[k] - v) < 0.06, (k, RATIOS[k], v)

# ---- main-body rows: committed translation (first sample), in parentheses any of the ten samples
T = []
for i, (src, backbone, name, year, bib, av, rc) in enumerate(rows):
    x = d["sources"][src]; pv = cols(x, "pool")
    cells = []
    for j, v in enumerate(av):
        s = pct(v)
        s = f"\\textbf{{{s}}}" if src == best_src[j] else s
        cells.append(f"{s} ({pct(pv[j])})")
    T.append(f"{name} & {year} & {LLM[backbone]} & 1 & " + " & ".join(cells) + " \\\\\n")
T.append("\\midrule\n")
T.append("Self-consistency vote & -- & both & 1 & " + " & ".join(pct(v) for v in maj) + " \\\\\n")
T.append(f"All distinct samples & -- & both & {U['overall']['pool']['size_median']:.1f} & " + " & ".join(pct(v) for v in pool) + " \\\\\n")
T.append(f"\\textbf{{\\method{{}} \\textsc{{Score-Keep}}}} & 2026 & both & \\textbf{{{U['overall']['arrow']['size_median']:.1f}}} & " + " & ".join(f"\\textbf{{{pct(v)}}}" for v in arrow) + " \\\\\n")
open(os.path.join(GEN, "gen_artemis_methods_table.tex"), "w").write(HEAD + "".join(T))

# ---- appendix rows: per method, four arms (any / recall / size)
A = []
for src, backbone, name, year, bib, av, rc in rows:
    x = d["sources"][src]; o = x["overall"]
    A.append(f"{name} & {LLM[backbone]} & " + " & ".join(
        f"{pct(o[a]['any'])} & {pct(o[a]['recall'])}" for a in ("top1", "majority", "arrow")) +
        f" & {o['arrow']['size_median']:.0f} & {pct(o['pool']['any'])} & {o['pool']['size_median']:.0f} \\\\\n")
A.append("\\midrule\n")
o = U["overall"]
A.append("All nine methods, union of samples & both & " + " & ".join(
    f"{pct(o[a]['any'])} & {pct(o[a]['recall'])}" for a in ("top1", "majority", "arrow")) +
    f" & {o['arrow']['size_median']:.1f} & {pct(o['pool']['any'])} & {o['pool']['size_median']:.1f} \\\\\n")
open(os.path.join(GEN, "gen_artemis_methods_app.tex"), "w").write(HEAD + "".join(A))

# ---- macros
M = [mac("AmMethods", 9), mac("AmRows", len(rows)), mac("AmSamplesUnion", 190),
     mac("AmBestSingleAll", pct(best[3]) + "\\%"), mac("AmBestSingleName", METHODS[best_src[3].split('/')[1]][0]),
     mac("AmBestSingleBackbone", best_src[3].split("/")[0]),
     mac("AmBestSinglePoolAll", pct(d["sources"][best_src[3]]["overall"]["pool"]["any"]) + "\\%"),
     mac("AmArrowAll", pct(arrow[3]) + "\\%"), mac("AmArrowVent", pct(arrow[0]) + "\\%"), mac("AmArrowRobo", pct(arrow[1]) + "\\%"),
     mac("AmArrowLmcps", pct(arrow[2]) + "\\%"), mac("AmBestVent", pct(best[0]) + "\\%"), mac("AmBestRobo", pct(best[1]) + "\\%"),
     mac("AmBestLmcps", pct(best[2]) + "\\%"), mac("AmMajAll", pct(maj[3]) + "\\%"), mac("AmPoolAll", pct(pool[3]) + "\\%"),
     mac("AmArrowSize", f"{U['overall']['arrow']['size_median']:.1f}"), mac("AmPoolSize", f"{U['overall']['pool']['size_median']:.1f}"),
     mac("AmArrowRecallAll", pct(U['overall']['arrow']['recall']) + "\\%"), mac("AmTopRecallAll", pct(U['overall']['top1']['recall']) + "\\%"),
     mac("AmBestRecallAll", pct(max(r[6][3] for r in rows)) + "\\%"),
     mac("AmOwnEqPool", own_eq_pool), mac("AmOwnBestAny", pct(own_best[1]['overall']['arrow']['any']) + "\\%"),
     mac("AmOwnBestName", METHODS[own_best[0].split('/')[1]][0]), mac("AmOwnBestSize", f"{own_best[1]['overall']['arrow']['size_median']:.0f}"),
     mac("AmWorstSingleAll", pct(min(r[5][3] for r in rows)) + "\\%"),
     mac("AmNVent", U["by_group"]["Ventilator"]["n"]), mac("AmNRobo", U["by_group"]["Robotics"]["n"]), mac("AmNLmcps", U["by_group"]["LMCPS"]["n"]),
     mac("AmGainAllPts", f"{100*(arrow[3]-best[3]):.1f}"),
     mac("ArSelfConsMaxGain", f"{100*max(abs(x['overall']['majority']['any']-x['overall']['top1']['any']) for x in d['sources'].values()):.1f}"),
     mac("AmRatiosOurs", "/".join(f"{RATIOS[(b, g)]:.2f}" for b in ("gemini-2.5-flash", "gpt-4.1") for g in G)),
     mac("AmRatiosReported", "/".join(f"{REPORTED[(b, g)]:.2f}" for b in ("gemini-2.5-flash", "gpt-4.1") for g in G)),
     mac("AmRatioMaxDiff", f"{max(abs(RATIOS[k]-REPORTED[k]) for k in REPORTED):.2f}")]
open(os.path.join(GEN, "gen_artemis_methods.tex"), "w").write(HEAD + "\n".join(M) + "\n")
print("best committed per column:", [(pct(b), s) for b, s in zip(best, best_src)])
print("ARROW union:", [pct(v) for v in arrow], "size", U["overall"]["arrow"]["size_median"], "| pool", [pct(v) for v in pool], U["overall"]["pool"]["size_median"], "| majority", [pct(v) for v in maj])
print("own-pool ARROW == pool size for", own_eq_pool, "of 15; best own-pool ARROW:", own_best[0], pct(own_best[1]["overall"]["arrow"]["any"]))
