#!/usr/bin/env python3
"""V41 (k_scaling.json) and V42 (decision_equivalence_readout.json) macros for
arrow.tex.  Asserts pin the directions the body states."""
import json
import os
ROOT=os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
k=json.load(open(f"{ROOT}/results/e2e/k_scaling.json")); a=k["aggregate"]; Ks=k["Ks"]; big=str(max(Ks))
de=json.load(open(f"{ROOT}/results/e2e/decision_equivalence_readout.json"))
lp2,lpb=1e3*a["2"]["t_lp_med"],1e3*a[big]["t_lp_med"]; fq2,fqb=1e3*a["2"]["t_fqi_med"],1e3*a[big]["t_fqi_med"]
assert lpb/lp2<2 and fqb/fq2<2, "body: compute flat in K"
assert k["lp_identity"]["max_abs_return_diff"]<1e-9, "body: identical LP policies"
assert all(a[str(K)]["fqi_converged"]==1.0 for K in Ks)
assert de["miss_labels"]=={"GEN_MISS":de["n_miss"]} and de["n_faithful"]==173 and de["n_hit"]==111, "body: every faithful miss is a metric miss"
rows=[]
for K in Ks:
    r=a[str(K)]; rows.append(f"{K} & {1e3*r['t_lp_med']:.1f} & {1e3*r['t_fqi_med']:.1f} & {r['fqi_iters_med']:.0f} & {100*r['lp_return']:.2f} & {100*r['fqi_return']:.2f} \\\\")
m={"KcBig":big,"KcPairs":str(k["lp_identity"]["n_pairs"]),"KcLpMsTwo":f"{lp2:.1f}","KcLpMsBig":f"{lpb:.1f}","KcFqiMsTwo":f"{fq2:.1f}","KcFqiMsBig":f"{fqb:.1f}",
   "KcInst":str(len({r['uid'] for r in k['rows']})),"KcSeeds":str(k["seeds"]),
   "DeMissN":str(de["n_miss"]),"DeFaithN":str(de["n_faithful"]),"DeHitN":str(de["n_hit"]),"DeRecall":f"{100*de['exact_recall']:.1f}\\%"}
out=["% AUTO-GENERATED by paper/final/make_gen_v41.py -- do not edit"]+[f"\\newcommand{{\\{n}}}{{{v}}}" for n,v in m.items()]
open(f"{ROOT}/paper/generated/gen_v41.tex","w").write("\n".join(out)+"\n")
open(f"{ROOT}/paper/generated/gen_v41_table.tex","w").write("% AUTO-GENERATED by paper/final/make_gen_v41.py -- do not edit\n"+"\n".join(rows)+"\n")
print("\n".join(out)); print("\n".join(rows))
