"""Macros for the ARTEMIS external-validation study (REGISTRATION_V17).  Reads
results/e2e/artemis_external.json only; asserts the branch-rule outcomes the text states.

Run: python3 scripts/paper/make_gen_artemis.py
Writes generated/gen_artemis.tex
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEN = os.path.join(ROOT, "paper", "generated")
HEAD = "% AUTO-GENERATED by scripts/paper/make_gen_artemis.py -- do not edit\n"
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "results/e2e", "artemis_external.json")


def fmt_size(x): return f"{x:.0f}" if abs(x-round(x))<1e-9 else f"{x:.1f}"   # medians of an even count end in .5
def pct(x, nd=1):
    return "--" if x is None else f"{100 * x:.{nd}f}\\%"


def mac(name, val):
    return f"\\newcommand{{\\{name}}}{{{val}}}"


d = json.load(open(SRC))
M = [mac("ArUnits", d["n_units"]), mac("ArCommit", d["artifact_commit"][:10]),
     mac("ArCheckerAgree", pct(d["checker_validation"]["agreement"], 2)),
     mac("ArCheckerN", f"{d['checker_validation']['n_trials_compared']:,}".replace(",", "{,}")),
     mac("ArCheckerDisagree", d["checker_validation"]["n_trials_compared"] - d["checker_validation"]["n_agree"]),
     mac("ArPlausMax", max(int(k) for k in d["n_plausible_hist"])),
     mac("ArUndecided", sum(d["undecided_total"].values()))]
groups = {"Ventilator": 0, "Robotics": 0, "LMCPS": 0}
for r in d["pools"]["P1"]["per_unit"]:
    groups[r["group"]] += 1
M += [mac("ArVent", groups["Ventilator"]), mac("ArRobo", groups["Robotics"]), mac("ArLmcps", groups["LMCPS"])]
assert sum(groups.values()) == d["n_units"]

for w, wl in (("P1", "flagship generator, 50 samples"), ("P2", "union of all archived generators, 190 samples")):
    p = d["pools"][w]
    o = p["overall"]
    tag = "One" if w == "P1" else "Two"
    br = p["branch_rules"]
    M += [mac(f"Ar{tag}Proposed", p["n_proposed"]), mac(f"Ar{tag}DeltaGen", pct(p["delta_gen_hat"])),
          mac(f"Ar{tag}Cov", pct(br["rule1_coverage_on_proposed"])), mac(f"Ar{tag}Eff", pct(br["rule2_median_efficiency"], 0)),
          mac(f"Ar{tag}Uninformative", "yes" if br["rule2_score_uninformative"] else "no"),
          mac(f"Ar{tag}CalFails", "yes" if br["rule1_calibration_fails"] else "no")]
    for arm, al in (("top1", "Top"), ("majority", "Maj"), ("arrow", "Arrow"), ("arrow_min", "ArrowMin"), ("pool", "Pool")):
        s = o[arm]
        M += [mac(f"Ar{tag}{al}Any", pct(s["any"])), mac(f"Ar{tag}{al}Recall", pct(s["recall"])), mac(f"Ar{tag}{al}All", pct(s["all"])),
              mac(f"Ar{tag}{al}Size", fmt_size(s['size_median'])), mac(f"Ar{tag}{al}Eff", pct(s["efficiency_median"], 0))]
    for b, v in p["by_bin"].items():
        key = {"1": "One", "2-5": "Few", "6-10": "Mid", ">10": "Many"}[b]
        if v["n"]:
            M += [mac(f"Ar{tag}Bin{key}N", v["n"]), mac(f"Ar{tag}Bin{key}Top", pct(v["top1"]["recall"])),
                  mac(f"Ar{tag}Bin{key}Maj", pct(v["majority"]["recall"])), mac(f"Ar{tag}Bin{key}Arrow", pct(v["arrow"]["recall"])),
                  mac(f"Ar{tag}Bin{key}Pool", pct(v["pool"]["recall"])), mac(f"Ar{tag}Bin{key}Size", f"{v['arrow']['size_median']:.0f}")]
    for g, v in p["by_group"].items():
        M += [mac(f"Ar{tag}Grp{g}Arrow", pct(v["arrow"]["recall"])), mac(f"Ar{tag}Grp{g}Maj", pct(v["majority"]["recall"])),
              mac(f"Ar{tag}Grp{g}Any", pct(v["arrow"]["any"]))]
with open(os.path.join(GEN, "gen_artemis.tex"), "w") as fh:
    fh.write(HEAD + "\n".join(M) + "\n")
print(f"wrote gen_artemis.tex ({len(M)} macros) from {os.path.basename(SRC)}")
