#!/usr/bin/env python3
"""Emit generated/gen_v52.tex (macros, prefix \Vc...) and gen_v52_table.tex from results/e2e/scope_agent_check.json:
the checked deployment route (empirical-Bernstein CHECK) on every learned policy of the agent-service experiment
(REGISTRATION_V52).  Directions the manuscript states are asserted before writing."""
import json, os
import numpy as np
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(ROOT, "paper")); GEN = os.path.join(PAPER, "generated")
d = json.load(open(os.path.join(ROOT, "results/e2e", "scope_agent_check.json"))); rows = d["rows"]
H = "% AUTO-GENERATED by paper/final/make_gen_v52.py -- do not edit\n"
LNAME = {"fqi": "BCQ-FQI-Lagrangian", "cpq": "CPQ", "pid": "PID-Lagrangian", "cql": "CQL-Lagrangian (neural)"}; LKEY = {"fqi": "Fqi", "cpq": "Cpq", "pid": "Pid", "cql": "Cql"}
def pct(x, k=1): return f"{100*x:.{k}f}\\%"
def arm_of(r): return "arrow" if r["is_arrow"] else ("surrogate" if r["arm"] == "surrogate" else "wrong")
M = []
def mac(n, v): M.append(f"\\newcommand{{\\{n}}}{{{v}}}")
mac("VcNEv", f"{d['n_ev']:,}".replace(",", "{,}")); mac("VcDeltaEv", f"{d['delta_ev']:g}"); mac("VcPolicies", f"{len(rows):,}".replace(",", "{,}"))
unsafe_dep = sum(1 for r in rows if r["ship"] and not r["safe"]); assert unsafe_dep == 0; mac("VcUnsafeDeployed", unsafe_dep)
wrong_unsafe = [r for r in rows if arm_of(r) == "wrong" and not r["safe"]]; assert all(not r["ship"] for r in wrong_unsafe)
mac("VcWrongUnsafe", f"{len(wrong_unsafe):,}".replace(",", "{,}")); mac("VcWrongUnsafeRejected", sum(1 for r in wrong_unsafe if not r["ship"]))
T = []; pass_arrow = []; dep_arrow = []
for l in ("fqi", "cpq", "pid", "cql"):
    for n in sorted({r["n"] for r in rows if r["learner"] == l}):
        for arm in ("arrow", "surrogate", "wrong"):
            sel = [r for r in rows if r["learner"] == l and r["n"] == n and arm_of(r) == arm]; dep = [r for r in sel if r["ship"]]
            ret = float(np.mean([r["ret_frac"] for r in sel])); ps = float(np.mean([r["ship"] for r in sel]))
            dret = float(np.mean([r["ret_frac"] for r in dep])) if dep else None; srej = sum(1 for r in sel if r["safe"] and not r["ship"])
            unsafe = sum(1 for r in sel if not r["safe"])
            label = {"arrow": "\\method{} reading", "surrogate": "single-cost surrogate", "wrong": "wrong reading"}[arm]
            T.append(f"{LNAME[l] if arm == 'arrow' else ''} & {n:,} & {label} & {pct(ret)} & {unsafe} & {pct(ps,0)} & {sum(1 for r in dep if not r['safe'])} & {pct(dret) if dret is not None else '--'} & {srej} \\\\".replace(",", "{,}").replace("{,} ", ", "))
            assert len(sel) == (180 if arm == "wrong" else 90)
            if n == 20000:
                key = f"Vc{LKEY[l]}" + {"arrow": "Arrow", "surrogate": "Surr", "wrong": "Wrong"}[arm]
                mac(key + "Pass", pct(ps, 0)); mac(key + "Ret", pct(ret)); mac(key + "Unsafe", unsafe); mac(key + "SafeRejected", srej)
                if dret is not None: mac(key + "DepRet", pct(dret))
                if arm == "arrow": pass_arrow.append(ps); dep_arrow.append(dret)
        T.append("\\addlinespace[1pt]")
open(os.path.join(GEN, "gen_v52_table.tex"), "w").write(H + "\n".join(T[:-1]) + "\n")
mac("VcArmPolicies", len([r for r in rows if r["learner"] == "fqi" and r["n"] == 20000 and arm_of(r) == "arrow"]))
mac("VcArrowPassLo", pct(min(pass_arrow), 0)); mac("VcArrowPassHi", pct(max(pass_arrow), 0)); mac("VcArrowDepRetLo", pct(min(dep_arrow))); mac("VcArrowDepRetHi", pct(max(dep_arrow)))
cql_arrow = [r for r in rows if r["learner"] == "cql" and arm_of(r) == "arrow"]
assert sum(1 for r in cql_arrow if not r["safe"]) > 0 and all(not r["ship"] for r in cql_arrow if not r["safe"])   # the unsafe CQL runs are all rejected
mac("VcCqlArrowUnsafeRuns", sum(1 for r in cql_arrow if not r["safe"]))
assert all(float(np.mean([r["ship"] for r in rows if r["learner"] == l and r["n"] == 20000 and arm_of(r) == "arrow"])) == 1.0 for l in ("fqi", "cpq", "pid"))
# ---- compact table: ARROW and surrogate arms at n = 20,000 per learner, plus one stress-test row for every wrong-reading policy
C = []
for l in ("fqi", "cpq", "pid", "cql"):
    for arm in ("arrow", "surrogate"):
        sel = [r for r in rows if r["learner"] == l and r["n"] == 20000 and arm_of(r) == arm]; dep = [r for r in sel if r["ship"]]
        ret = float(np.mean([r["ret_frac"] for r in sel])); ps = float(np.mean([r["ship"] for r in sel])); dret = float(np.mean([r["ret_frac"] for r in dep]))
        label = "\\method{} reading" if arm == "arrow" else "single-cost surrogate"
        C.append(f"{LNAME[l] if arm == 'arrow' else ''} & {label} & {pct(ret)} & {sum(1 for r in sel if not r['safe'])} & {pct(ps,0)} & {sum(1 for r in dep if not r['safe'])} & {pct(dret)} \\\\")
wrong = [r for r in rows if arm_of(r) == "wrong"]; wdep = [r for r in wrong if r["ship"]]
C.append("\\midrule")
C.append(f"wrong readings, all learners & {len(wrong):,} policies & {pct(float(np.mean([r['ret_frac'] for r in wrong])))} & {sum(1 for r in wrong if not r['safe'])} & {pct(float(np.mean([r['ship'] for r in wrong])),0)} & {sum(1 for r in wdep if not r['safe'])} & {pct(float(np.mean([r['ret_frac'] for r in wdep])))} \\\\".replace(",", "{,}").replace("{,} policies", " policies"))
assert sum(1 for r in wdep if not r["safe"]) == 0 and len(wrong) == 1260
mac("VcWrongPolicies", f"{len(wrong):,}".replace(",", "{,}")); mac("VcWrongPass", pct(float(np.mean([r["ship"] for r in wrong])), 0))
open(os.path.join(GEN, "gen_v52_table_compact.tex"), "w").write(H + "\n".join(C) + "\n")
open(os.path.join(GEN, "gen_v52.tex"), "w").write(H + "\n".join(M) + "\n")
print("macros", len(M)); print(open(os.path.join(GEN, "gen_v52_table.tex")).read()[:600])
