"""Macros for the revision studies the paper still reports: exact-decision runtime and state-space
growth (Rt...), the simple-alternative baselines (Bl...) and the cross-organization third corpus
(Tc...), plus the compact third-corpus table.  Reads only archived run files; every direction the
body states is asserted here, so a rerun that flips one refuses to emit and the sentence has to
change.

Run: python3 scripts/paper/make_gen_revision.py
Writes paper/generated/gen_revision.tex and gen_third_corpus_compact.tex.
"""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEN = os.path.join(ROOT, "paper", "generated")
HEAD = "% AUTO-GENERATED by scripts/paper/make_gen_revision.py -- do not edit\n"


def load(*p):
    with open(os.path.join(ROOT, *p)) as fh:
        return json.load(fh)


def write(name, text):
    with open(os.path.join(GEN, name), "w") as fh:
        fh.write(HEAD + text)


def pct(x, nd=1):
    return f"{100 * x:.{nd}f}\\%"


def num(x, nd=0):
    return f"{x:,.{nd}f}".replace(",", "{,}")


def mac(name, val):
    return f"\\newcommand{{\\{name}}}{{{val}}}"


M = []


# ---------------------------------------------------------------- W4 runtime
rt = load("results/e2e", "decide_runtime.json")["parts"]
hw = rt["exact_nonnested"]["hardware"]
M += [mac("RtCpu", hw["cpu"]), mac("RtCores", hw["n_cores"]), mac("RtRam", f"{hw['ram_bytes'] / 2**30:.0f}"),
      mac("RtSolver", "HiGHS via SciPy " + hw["scipy"])]
order = [("exact_nonnested", "exact non-nested suite (Tab.~\\ref{tab:exact})", "17 inst.\\ $\\times$ 5 budgets"),
         ("policy_sufficiency", "face certificates (Tab.~\\ref{tab:e2})", "28 inst.\\ $\\times$ 5 budgets"),
         ("surrogate_price", "single-cost surrogate price", "28 inst.\\ $\\times$ 5 budgets"),
         ("policy_class_budget", "class $\\times$ budget audit, both families", "132 pools $\\times$ 5 budgets"),
         ("class_ladder", "capability ladder", f"{rt['class_ladder']['n_rows']:,} rule/class/budget rows".replace(",", "{,}")),
         ("face_ladder", "face-level ladder + admission face pass", "132 pools"),
         ("e16", "admission exact screen (enumeration)", "44 pools $\\times$ 4 budgets")]
tot_lp = tot_milp = 0
for key, label, objs in order:
    p = rt[key]
    tot_lp += p.get("n_value_or_face_lps", 0); tot_milp += p.get("n_milps", 0)
    assert p["reproduces_archive"], key
pcbp = rt["policy_class_budget"]
M += [mac("RtPoolReadings", num(pcbp["n_candidate_readings"])), mac("RtPoolClasses", num(pcbp["n_behaviour_classes"])),
      mac("RtPoolWidthMax", pcbp["max_antichain_width"])]
M += [mac("RtTotalLps", num(tot_lp)), mac("RtTotalMilps", num(tot_milp)),
      mac("RtTotalWall", f"{sum(rt[k]['wall_seconds'] for k, _, _ in order):.0f}"),
      mac("RtPeakMb", f"{max(rt[k]['peak_rss_mb'] for k, _, _ in order):.0f}"),
      mac("RtPsFaceLps", num(rt["policy_sufficiency"]["n_face_lps_by_construction"])),
      mac("RtPsSeconds", f"{rt['policy_sufficiency']['wall_seconds']:.1f}"),
      mac("RtPsValueLps", num(rt["policy_sufficiency"]["n_value_lps_by_construction"])),
      mac("RtPsTieLps", num(rt["policy_sufficiency"]["n_tiebreak_lps_by_construction"])),
      mac("RtLadderRows", num(rt["class_ladder"]["n_rows"]))]
sc = rt["scale"]
big = sc["rows"][-1]
M += [mac("RtScaleKmed", num(sc["antichain_median_e2e"])), mac("RtScaleStates", big["n_states"]),
      mac("RtScaleBigValueS", f"{big['seconds_value_lp']:.1f}"), mac("RtScaleBigSinglesS", f"{big['seconds_single_lps']:.1f}"),
      mac("RtScaleBigFaceLps", num(big["face_lps_run"])), mac("RtScaleBigFaceS", f"{big['seconds_face_lps']:.0f}"),
      mac("RtScaleBigSuff", big["n_value_sufficient"]), mac("RtScaleGeometry", sc["geometry"])]
gr = sc["compiled_state_space_growth"]
M += [mac("RtGrowthKfour", num(next(g["n_states"] for g in gr if g["K"] == 4))),
      mac("RtGrowthKeight", num(next(g["n_states"] for g in gr if g["K"] == 8))), mac("RtGrowthCap", gr[0]["cap"])]


# ---------------------------------------------------------------- W8 baselines
bl = load("results/e2e", "baseline_table.json")
c, a = bl["compiled"]["summary"], bl["admission"]["summary"]
assert c["top1_unsafe"] > 0 and a["top1_unsafe"] > 0
assert c["clarify_gain_median"] > c["surrogate_loss_max"]
M += [mac("BlN", c["n"]), mac("BlTopUnsafe", c["top1_unsafe"]), mac("BlTopGold", c["top1_is_gold"]),
      mac("BlGoldInMax", c["gold_in_maximal"]), mac("BlFaceCert", c["face_certified"]),
      mac("BlTopRatioMed", f"{c['top1_ratio_median']:.2f}"), mac("BlTopRatioMax", f"{c['top1_ratio_max']:.2f}"),
      mac("BlTopTies", c["top1_score_ties"]), mac("BlTopAltUnsafe", c["top1_alt_unsafe"]),
      mac("BlTopUnsafeUntied", c["top1_unsafe_untied"]), mac("BlNUntied", c["n_untied"]),
      mac("BlSurrMed", pct(c["surrogate_loss_median"])), mac("BlSurrMin", pct(c["surrogate_loss_min"])), mac("BlSurrMax", pct(c["surrogate_loss_max"])),
      mac("BlClarMed", pct(c["clarify_gain_median"])), mac("BlClarMin", pct(c["clarify_gain_min"])), mac("BlClarMax", pct(c["clarify_gain_max"])),
      mac("BlClarTen", pct(c["clarify_when_gain_exceeds"]["0.1"], 0)), mac("BlClarTwenty", pct(c["clarify_when_gain_exceeds"]["0.2"], 0)),
      mac("BlAdmN", a["n"]), mac("BlAdmTopUnsafe", a["top1_unsafe"]), mac("BlAdmTopGold", a["top1_is_gold"]), mac("BlAdmStrict", a["strictest_defined"]),
      mac("BlAdmSurrMed", pct(a["surrogate_loss_median"])), mac("BlAdmSurrMax", pct(a["surrogate_loss_max"])),
      mac("BlAdmClarMed", pct(a["clarify_gain_median"])), mac("BlAdmClarMax", pct(a["clarify_gain_max"])),
      mac("BlAdmClarPos", a["n"] - a["clarify_gain_zero"]),
      mac("BlAdmClarTen", pct(a["clarify_when_gain_exceeds"]["0.1"], 0)), mac("BlAdmClarTwenty", pct(a["clarify_when_gain_exceeds"]["0.2"], 0)),
      mac("BlNestedN", bl["monitoring_nested_clear"]["n"])]
sc_ = load("results/e2e", "surrogate_price.json")["aggregate_at_operating"]
assert abs(c["surrogate_loss_median"] - sc_["rel_gap_med"]) < 1e-9, "baseline-table surrogate loss disagrees with surrogate_price.json"

# ---------------------------------------------------------------- P10 third corpus
tc = load("results/e2e", "third_corpus.json")
tp = tc["pooled"]
assert tc["n_pool_errors"] == 0
assert tp["face_clear_0.005"] == 0, "the tight-budget face separation no longer replicates; text must change"
assert tp["value_clear_0.05"] == tp["face_clear_0.05"], "value and face separate at the operating budget on the third corpus; text must change"
M += [mac("TcRepos", len(tc["repos"])), mac("TcPools", num(tp["n_pools"])), mac("TcNondom", pct(tp["non_dominance_rate"])),
      mac("TcEligible", tp["compiled_eligible"]), mac("TcNested", tp["nested_clear"]), mac("TcUnanalyzed", tp["unanalyzed"]),
      mac("TcAnalyzable", tp["analyzable"]), mac("TcFiresOp", tp["fires_0.05"]), mac("TcFiresTight", tp["fires_0.005"]),
      mac("TcFiresOpPct", pct(tp["fires_0.05"] / tp["analyzable"])),
      mac("TcValueClearTight", tp["value_clear_0.005"]), mac("TcFaceClearTight", tp["face_clear_0.005"]),
      mac("TcValueClearOp", tp["value_clear_0.05"]), mac("TcFaceClearOp", tp["face_clear_0.05"]),
      mac("TcFreeFires", tp["free_fires_0.05"]), mac("TcFreeFiresPct", pct(tp["free_fires_0.05"] / tp["n_pools"], 0)),
      mac("TcLadKOne", tp["ladder"]["1"]["some"]), mac("TcLadKTwoSome", tp["ladder"]["2"]["some"]), mac("TcLadKTwoN", tp["ladder"]["2"]["n"]),
      mac("TcLadKTwoAll", tp["ladder"]["2"]["every"]), mac("TcFrontOne", tp["frontier"].get("1", 0)), mac("TcFrontTwo", tp["frontier"].get("2", 0)),
      mac("TcFrontNever", tp["frontier"].get("None", 0)), mac("TcFaithful", tp["faithful"]), mac("TcFaithfulPct", pct(tp["faithful"] / tp["n_pools"], 0)),
      mac("TcAnalyzableFaith", tp["analyzable_faithful"]), mac("TcFiresFaith", tp["fires_0.05_faithful"])]
per = tc["per_repo"]
top = max(per, key=lambda r: per[r]["fires_0.05"])
M += [mac("TcTopRepo", top), mac("TcTopRepoFires", per[top]["fires_0.05"]), mac("TcTopRepoEligible", per[top]["compiled_eligible"]),
      mac("TcTopRepoAnalyzable", per[top]["analyzable"]),
      mac("TcOtherFires", tp["fires_0.05"] - per[top]["fires_0.05"]), mac("TcOtherAnalyzable", tp["analyzable"] - per[top]["analyzable"])]

# ---------------------------------------------------------------- third corpus, body columns
_tc = load("results/e2e", "third_corpus.json")
_names = [("mimir", "Mimir"), ("loki", "Loki"), ("cluster-monitoring-operator", "OpenShift monitoring"),
          ("victoriametrics", "VictoriaMetrics"), ("rook", "Rook"), ("ceph", "Ceph"),
          ("thanos", "Thanos"), ("tidb", "TiDB")]
_tot = dict(pools=0, elig=0, f05=0, f005=0, vc=0, fc=0, free=0)
for key, label in _names:
    r = _tc["per_repo"][key]
    vc, fc = r["value_clear_0.005"], r["face_clear_0.005"]
    for k, v in (("pools", r["n_pools"]), ("elig", r["compiled_eligible"]), ("f05", r["fires_0.05"]),
                 ("f005", r["fires_0.005"]), ("vc", vc), ("fc", fc), ("free", r["free_fires_0.05"])):
        _tot[k] += v
_p = _tc["pooled"]
assert _tot["pools"] == _p["n_pools"] == 465 and _tot["elig"] == _p["compiled_eligible"] == 100
assert _tot["fc"] == 0, "a reading now passes the policy test at the tight budget on the third corpus; Section 5.2 must change"
assert _tot["vc"] == _p["value_clear_0.005"] and _tot["f005"] == _p["fires_0.005"]
# compact four-column presentation (Appendix D.1): pools, value-screen clears and face clears at d=0.005
_compact = [("mimir", "Grafana Mimir"), ("loki", "Grafana Loki"), ("cluster-monitoring-operator", "OpenShift cluster-monitoring-operator"),
            ("victoriametrics", "VictoriaMetrics"), ("rook", "Rook"), ("ceph", "Ceph"), ("thanos", "Thanos"), ("tidb", "TiDB")]
_crows = [f"{label} & {_tc['per_repo'][key]['n_pools']} & {_tc['per_repo'][key]['value_clear_0.005']} & {_tc['per_repo'][key]['face_clear_0.005']} \\\\\n"
          for key, label in _compact]
assert sum(_tc['per_repo'][k]['value_clear_0.005'] for k, _ in _compact) == _tot["vc"] == 57 and _tot["fc"] == 0
_crows.append("\\midrule\n")
_crows.append(f"All eight & {_tot['pools']} & {_tot['vc']} & {_tot['fc']} \\\\\n")
write("gen_third_corpus_compact.tex", "".join(_crows))
M += [mac("TcMainPools", _tot["pools"]), mac("TcMainExact", _tot["elig"]), mac("TcMainValue", _tot["vc"]),
      mac("TcMainPolicy", _tot["fc"]), mac("TcMainFiresOp", _tot["f05"]), mac("TcMainFiresTight", _tot["f005"]),
      mac("TcMainFree", _tot["free"]), mac("TcMainOrgs", len(_names))]

write("gen_revision.tex", "\n".join(M) + "\n")
print(f"wrote gen_revision.tex ({len(M)} macros) + gen_third_corpus_compact.tex; all asserts passed")
