"""Emit generated/gen_e5b.tex: the body's Table 5(B) rows.

The body table and the appendix table report the same four constrained-learning
mechanisms, so they must not be able to disagree.  This reshapes the
archive-derived gen_agnostic.tex fragment into the body's four-column form
(learner, single-reading worst retained cost, ARROW's, an abbreviated mechanism)
rather than restating its numbers, and asserts the direction the body claims: ARROW's worst
retained cost is lower on every mechanism.

Run: python3 scripts/paper/make_gen_e5b.py   (after make_corset_tables.py)
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "paper"))
GEN = os.path.join(PAPER, "generated")

src = open(os.path.join(GEN, "gen_agnostic.tex")).read()
rows = []
for line in src.splitlines():
    line = line.strip()
    if not line or line.startswith("%"):
        continue
    c = [x.strip() for x in line.rstrip("\\").strip().split("&")]
    assert len(c) == 8, c
    learner, mech, _sret, sworst, _rret, rworst = c[0], c[1], c[2], c[3], c[4], c[5]
    num = lambda x: float(x.replace("$", ""))
    assert num(rworst) < num(sworst), f"{learner}: ARROW is not lower"
    short = {"Lagrangian dual ascent": "Lagrangian",
             "PID multiplier control": "PID control",
             "cost critic + action restriction": "cost critic"}
    assert mech in short, f"unknown mechanism {mech!r}"
    rows.append(f"{learner} & {sworst} & {rworst} & {short[mech]} \\\\\n")
assert len(rows) == 4, len(rows)

path = os.path.join(GEN, "gen_e5b.tex")
open(path, "w").write(
    "% AUTO-GENERATED by paper/final/make_gen_e5b.py -- do not edit\n" + "".join(rows))
print("wrote", path)
print("".join(rows))
