#!/usr/bin/env python3
"""Emit generated/gen_v28.tex from results/e2e/safe_face_select.json (V28).

Every numeral the safe-face selector subsection quotes expands from here.
Asserts agreement with the V13 archive wherever the two measure the same
quantity, so a disagreement is a build failure rather than a silent drift.
"""
import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SEL = os.path.join(ROOT, "results/e2e", "safe_face_select.json")
V13 = os.path.join(ROOT, "results/e2e", "policy_sufficiency.json")
OUT = os.path.join(ROOT, "paper", "generated", "gen_v28.tex")

TIGHT, MID = "0.005", "0.02"


def pct(x):
    return f"{100 * x:.0f}\\%"


def main():
    sel = json.load(open(SEL, encoding="utf8"))
    v13 = json.load(open(V13, encoding="utf8"))
    by = sel["by_budget"]

    # --- cross-check the regimes against V13 ---------------------------
    for b in ("0.005", "0.01", "0.02", "0.05", "0.1"):
        rows13 = [r for r in v13["rows"] if abs(r["budget"] - float(b)) < 1e-12]
        v_clear = sum(r["value_sufficient_exists"] for r in rows13)
        p_clear = sum(r["policy_sufficient_exists"] for r in rows13)
        reg = by[b]["regimes"]
        assert reg["irrelevant"] == p_clear, (b, reg, p_clear)
        assert reg["irrelevant"] + reg["optimizer_resolvable"] == v_clear, \
            (b, reg, v_clear)
    n_inst = by[TIGHT]["n"]

    t, m = by[TIGHT], by[MID]
    # slack agreement between safe-face and the best full-set optimum
    diffs = []
    for r in sel["rows"]:
        s = r["selectors"]
        if r["regime"] != "optimizer_resolvable" or not s:
            continue
        a, b_ = s["safeface"]["C_max"], s["fullset_best"]["C_max"]
        if a is not None and b_ is not None:
            diffs.append(abs(a - b_))
    worst = max(diffs)
    exp = int(np.floor(np.log10(worst))) if worst > 0 else -18
    assert worst < 1e-12, ("safe-face and full-set optima differ materially",
                           worst)
    # the adversarial point, as a multiple of the budget
    ov = [r["selectors"]["tie_worst"]["C_max"] / r["budget"]
          for r in sel["rows"]
          if r["regime"] == "optimizer_resolvable" and r["selectors"]
          and r["selectors"]["tie_worst"]["C_max"] is not None]
    assert abs(np.median(ov) - 1.51) < 0.02, np.median(ov)

    # every middle-regime run must be safe and reward-preserving
    mid_rows = [r for r in sel["rows"]
                if r["regime"] == "optimizer_resolvable" and r["selectors"]]
    assert all(r["selectors"]["safeface"]["safe"] for r in mid_rows)
    assert all(r["selectors"]["safeface"]["reward_kept"] for r in mid_rows)

    lines = [
        "% AUTO-GENERATED by paper/final/make_gen_v28.py -- do not edit",
        f"\\newcommand{{\\SfInst}}{{{n_inst}}}",
        f"\\newcommand{{\\SfMidTight}}{{{t['n_middle']}}}",
        f"\\newcommand{{\\SfMidMid}}{{{m['n_middle']}}}",
        f"\\newcommand{{\\SfSfSafeTight}}{{{t['safeface_safe']}}}",
        f"\\newcommand{{\\SfSfSafeMid}}{{{m['safeface_safe']}}}",
        f"\\newcommand{{\\SfSingleSafeTight}}{{{t['single_safe']}}}",
        f"\\newcommand{{\\SfSingleSafeMid}}{{{m['single_safe']}}}",
        f"\\newcommand{{\\SfTieN}}{{{100}}}",
        f"\\newcommand{{\\SfTieMedTight}}{{{pct(t['tie_random_safe_frac_med'])}}}",
        f"\\newcommand{{\\SfTieLoTight}}{{{pct(t['tie_random_safe_frac_min'])}}}",
        f"\\newcommand{{\\SfTieMedMid}}{{{pct(m['tie_random_safe_frac_med'])}}}",
        f"\\newcommand{{\\SfTieLoMid}}{{{pct(m['tie_random_safe_frac_min'])}}}",
        f"\\newcommand{{\\SfOvershoot}}{{{np.median(ov):.2f}$\\times$}}",
        f"\\newcommand{{\\SfSlackAgree}}{{$10^{{{exp}}}$}}",
    ]
    for key, tag in (("0.005", "A"), ("0.01", "B"), ("0.02", "C"),
                     ("0.05", "D"), ("0.1", "E")):
        reg = by[key]["regimes"]
        lines += [
            f"\\newcommand{{\\SfReg{tag}Irr}}{{{reg['irrelevant']}}}",
            f"\\newcommand{{\\SfReg{tag}Mid}}{{{reg['optimizer_resolvable']}}}",
            f"\\newcommand{{\\SfReg{tag}Red}}{{{reg['irreducible']}}}",
        ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines) - 1} macros)")
    print("\n".join(lines[1:]))


if __name__ == "__main__":
    main()
