#!/usr/bin/env python3
"""Emit generated/gen_v51.tex (macros, prefix \Vn...) from results/e2e/scope_agent_native.json:
native multi-constraint learners (K separate constraints) versus the ARROW-certified singleton (REGISTRATION_V51).
Every direction the manuscript states is asserted before writing."""
import json, os, statistics as st
from math import comb
import numpy as np
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(ROOT, "paper")); GEN = os.path.join(PAPER, "generated")
d = json.load(open(os.path.join(ROOT, "results/e2e", "scope_agent_native.json")))
rows = d["rows"]; H = "% AUTO-GENERATED by scripts/paper/make_gen_v51.py -- do not edit\n"
LNAME = {"mfqi": "vector Lagrangian FQI", "mpid": "vector PID-Lagrangian FQI", "mcpq": "vector CPQ", "lp": "occupancy LP on $\\hat P$"}
LKEY = {"mfqi": "Fqi", "mpid": "Pid", "mcpq": "Cpq", "lp": "Lp"}
def pct(x, k=1): return f"{100*x:.{k}f}\\%"
def pts(x, k=1): return f"{100*x:+.{k}f}"
def sign_p(pos, neg):
    n = pos + neg; return sum(comb(n, k) for k in range(pos, n + 1)) / 2 ** n
M = []
def mac(n, v): M.append(f"\\newcommand{{\\{n}}}{{{v}}}")
# exact tie (Theorem 4.1)
tie = max(t["gap"] for t in d["exact_ties"]); assert tie < 1e-9
mac("VnTieMax", f"{tie:.0e}".replace("e-", "\\times10^{-") + "}"); mac("VnTieInst", len(d["exact_ties"]))
mac("VnSeeds", len(d["eval_seeds"])); mac("VnCalSeeds", len(d["cal_seeds"])); mac("VnNGrid", ", ".join(f"{n:,}".replace(",", "{,}") for n in d["n_grid"]))
mac("VnInstances", len(d["tasks"])); mac("VnBase", sum(t["certified_eps001"] for t in d["tasks"]))
def agg(l, n):
    sel = [r for r in rows if r["learner"] == l and r["n"] == n]; by = {}
    for r in sel: by.setdefault((r["variant"], r["K"], r["d"], r["seed"]), {})[r["arm"]] = r
    pairs = [v for v in by.values() if "arrow" in v and "native" in v]
    inst = {}
    for v in pairs: inst.setdefault((v["native"]["variant"], v["native"]["K"], v["native"]["d"]), []).append(v["arrow"]["ret_frac"] - v["native"]["ret_frac"])
    gaps = {k: float(np.mean(g)) for k, g in inst.items()}
    pos = sum(g > 1e-9 for g in gaps.values()); neg = sum(g < -1e-9 for g in gaps.values())
    return dict(n_inst=len(gaps), pos=pos, neg=neg, med=float(np.median(list(gaps.values()))),
                native=float(np.mean([v["native"]["ret_frac"] for v in pairs])), arrow=float(np.mean([v["arrow"]["ret_frac"] for v in pairs])),
                native_safe=float(np.mean([v["native"]["safe"] for v in pairs])), arrow_safe=float(np.mean([v["arrow"]["safe"] for v in pairs])),
                surr=(float(np.mean([v["surrogate"]["ret_frac"] for v in by.values() if "surrogate" in v])) if any("surrogate" in v for v in by.values()) else None),
                cert=sum(1 for k, v in d["certification"].items() if k.startswith(f"{l}|{n}|") and v["certified"]), mode=d["cert_mode"][f"{l}|{n}"],
                eps_r=d["eps_prime"][f"{l}|{n}"]["eps_r"])
for l in d["learners"]:
    for i, n in enumerate(d["n_grid"]):
        a = agg(l, n); key = LKEY[l] + {2000: "A", 5000: "B", 20000: "C", 50000: "D"}[n]
        mac(f"Vn{key}Native", pct(a["native"])); mac(f"Vn{key}Arrow", pct(a["arrow"])); mac(f"Vn{key}Gap", pts(a["med"]))
        mac(f"Vn{key}Pos", f"{a['pos']}/{a['n_inst']}"); mac(f"Vn{key}NativeSafe", pct(a["native_safe"], 0)); mac(f"Vn{key}ArrowSafe", pct(a["arrow_safe"], 0))
        mac(f"Vn{key}Cert", a["cert"]); mac(f"Vn{key}EpsR", f"{a['eps_r']:.3f}")
        if a["surr"] is not None: mac(f"Vn{key}Surr", pct(a["surr"]))
        name = LNAME[l] if i == 0 else ""
# ---- asserted directions
for n in d["n_grid"]:
    for l in ("mfqi", "mpid"):
        a = agg(l, n); assert abs(a["med"]) < 1e-9 and a["pos"] == 0, (l, n, a)      # Lagrangian: singleton and K constraints coincide
    a = agg("mcpq", n); assert a["pos"] == a["n_inst"] == 9 and a["neg"] == 0, ("cpq", n, a)   # CPQ: singleton better on every instance
    a = agg("lp", n)
    if n >= 5000: assert abs(a["med"]) < 1e-9 and a["pos"] == 0 and a["neg"] == 0, ("lp", n, a)  # LP: exact tie once data suffice
assert all(agg(l, n)["cert"] == 0 for l in ("mfqi", "mpid", "mcpq") for n in d["n_grid"])        # tabular learners: no instance certifies at eps'
assert agg("lp", 20000)["cert"] == agg("lp", 50000)["cert"] == 24 and agg("lp", 5000)["cert"] == 6 and agg("lp", 2000)["cert"] == 0
aux = [max(r["lam_selected"][1:]) for r in rows if r["learner"] == "mfqi" and r["arm"] == "native"]
assert max(aux) == 0.0                                                          # dual ascent: auxiliary multipliers never activate
aux_pid = [max(r["lam_selected"][1:]) for r in rows if r["learner"] == "mpid" and r["arm"] == "native"]
mac("VnPidAuxNonzero", pct(float(np.mean(np.array(aux_pid) > 0)), 0))        # PID: share of selected iterates with a nonzero auxiliary multiplier
cpq = [agg("mcpq", n) for n in d["n_grid"]]
mac("VnCpqGapLo", pts(min(a["med"] for a in cpq))); mac("VnCpqGapHi", pts(max(a["med"] for a in cpq)))
mac("VnCpqSignP", f"{sign_p(9, 0):.3f}")
mac("VnTabEpsLo", f"{min(agg(l, n)['eps_r'] for l in ('mfqi','mpid','mcpq') for n in d['n_grid']):.3f}")
mac("VnTabEpsHi", f"{max(agg(l, n)['eps_r'] for l in ('mfqi','mpid','mcpq') for n in d['n_grid']):.3f}")
lpA = agg("lp", 2000)
mac("VnLpASafeNative", pct(lpA["native_safe"], 0)); mac("VnLpASafeArrow", pct(lpA["arrow_safe"], 0))
lag = [agg(l, n) for l in ("mfqi", "mpid") for n in d["n_grid"]]
mac("VnLagLo", pct(min(a["arrow"] for a in lag))); mac("VnLagHi", pct(max(a["arrow"] for a in lag)))
mac("VnLpCertFrac", f"{agg('lp', 20000)['cert']}/{len(d['tasks'])}")
mac("VnRows", len(rows)); mac("VnSecs", f"{d['seconds']/60:.0f}")
# exploratory small-data extension (labelled exploratory in the paper)
sm = json.load(open(os.path.join(ROOT, "results/e2e", "scope_agent_native_smalln.json")))
def safe_range(learner, arm):
    vals = []
    for n in sm["n_grid"]:
        sel = [r for r in sm["rows"] if r["learner"] == learner and r["n"] == n and r["arm"] == arm]; vals.append(float(np.mean([r["safe"] for r in sel])))
    return min(vals), max(vals)
for l, key in (("lp", "Lp"), ("mpid", "Pid"), ("mcpq", "Cpq")):
    ln, ln2 = safe_range(l, "native"); la, la2 = safe_range(l, "arrow")
    assert la2 < ln, (l, la2, ln)                                              # singleton less safe than K constraints at every small n
    mac(f"VnSm{key}NativeSafe", f"{pct(ln,0)}--{pct(ln2,0)}"); mac(f"VnSm{key}ArrowSafe", f"{pct(la,0)}--{pct(la2,0)}")
def small_gap_range(l):
    meds = []
    for n in sm["n_grid"]:
        by = {}
        for r in sm["rows"]:
            if r["learner"] == l and r["n"] == n: by.setdefault((r["variant"], r["K"], r["d"], r["seed"]), {})[r["arm"]] = r
        inst = {}
        for v in by.values():
            if "arrow" in v and "native" in v: inst.setdefault((v["native"]["variant"], v["native"]["K"], v["native"]["d"]), []).append(v["arrow"]["ret_frac"] - v["native"]["ret_frac"])
        meds.append(float(np.median([np.mean(g) for g in inst.values()])))
    return min(meds), max(meds)
for l, key in (("mfqi", "Fqi"), ("mpid", "Pid"), ("mcpq", "Cpq"), ("lp", "Lp")):
    lo, hi = small_gap_range(l); mac(f"VnSm{key}GapLo", pts(lo)); mac(f"VnSm{key}GapHi", pts(hi))
assert small_gap_range("mpid")[1] < 0 and small_gap_range("lp")[0] > 0 and abs(small_gap_range("mfqi")[1]) < 1e-3   # mixed directions, as the text states
mac("VnSmNGrid", ", ".join(f"{n:,}".replace(",", "{,}") for n in sm["n_grid"]))
open(os.path.join(GEN, "gen_v51.tex"), "w").write(H + "\n".join(M) + "\n")
print("macros", len(M))
