"""Macros and table fragments for the ICLR 2027 revision (W1--W12 except the
ARTEMIS study, which has its own generator).  Reads only archived run
files; every direction the body states is asserted here, so a rerun that
flips one refuses to emit and the sentence has to change.

Run: python3 scripts/paper/make_gen_revision.py
Writes paper/generated/gen_revision.tex and the fragments
gen_audit_table.tex, gen_runtime_table.tex, gen_scale_table.tex,
gen_baseline_table.tex, gen_price_instances.tex, gen_sweep_table.tex,
gen_accounting_table.tex, gen_funnel_mon.tex, gen_funnel_adm.tex,
gen_pipeline_funnel.tex.
"""
from __future__ import annotations

import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEN = os.path.join(ROOT, "paper", "generated")
HEAD = "% AUTO-GENERATED by paper/final/make_gen_revision.py -- do not edit\n"


def load(*p):
    with open(os.path.join(ROOT, *p)) as fh:
        return json.load(fh)


def write(name, text):
    with open(os.path.join(GEN, name), "w") as fh:
        fh.write(HEAD + text)


def pct(x, nd=1):
    return f"{100 * x:.{nd}f}\\%"


def num(x, nd=0):
    return f"{x:,.{nd}f}".replace(",", "{,}")


def mac(name, val):
    return f"\\newcommand{{\\{name}}}{{{val}}}"


M = []

# ---------------------------------------------------------------- W5 audit
au = load("results/conformal", "lp", "certificate_audit.json")
dom_order = [("synthetic", "Synth", "Synthetic maintenance"), ("real", "Cmap", "C-MAPSS replay MDP"),
             ("gridworld", "Warn", "Warning-window"), ("budget", "Budget", "Budget agent")]
rows = []
for key, tag, label in dom_order:
    d = au["domains"][key]
    sc = d["sample_complexity"]
    kmax = d["k_max_certifiable_at_n"]
    M += [mac(f"Aud{tag}B", f"{d['B']:.1f}"), mac(f"Aud{tag}W", d["w_maximal"]),
          mac(f"Aud{tag}Kmax", "none" if kmax < 0 else str(kmax)),
          mac(f"Aud{tag}Nzero", num(sc["n_zero_violation"])),
          mac(f"Aud{tag}Pmax", pct(sc["max_certifiable_violation_rate"], 2)),
          mac(f"Aud{tag}Hoeff", f"{d['hoeffding_radius_if_used']:.2f}"),
          mac(f"Aud{tag}ShipsSet", f"{d['arms']['corset']['ships']}/{d['arms']['corset']['n_seeds']}"),
          mac(f"Aud{tag}ShipsSingle", f"{d['arms']['single']['ships']}/{d['arms']['single']['n_seeds']}"),
          mac(f"Aud{tag}HoeffNzero", num(sc["hoeffding_n_mean_zero"]))]
    zmin = min(v["Z"] for v in d["per_reading"].values())
    rows.append(f"{label} & ${d['B']:.1f}$ & {d['w_maximal']} & ${zmin:.2f}$ & "
                f"{'none' if kmax < 0 else kmax} & {num(sc['n_zero_violation'])} & "
                f"{pct(sc['max_certifiable_violation_rate'], 2)} & ${d['hoeffding_radius_if_used']:.2f}$ & "
                f"{d['arms']['corset']['ships']}/{d['arms']['corset']['n_seeds']} & "
                f"{d['arms']['single']['ships']}/{d['arms']['single']['n_seeds']} \\\\\n")
write("gen_audit_table.tex", "".join(rows))
assert au["domains"]["real"]["k_max_certifiable_at_n"] < 0, "C-MAPSS is no longer range-dominated at n=300"
assert au["domains"]["synthetic"]["k_max_certifiable_at_n"] == 0
M += [mac("AudN", au["domains"]["synthetic"]["n"]), mac("AudDeltaEv", f"{au['domains']['synthetic']['delta_ev']:.2f}"),
      mac("AudLevel", f"{au['domains']['synthetic']['level']:.3f}")]
re_ = au["reevaluation"]
for key, tag in (("synthetic", "Synth"), ("real", "Cmap")):
    r = re_[key]
    assert r["reproduces_archived_count"], key
    M += [mac(f"Aud{tag}Seed", r["seed"]), mac(f"Aud{tag}K", r["k"]), mac(f"Aud{tag}H", r["horizon"]),
          mac(f"Aud{tag}MeanW", f"{r['mean_W']:.3f}"), mac(f"Aud{tag}MaxW", f"{r['max_W_observed']:.2f}"),
          mac(f"Aud{tag}CP", f"{r['cp_route_bound']:.3f}" if r["cp_route_bound"] < 1 else f"{r['cp_route_bound']:.2f}"),
          mac(f"Aud{tag}HoeffBound", f"{r['hoeffding_bound']:.2f}"), mac(f"Aud{tag}Bern", f"{r['bernstein_bound']:.2f}"),
          mac(f"Aud{tag}Zmin", f"{min(r['Z'].values()):.2f}"), mac(f"Aud{tag}Return", f"{r['learned_return']:.1f}")]
# episodes an empirical-Bernstein gate would need on the C-MAPSS seed's own moments
r = re_["real"]
B, w, dl, d = r["B"], r["w_maximal"], au["domains"]["real"]["delta_ev"], au["domains"]["real"]["budget"]
v = r["sd_W"] ** 2
ln = math.log(2.0 / (dl / w))
n_b = None
for n in range(2, 5_000_000):
    if r["mean_W"] + math.sqrt(2 * v * ln / n) + 7 * B * ln / (3 * (n - 1)) <= d:
        n_b = n
        break
assert n_b is not None
M += [mac("AudCmapBernN", num(n_b))]
# a tighter range: if the range were H/Z_max... report the ratio B / d as the loss factor
M += [mac("AudCmapRangeFactor", num(B / d)), mac("AudCmapTrueOverBudget", pct(r["mean_W"] / d, 0))]
assert r["mean_W"] < d, "the C-MAPSS re-evaluated mean W is no longer below the budget; the audit text must change"

# ---------------------------------------------------------------- W4 runtime
rt = load("results/e2e", "decide_runtime.json")["parts"]
hw = rt["exact_nonnested"]["hardware"]
M += [mac("RtCpu", hw["cpu"]), mac("RtCores", hw["n_cores"]), mac("RtRam", f"{hw['ram_bytes'] / 2**30:.0f}"),
      mac("RtSolver", "HiGHS (scipy " + hw["scipy"] + ")")]
order = [("exact_nonnested", "exact non-nested suite (Tab.~\\ref{tab:exact})", "17 inst.\\ $\\times$ 5 budgets"),
         ("policy_sufficiency", "face certificates (Tab.~\\ref{tab:e2})", "28 inst.\\ $\\times$ 5 budgets"),
         ("surrogate_price", "single-cost surrogate price", "28 inst.\\ $\\times$ 5 budgets"),
         ("policy_class_budget", "class $\\times$ budget audit, both families", "132 pools $\\times$ 5 budgets"),
         ("class_ladder", "capability ladder", f"{rt['class_ladder']['n_rows']:,} rule/class/budget rows".replace(",", "{,}")),
         ("face_ladder", "face-level ladder + admission face pass", "132 pools"),
         ("e16", "admission exact screen (enumeration)", "44 pools $\\times$ 4 budgets")]
rows = []
tot_lp = tot_milp = 0
for key, label, objs in order:
    p = rt[key]
    lp = p.get("n_value_or_face_lps", 0); mi = p.get("n_milps", 0)
    tot_lp += lp; tot_milp += mi
    assert p["reproduces_archive"], key
    rows.append(f"{label} & {objs} & {num(lp)} & {num(mi)} & ${p['wall_seconds']:.1f}$ & ${p['peak_rss_mb']:.0f}$ \\\\\n")
write("gen_runtime_table.tex", "".join(rows))
pcbp = rt["policy_class_budget"]
M += [mac("RtPoolReadings", num(pcbp["n_candidate_readings"])), mac("RtPoolClasses", num(pcbp["n_behaviour_classes"])),
      mac("RtPoolWidthMax", pcbp["max_antichain_width"])]
M += [mac("RtTotalLps", num(tot_lp)), mac("RtTotalMilps", num(tot_milp)),
      mac("RtTotalWall", f"{sum(rt[k]['wall_seconds'] for k, _, _ in order):.0f}"),
      mac("RtPeakMb", f"{max(rt[k]['peak_rss_mb'] for k, _, _ in order):.0f}"),
      mac("RtPsFaceLps", num(rt["policy_sufficiency"]["n_face_lps_by_construction"])),
      mac("RtPsValueLps", num(rt["policy_sufficiency"]["n_value_lps_by_construction"])),
      mac("RtPsTieLps", num(rt["policy_sufficiency"]["n_tiebreak_lps_by_construction"])),
      mac("RtLadderRows", num(rt["class_ladder"]["n_rows"]))]
sc = rt["scale"]
rows = []
for row in sc["rows"]:
    rows.append(f"{num(row['K'])} & {num(row['n_lp_vars'])} & ${row['seconds_value_lp']:.2f}$ & ${row['seconds_single_lps']:.1f}$ & "
                f"{row['n_value_sufficient']} & {num(row['face_lps_run'])} & ${row['seconds_face_lps']:.1f}$ \\\\\n")
write("gen_scale_table.tex", "".join(rows))
big = sc["rows"][-1]
M += [mac("RtScaleKmed", num(sc["antichain_median_e2e"])), mac("RtScaleStates", big["n_states"]),
      mac("RtScaleBigValueS", f"{big['seconds_value_lp']:.1f}"), mac("RtScaleBigSinglesS", f"{big['seconds_single_lps']:.1f}"),
      mac("RtScaleBigFaceLps", num(big["face_lps_run"])), mac("RtScaleBigFaceS", f"{big['seconds_face_lps']:.0f}"),
      mac("RtScaleBigSuff", big["n_value_sufficient"]), mac("RtScaleGeometry", sc["geometry"])]
gr = sc["compiled_state_space_growth"]
M += [mac("RtGrowthKfour", num(next(g["n_states"] for g in gr if g["K"] == 4))),
      mac("RtGrowthKeight", num(next(g["n_states"] for g in gr if g["K"] == 8))), mac("RtGrowthCap", gr[0]["cap"])]

# ---------------------------------------------------------------- W8 baselines
bl = load("results/e2e", "baseline_table.json")
c, a = bl["compiled"]["summary"], bl["admission"]["summary"]
assert c["top1_unsafe"] > 0 and a["top1_unsafe"] > 0
assert c["clarify_gain_median"] > c["surrogate_loss_max"]
M += [mac("BlN", c["n"]), mac("BlTopUnsafe", c["top1_unsafe"]), mac("BlTopGold", c["top1_is_gold"]),
      mac("BlGoldInMax", c["gold_in_maximal"]), mac("BlFaceCert", c["face_certified"]),
      mac("BlTopRatioMed", f"{c['top1_ratio_median']:.2f}"), mac("BlTopRatioMax", f"{c['top1_ratio_max']:.2f}"),
      mac("BlTopTies", c["top1_score_ties"]), mac("BlTopAltUnsafe", c["top1_alt_unsafe"]),
      mac("BlTopUnsafeUntied", c["top1_unsafe_untied"]), mac("BlNUntied", c["n_untied"]),
      mac("BlSurrMed", pct(c["surrogate_loss_median"])), mac("BlSurrMin", pct(c["surrogate_loss_min"])), mac("BlSurrMax", pct(c["surrogate_loss_max"])),
      mac("BlClarMed", pct(c["clarify_gain_median"])), mac("BlClarMin", pct(c["clarify_gain_min"])), mac("BlClarMax", pct(c["clarify_gain_max"])),
      mac("BlClarTen", pct(c["clarify_when_gain_exceeds"]["0.1"], 0)), mac("BlClarTwenty", pct(c["clarify_when_gain_exceeds"]["0.2"], 0)),
      mac("BlAdmN", a["n"]), mac("BlAdmTopUnsafe", a["top1_unsafe"]), mac("BlAdmTopGold", a["top1_is_gold"]), mac("BlAdmStrict", a["strictest_defined"]),
      mac("BlAdmSurrMed", pct(a["surrogate_loss_median"])), mac("BlAdmSurrMax", pct(a["surrogate_loss_max"])),
      mac("BlAdmClarMed", pct(a["clarify_gain_median"])), mac("BlAdmClarMax", pct(a["clarify_gain_max"])),
      mac("BlAdmClarPos", a["n"] - a["clarify_gain_zero"]),
      mac("BlAdmClarTen", pct(a["clarify_when_gain_exceeds"]["0.1"], 0)), mac("BlAdmClarTwenty", pct(a["clarify_when_gain_exceeds"]["0.2"], 0)),
      mac("BlNestedN", bl["monitoring_nested_clear"]["n"])]
sc_ = load("results/e2e", "surrogate_price.json")["aggregate_at_operating"]
assert abs(c["surrogate_loss_median"] - sc_["rel_gap_med"]) < 1e-9, "baseline-table surrogate loss disagrees with surrogate_price.json"
selfc = load("results/conformal", "selfconsistency.json") if os.path.exists(os.path.join(ROOT, "results/conformal", "selfconsistency.json")) else None
tbl = [
    f"top-1 (frozen score) & ranked on {c['n_untied']}/{c['n']}: unsafe on {c['top1_unsafe_untied']}; tied on {c['top1_score_ties']}, tie-break decides ({c['top1_unsafe']} vs {c['top1_alt_unsafe']} unsafe) & unsafe on {a['top1_unsafe']}/{a['n']}; recorded reading on {a['top1_is_gold']}/{a['n']} \\\\\n",
    "self-consistency singleton & n/a here; controlled domain: \\ScViolVote{} violation & n/a \\\\\n",
    f"strictest-when-defined & undefined (crossed); on {bl['monitoring_nested_clear']['n']} nested pools $=$ set protection & defined for {a['strictest_defined']}/{a['n']}, $=$ set protection \\\\\n",
    f"pointwise-max surrogate & safe; return $-${pct(c['surrogate_loss_min'])} to $-${pct(c['surrogate_loss_max'])} (median $-${pct(c['surrogate_loss_median'])}) & safe; median $-${pct(a['surrogate_loss_median'])}, worst $-${pct(a['surrogate_loss_max'])} \\\\\n",
    "set protection & $V_{\\Uc}$, safe & $V_{\\Uc}$, safe \\\\\n",
    f"\\method{{}} & $V_{{\\Uc}}$; singleton certified {c['face_certified']}/{c['n']}, set {c['n'] - c['face_certified']} & $V_{{\\Uc}}$; singleton certified \\FaceKyvOk{{}}/{a['n']}, set \\FaceKyvFails{{}} \\\\\n",
    f"perfect clarification & $+${pct(c['clarify_gain_min'])} to $+${pct(c['clarify_gain_max'])} (median $+${pct(c['clarify_gain_median'])}) & median $+${pct(a['clarify_gain_median'])}, $>0$ on {a['n'] - a['clarify_gain_zero']}/{a['n']} \\\\\n",
]
write("gen_baseline_table.tex", "".join(tbl))

# ---------------------------------------------------------------- W10 prices
pi = load("results/e2e", "price_instances.json")
rows = []
for g in pi["monitoring_compiled"]:
    rows.append(f"{g['geometry']} & {g['n_pools']} & {g['n_states']} & {pct(g['rel_price'])} & {'fires' if g['fires'] else 'clears'} \\\\\n")
write("gen_price_instances.tex", "".join(rows))
fk, fp = pi["free_class"]["kyverno"], pi["free_class"]["prometheus"]
assert fk["n_distinct_instances"] == 11 and fp["n_distinct_instances"] == 53
M += [mac("PiAdmInst", fk["n_distinct_instances"]), mac("PiAdmPools", fk["n_pools"]), mac("PiAdmPoolMed", pct(fk["pool_weighted_median"])),
      mac("PiAdmInstMed", pct(fk["instance_weighted_median"])), mac("PiAdmCIlo", pct(fk["instance_bootstrap_median_ci95"][0])),
      mac("PiAdmCIhi", pct(fk["instance_bootstrap_median_ci95"][1])), mac("PiAdmDup", fk["largest_duplicate_group"]),
      mac("PiAdmMin", pct(fk["instance_min"])), mac("PiAdmMax", pct(fk["instance_max"])),
      mac("PiMonInst", fp["n_distinct_instances"]), mac("PiMonPools", fp["n_pools"]), mac("PiMonPoolMed", pct(fp["pool_weighted_median"])),
      mac("PiMonInstMed", pct(fp["instance_weighted_median"])), mac("PiMonCIlo", pct(fp["instance_bootstrap_median_ci95"][0])),
      mac("PiMonCIhi", pct(fp["instance_bootstrap_median_ci95"][1])), mac("PiMonPos", fp["n_positive_instances"]),
      mac("PiGeoms", len(pi["monitoring_compiled"])), mac("PiBoot", num(fk["bootstrap"]["B"]))]
firing = [g for g in pi["monitoring_compiled"] if g["fires"]]
assert len(firing) == 1 and firing[0]["rel_price"] == min(g["rel_price"] for g in pi["monitoring_compiled"])
M += [mac("PiFireGeom", firing[0]["geometry"]), mac("PiFirePrice", pct(firing[0]["rel_price"]))]

# ---------------------------------------------------------------- W9 sweep
sw = load("results/e2e", "live_threshold_sweep.json")
rows_sw = [r for r in sw["rows"] if not r.get("empty")]
segs = []
for r in rows_sw:
    key = (tuple(r["retained"]), r["face_clear"], r["set_k3_set_safe"], r["single_k5_set_safe"])
    if segs and segs[-1][0] == key:
        segs[-1][2] = r["qhat"]
    else:
        segs.append([key, r["qhat"], r["qhat"], r])
rows = []
for key, lo, hi, r in segs:
    ret = ", ".join(x.replace("total", "$k{\\le}$").replace("run", "$B{\\le}$") for x in r["retained"])
    mx = ", ".join(x.replace("total", "$k{\\le}$").replace("run", "$B{\\le}$") for x in r["maximal"])
    ck = lambda b: "\\cmark" if b else "\\xmark"
    c1, c2, c3, c4 = ck(r["value_clear"]), ck(r["face_clear"]), ck(r["set_k3_set_safe"]), ck(r["single_k5_set_safe"])
    rows.append(f"${lo:.2f}$--${hi:.2f}$ & {ret} & {mx} & {c1} & {c2} & {c3} & {c4} \\\\\n")
write("gen_sweep_table.tex", "".join(rows))
k3 = [r["qhat"] for r in rows_sw if r["set_k3_set_safe"]]
k5 = [r["qhat"] for r in rows_sw if r["single_k5_set_safe"]]
cross = [r["qhat"] for r in rows_sw if "run2" in r["retained"]]
M += [mac("SwKThreeLo", f"{min(k3):.2f}"), mac("SwKThreeHi", f"{max(k3):.2f}"), mac("SwKFiveLo", f"{min(k5):.2f}"),
      mac("SwCrossHi", f"{max(cross):.2f}"), mac("SwSegments", len(segs)), mac("SwGridLo", f"{rows_sw[0]['qhat']:.2f}"),
      mac("SwGridHi", f"{rows_sw[-1]['qhat']:.2f}"), mac("SwCorpusQ", f"{sw['corpus_qhat']:.2f}"),
      mac("SwRunThreeScore", f"{sw['scores']['run3']:.2f}"), mac("SwTotalTwoScore", f"{sw['scores']['total2']:.2f}"),
      mac("SwRunTwoScore", f"{sw['scores']['run2']:.2f}")]
assert 0.5 >= min(k3) and 0.5 <= max(k3), "the corpus threshold is no longer inside the set-guard-safe band"
assert all(r["face_clear"] for r in rows_sw), "a retained pool in the sweep fails the face test; the sweep text must change"

# ---------------------------------------------------------------- W1/W6/W7 accounting
ga = load("results/e2e", "guarantee_accounting.json")
acc = ga["accounting"]
labels = [("raw_units", "Raw corpus units"), ("distinct_rules", "Distinct written rules"),
          ("non_template_units", "Non-template units"), ("grammar_expressible_G0", "Grammar-expressible ($\\mathcal G_0$)"),
          ("widened_grammar_G1", "Widened grammar ($\\mathcal G_1$)")]


def cell(x, nd=1):
    return "n.m." if x is None else pct(x, nd)


rows = []
for key, lab in labels:
    t = acc[key]
    g = "recorded_G1" if key == "widened_grammar_G1" else "recorded_G0"
    f = "faithful_G1" if key == "widened_grammar_G1" else "faithful_G0"
    rg, fg = t[g], t[f]
    rows.append(f"{lab} & {num(rg['n'])} & {cell(rg['reach'])} & {cell(rg['proposal'])} / {cell(fg['proposal'])} & "
                f"{cell(rg['retention'])} / {cell(fg['retention'])} & {cell(rg['e2e'])} / {cell(fg['e2e'])} \\\\\n")
write("gen_accounting_table.tex", "".join(rows))
g0 = acc["grammar_expressible_G0"]
raw = acc["raw_units"]
M += [mac("AcRawN", num(raw["recorded_G0"]["n"])), mac("AcRawEte", pct(raw["recorded_G0"]["e2e"])), mac("AcRawEteFaith", pct(raw["faithful_G0"]["e2e"])),
      mac("AcRawEteGOne", pct(raw["recorded_G1"]["e2e"])), mac("AcRawEteGOneFaith", pct(raw["faithful_G1"]["e2e"])),
      mac("AcDistinctN", num(acc["distinct_rules"]["recorded_G0"]["n"])), mac("AcDistinctEte", pct(acc["distinct_rules"]["recorded_G0"]["e2e"])),
      mac("AcDistinctEteFaith", pct(acc["distinct_rules"]["faithful_G0"]["e2e"])),
      mac("AcNonTmplN", num(acc["non_template_units"]["recorded_G0"]["n"])), mac("AcNonTmplEte", pct(acc["non_template_units"]["recorded_G0"]["e2e"])),
      mac("AcNonTmplEteFaith", pct(acc["non_template_units"]["faithful_G0"]["e2e"])),
      mac("AcExprN", num(g0["recorded_G0"]["n"])), mac("AcExprFaithN", num(g0["faithful_G0"]["expressible"])),
      mac("AcExprProp", pct(g0["recorded_G0"]["proposal"])), mac("AcExprPropFaith", pct(g0["faithful_G0"]["proposal"])),
      mac("AcExprRet", pct(g0["recorded_G0"]["retention"])), mac("AcExprRetFaith", pct(g0["faithful_G0"]["retention"])),
      mac("AcExprEte", pct(g0["recorded_G0"]["e2e"])), mac("AcExprEteFaith", pct(g0["faithful_G0"]["e2e"])),
      mac("AcExprLicFaith", num(g0["faithful_G0"]["licensed"])), mac("AcExprRetFaithN", num(g0["faithful_G0"]["retained"])),
      mac("AcExprAvail", pct(g0["availability_v4u"])),
      mac("AcGOneN", num(acc["widened_grammar_G1"]["recorded_G1"]["n"])), mac("AcGOneProp", pct(acc["widened_grammar_G1"]["recorded_G1"]["proposal"])),
      mac("AcGOnePropFaith", pct(acc["widened_grammar_G1"]["faithful_G1"]["proposal"])),
      mac("AcGOneRet", pct(acc["widened_grammar_G1"]["recorded_G1"]["retention"])), mac("AcGOneRetFaith", pct(acc["widened_grammar_G1"]["faithful_G1"]["retention"])),
      mac("AcGOneEte", pct(acc["widened_grammar_G1"]["recorded_G1"]["e2e"])), mac("AcGOneEteFaith", pct(acc["widened_grammar_G1"]["faithful_G1"]["e2e"]))]
assert abs(raw["faithful_G0"]["e2e"] - 0.0232) < 0.001 and abs(raw["recorded_G0"]["e2e"] - 0.036) < 0.001
mf = ga["monitoring_funnel"]
M += [mac(f"Mon{k}", num(v)) for k, v in (
    ("Records", mf["rule_records"]), ("Recording", mf["recording_rules_not_alerts"]), ("Alerts", mf["alerts"]),
    ("NoText", mf["alerts_without_text"]), ("WithText", mf["alerts_with_text"]), ("Outside", mf["outside_six_tuple_grammar"]),
    ("Compiled", mf["compiled"]), ("Faith", mf["compiled_faithful"]), ("Lossy", mf["compiled_lossy"]), ("Analyzable", mf["analyzable"]),
    ("Solved", mf["solved"]), ("Nested", mf["clear_by_nesting"]), ("Unanalyzed", mf["outside_compiled_control_grammar"]),
    ("AnalyzableFaith", mf["analyzable_faithful"]), ("SolvedFaith", mf["solved_faithful"]), ("NestedFaith", mf["nested_faithful"]),
    ("UnanFaith", mf["unanalyzed_faithful"]), ("Fires", mf["screen_fires"]), ("FiresFaith", mf["screen_fires_faithful"]))]
write("gen_funnel_mon.tex",
      f"rule records in the pinned manifests & {mf['rule_records']} & \\\\\n"
      f"\\quad recording rules (not alerts) & {mf['recording_rules_not_alerts']} & excluded \\\\\n"
      f"alerts & {mf['alerts']} & \\\\\n"
      f"\\quad without summary/description text & {mf['alerts_without_text']} & excluded \\\\\n"
      f"alerts with text & {mf['alerts_with_text']} & \\\\\n"
      f"\\quad expression outside the six-tuple grammar & {mf['outside_six_tuple_grammar']} & gold unrepresentable \\\\\n"
      f"compiled into executable readings & {mf['compiled']} & {mf['compiled_faithful']} faithful / {mf['compiled_lossy']} lossy \\\\\n"
      f"\\quad outside the compiled control grammar & {mf['outside_compiled_control_grammar']} & unclassified ({mf['unanalyzed_faithful']} faithful) \\\\\n"
      f"analyzable & {mf['analyzable']} & {mf['analyzable_faithful']} faithful \\\\\n"
      f"\\quad clear by nesting (no solve) & {mf['clear_by_nesting']} & {mf['nested_faithful']} faithful \\\\\n"
      f"\\quad solved exactly & {mf['solved']} & {mf['solved_faithful']} faithful \\\\\n"
      f"screen fires at $d{{=}}0.05$ & {mf['screen_fires']} & {mf['screen_fires_faithful']} faithful \\\\\n")
af = ga["admission_funnel"]
M += [mac("AdmRules", num(af["validate_rules_in_policy_documents"])), mac("AdmNoValidate", num(af["no_validate_block"])),
      mac("AdmUnmodelled", num(af["validate_outside_compiled_families"])), mac("AdmInGrammar", num(af["in_grammar_before_curation"])),
      mac("AdmCurated", num(af["curated_pools"])), mac("AdmRemoved", num(af["removed_by_curation"])),
      mac("AdmOodPolicies", num(af["policies_out_of_grammar_with_text"]))]
assert af["no_validate_block"] + af["validate_outside_compiled_families"] + af["no_match_kinds"] + af["duplicate_rules"] + af["in_grammar_before_curation"] == af["validate_rules_in_policy_documents"]
write("gen_funnel_adm.tex",
      f"rules in \\texttt{{Policy}}/\\texttt{{ClusterPolicy}} documents & {af['validate_rules_in_policy_documents']} & \\\\\n"
      f"\\quad no \\texttt{{validate}} block (mutate/generate) & {af['no_validate_block']} & excluded \\\\\n"
      f"\\quad \\texttt{{validate}} pattern outside the compiled families & {af['validate_outside_compiled_families']} & gold unrepresentable \\\\\n"
      + (f"\\quad no match kinds / duplicate & {af['no_match_kinds']} / {af['duplicate_rules']} & excluded \\\\\n" if af['no_match_kinds'] or af['duplicate_rules'] else "")
      + f"in grammar before curation & {af['in_grammar_before_curation']} & \\\\\n"
      f"\\quad removed by per-family caps and dedup & {af['removed_by_curation']} & balance, not difficulty \\\\\n"
      f"curated pools analyzed & {af['curated_pools']} & \\\\\n")
of = ga["operational_funnel"]
oc, pr, cd = of["open_corpus"], of["pinned_public_rules"], of["controlled_domains"]
ships = "/".join(str(cd[k]["ships_set"]) for k in ("synthetic", "real", "gridworld", "budget"))
M += [mac("OfShips", ships), mac("OfOpenRetainedFaith", num(oc["retained_faithful"])), mac("OfOpenGenFaith", num(oc["generated_faithful"]))]
write("gen_pipeline_funnel.tex",
      f"raw rules & {num(oc['raw_rules'])} & {pr['raw_rules']} & 4 rules \\\\\n"
      f"faithfully representable & {num(oc['faithful_representable'])} ({num(oc['representable_recorded'])} recorded) & {pr['faithful_representable']} & 4 \\\\\n"
      f"governing reading generated & {num(oc['generated_faithful'])} ({num(oc['generated'])}) & n/a (readings compiled from the rule) & 4 \\\\\n"
      f"governing reading retained & {num(oc['retained_faithful'])} ({num(oc['retained'])}) & n/a & 4 \\\\\n"
      f"decide: singleton certified / set protected & fallback to \\textsc{{protect}} (antichain median \\RtScaleKmed{{}}) & {pr['singleton_certified']}/{pr['solved']} certified; {pr['set_protected']} set ({pr['set_protected_faithful']} faithful) & 2 nested / 2 crossed \\\\\n"
      f"learned policy & not run & not run & 50 seeds each \\\\\n"
      f"deployment certificate passes (ships) & -- & -- & {ships} of 50 \\\\\n")


# ---------------------------------------------------------------- P10 third corpus
tc = load("results/e2e", "third_corpus.json")
tp = tc["pooled"]
assert tc["n_pool_errors"] == 0
assert tp["face_clear_0.005"] == 0, "the tight-budget face separation no longer replicates; text must change"
assert tp["value_clear_0.05"] == tp["face_clear_0.05"], "value and face separate at the operating budget on the third corpus; text must change"
M += [mac("TcRepos", len(tc["repos"])), mac("TcPools", num(tp["n_pools"])), mac("TcNondom", pct(tp["non_dominance_rate"])),
      mac("TcEligible", tp["compiled_eligible"]), mac("TcNested", tp["nested_clear"]), mac("TcUnanalyzed", tp["unanalyzed"]),
      mac("TcAnalyzable", tp["analyzable"]), mac("TcFiresOp", tp["fires_0.05"]), mac("TcFiresTight", tp["fires_0.005"]),
      mac("TcFiresOpPct", pct(tp["fires_0.05"] / tp["analyzable"])),
      mac("TcValueClearTight", tp["value_clear_0.005"]), mac("TcFaceClearTight", tp["face_clear_0.005"]),
      mac("TcValueClearOp", tp["value_clear_0.05"]), mac("TcFaceClearOp", tp["face_clear_0.05"]),
      mac("TcFreeFires", tp["free_fires_0.05"]), mac("TcFreeFiresPct", pct(tp["free_fires_0.05"] / tp["n_pools"], 0)),
      mac("TcLadKOne", tp["ladder"]["1"]["some"]), mac("TcLadKTwoSome", tp["ladder"]["2"]["some"]), mac("TcLadKTwoN", tp["ladder"]["2"]["n"]),
      mac("TcLadKTwoAll", tp["ladder"]["2"]["every"]), mac("TcFrontOne", tp["frontier"].get("1", 0)), mac("TcFrontTwo", tp["frontier"].get("2", 0)),
      mac("TcFrontNever", tp["frontier"].get("None", 0)), mac("TcFaithful", tp["faithful"]), mac("TcFaithfulPct", pct(tp["faithful"] / tp["n_pools"], 0)),
      mac("TcAnalyzableFaith", tp["analyzable_faithful"]), mac("TcFiresFaith", tp["fires_0.05_faithful"])]
per = tc["per_repo"]
top = max(per, key=lambda r: per[r]["fires_0.05"])
M += [mac("TcTopRepo", top), mac("TcTopRepoFires", per[top]["fires_0.05"]), mac("TcTopRepoEligible", per[top]["compiled_eligible"]),
      mac("TcTopRepoAnalyzable", per[top]["analyzable"]),
      mac("TcOtherFires", tp["fires_0.05"] - per[top]["fires_0.05"]), mac("TcOtherAnalyzable", tp["analyzable"] - per[top]["analyzable"])]
rows = []
for r in tc["repos"]:
    a = per[r]
    rows.append(f"{r} & {a['n_pools']} & {a['faithful']} & {a['compiled_eligible']} & {a['nested_clear']} & {a['unanalyzed']} & "
                f"{a['fires_0.05']} & {a['fires_0.005']} & {a['value_clear_0.005']}/{a['face_clear_0.005']} & {a['free_fires_0.05']} \\\\\n")
rows.append(f"\\midrule\nall eight & {tp['n_pools']} & {tp['faithful']} & {tp['compiled_eligible']} & {tp['nested_clear']} & {tp['unanalyzed']} & "
            f"{tp['fires_0.05']} & {tp['fires_0.005']} & {tp['value_clear_0.005']}/{tp['face_clear_0.005']} & {tp['free_fires_0.05']} \\\\\n")
write("gen_third_corpus.tex", "".join(rows))

# ---------------------------------------------------------------- W6-3 faithful recalibration
rc = load("results/e2e", "faithful_recalibration.json")
c_, t_ = rc["calibration"], rc["test"]
assert abs(c_["qhat_recorded"] - c_["qhat_archived"]) < 1e-9 and t_["retained_all_under_recorded"] == 158
M += [mac("RcQhat", f"{c_['qhat_recorded']:.2f}"), mac("RcQhatF", f"{c_['qhat_faithful']:.3f}"), mac("RcCalIn", c_["n_in_dsl"]),
      mac("RcCalFaith", c_["n_in_dsl_faithful"]), mac("RcTestFaith", t_["n_in_dsl_faithful"]),
      mac("RcRetRec", pct(t_["retention_faithful_under_recorded"])), mac("RcRetF", pct(t_["retention_faithful_under_faithful"])),
      mac("RcRetRecN", t_["retained_faithful_under_recorded"]), mac("RcRetFN", t_["retained_faithful_under_faithful"]),
      mac("RcEteF", pct(t_["e2e_faithful_under_faithful"])), mac("RcEteRec", pct(t_["e2e_faithful_under_recorded"]))]


# ---------------------------------------------------------------- V19 evaluator at 20,000 episodes
esp = os.path.join(ROOT, "results/conformal", "lp", "evaluator_scale.json")
if os.path.exists(esp):
    es = load("results/conformal", "lp", "evaluator_scale.json")
    sm = es["summary"]
    M += [mac("EsN", num(es["n_episodes"]))]
    rows = []
    lab = dict(synthetic="Synthetic maintenance", real="C-MAPSS replay MDP")
    arml = dict(corset="set", single="single")
    for key in ("synthetic/corset", "synthetic/single", "real/corset", "real/single"):
        if key not in sm:
            continue
        v = sm[key]; dom, arm = key.split("/")
        tag = ("Synth" if dom == "synthetic" else "Cmap") + ("Set" if arm == "corset" else "Single")
        assert v["reproduces_archive"] == v["n_seeds"], f"{key}: retrained seeds do not all reproduce the archived counts"
        M += [mac(f"Es{tag}N", v["n_seeds"]), mac(f"Es{tag}Arch", v["archived_ships300"]), mac(f"Es{tag}CP", v["cp_ships"]),
              mac(f"Es{tag}Hoeff", v["hoeffding_ships"]), mac(f"Es{tag}Bern", v["bernstein_ships"]), mac(f"Es{tag}Below", v["true_mean_below_d"]),
              mac(f"Es{tag}MeanMed", f"{v['mean_W_median']:.3f}"), mac(f"Es{tag}MeanMax", f"{v['mean_W_max']:.3f}"),
              mac(f"Es{tag}BernMed", f"{v['bernstein_bound_median']:.3f}"),
              mac(f"Es{tag}BernNmed", num(v["n_needed_bernstein_median"]) if v["n_needed_bernstein_median"] else "--")]
        rows.append(f"{lab[dom]} ({arml[arm]}) & {v['n_seeds']} & {v['archived_ships300']} & {v['true_mean_below_d']} & {v['cp_ships']} & {v['hoeffding_ships']} & {v['bernstein_ships']} & ${v['mean_W_median']:.3f}$ & {num(v['n_needed_bernstein_median']) if v['n_needed_bernstein_median'] else '--'} \\\\\n")
    write("gen_evaluator_scale.tex", "".join(rows))


# ------------------------------------------- body tables of the restructured build
# E4: the faithful-gold column of the accounting table, as its own fragment.
gaf = load("results/e2e", "guarantee_accounting.json")["accounting"]
_pop = [("raw_units", "Raw corpus units"), ("distinct_rules", "Distinct written rules"),
        ("non_template_units", "Non-template units"), ("grammar_expressible_G0", "Frozen-grammar group")]
_rows, _seen = [], {}
for key, label in _pop:
    c = gaf[key]["faithful_G0"]
    rec = gaf[key]["recorded_G0"]
    assert c["retention"] >= 0.90, f"{key}: retention given generation fell below the nominal 90%; the text must change"
    _seen[key] = c
    # reach is the recorded-gold share the frozen grammar expresses (the population
    # column of the accounting table); proposal/retention/e2e are on the faithful gold.
    _rows.append(f"{label} & {num(c['n'])} & {pct(rec['reach'])} & {pct(c['proposal'])} & {pct(c['retention'])} & {pct(c['e2e'])} \\\\\n")
assert gaf["grammar_expressible_G0"]["recorded_G0"]["reach"] == 1.0
assert _seen["grammar_expressible_G0"]["expressible"] == 173 and _seen["grammar_expressible_G0"]["n"] == 315, \
    "the faithful subset of the grammar-expressible group moved; Section 5.4 states 173 of 315"
assert _seen["raw_units"]["e2e"] < _seen["grammar_expressible_G0"]["e2e"], "the raw-corpus rate is no longer the smaller one"
write("gen_accounting_faithful.tex", "".join(_rows))
M += [mac("AcFaithProp", pct(_seen["raw_units"]["proposal"])), mac("AcFaithRet", pct(_seen["raw_units"]["retention"])),
      mac("AcLicensedFaithN", _seen["grammar_expressible_G0"]["licensed"]),
      mac("AcRetainedFaithN", _seen["grammar_expressible_G0"]["retained"]),
      mac("AcGenMissFaith", pct(1 - _seen["grammar_expressible_G0"]["proposal"], 0)),
      mac("AcGenMissExpr", pct(1 - _seen["grammar_expressible_G0"]["licensed"] / _seen["grammar_expressible_G0"]["n"], 0))]

# E5/E6: the controlled domains, from the archived certificates.
dep = load("results/conformal", "lp", "deploy_certificate.json")["domains"]
sp = load("results/conformal", "lp", "shadow_price.json")["domains"]
_dom = [("synthetic", "Synthetic maintenance"), ("real", "C-MAPSS replay MDP"),
        ("gridworld", "Warning-window"), ("budget", "Budget agent")]
_learn, _ship = [], []
for key, label in _dom:
    ar = dep[key]["arms"]; t2 = sp[key]["t2_shadow_price"]
    vs, vr = t2["V_psi_star"], t2["V_robust"]
    price = (vs - vr) / vs
    assert ar["single"]["seed_mean_rate"] > ar["corset"]["seed_mean_rate"], \
        f"{key}: the single-reading arm no longer violates more often than the set arm"
    au = load("results/conformal", "lp", "certificate_audit.json")["domains"][key]
    n0 = au["sample_complexity"]["n_zero_violation"]
    ships_set, ships_single = au["arms"]["corset"]["ships"], au["arms"]["single"]["ships"]
    assert (n0 <= au["n"]) == (ships_set > 0), \
        f"{key}: the zero-violation sample requirement and the ships count disagree"
    _learn.append(f"{label} & ${100*ar['single']['seed_mean_rate']:.1f}\\%$ & ${100*ar['corset']['seed_mean_rate']:.1f}\\%$ & ${100*price:.1f}\\%$ \\\\\n")
    _ship.append(f"{label} & {au['n']} & {num(n0)} & ${ships_single}/{au['arms']['single']['n_seeds']}$ & ${ships_set}/{au['arms']['corset']['n_seeds']}$ \\\\\n")
write("gen_learn_table.tex", "".join(_learn))
write("gen_ship_table.tex", "".join(_ship))
_real = load("results/conformal", "lp", "certificate_audit.json")["domains"]["real"]
assert _real["arms"]["corset"]["ships"] == 0 and _real["sample_complexity"]["n_zero_violation"] > _real["n"], \
    "C-MAPSS now certifies at n=300; Section 5.6 must change"


# ---------------------------------------------------------------- third corpus, body columns
_tc = load("results/e2e", "third_corpus.json")
_names = [("mimir", "Mimir"), ("loki", "Loki"), ("cluster-monitoring-operator", "OpenShift monitoring"),
          ("victoriametrics", "VictoriaMetrics"), ("rook", "Rook"), ("ceph", "Ceph"),
          ("thanos", "Thanos"), ("tidb", "TiDB")]
_tot = dict(pools=0, elig=0, f05=0, f005=0, vc=0, fc=0, free=0)
_rows = []
for key, label in _names:
    r = _tc["per_repo"][key]
    vc, fc = r["value_clear_0.005"], r["face_clear_0.005"]
    _rows.append(f"{label} & {r['n_pools']} & {r['compiled_eligible']} & {r['fires_0.05']} & {r['fires_0.005']} & {vc} / {fc} & {r['free_fires_0.05']} \\\\\n")
    for k, v in (("pools", r["n_pools"]), ("elig", r["compiled_eligible"]), ("f05", r["fires_0.05"]),
                 ("f005", r["fires_0.005"]), ("vc", vc), ("fc", fc), ("free", r["free_fires_0.05"])):
        _tot[k] += v
_p = _tc["pooled"]
assert _tot["pools"] == _p["n_pools"] == 465 and _tot["elig"] == _p["compiled_eligible"] == 100
assert _tot["fc"] == 0, "a reading now passes the policy test at the tight budget on the third corpus; Section 5.2 must change"
assert _tot["vc"] == _p["value_clear_0.005"] and _tot["f005"] == _p["fires_0.005"]
_rows.append("\\midrule\n")
_rows.append(f"\\textbf{{Total}} & \\textbf{{{_tot['pools']}}} & \\textbf{{{_tot['elig']}}} & \\textbf{{{_tot['f05']}}} & "
             f"\\textbf{{{_tot['f005']}}} & \\textbf{{{_tot['vc']} / {_tot['fc']}}} & \\textbf{{{_tot['free']}}} \\\\\n")
write("gen_third_corpus_main.tex", "".join(_rows))
# compact four-column presentation (Appendix D.1): pools, value-screen clears and face clears at d=0.005
_compact = [("mimir", "Grafana Mimir"), ("loki", "Grafana Loki"), ("cluster-monitoring-operator", "OpenShift cluster-monitoring-operator"),
            ("victoriametrics", "VictoriaMetrics"), ("rook", "Rook"), ("ceph", "Ceph"), ("thanos", "Thanos"), ("tidb", "TiDB")]
_crows = [f"{label} & {_tc['per_repo'][key]['n_pools']} & {_tc['per_repo'][key]['value_clear_0.005']} & {_tc['per_repo'][key]['face_clear_0.005']} \\\\\n"
          for key, label in _compact]
assert sum(_tc['per_repo'][k]['value_clear_0.005'] for k, _ in _compact) == _tot["vc"] == 57 and _tot["fc"] == 0
_crows.append("\\midrule\n")
_crows.append(f"All eight & {_tot['pools']} & {_tot['vc']} & {_tot['fc']} \\\\\n")
write("gen_third_corpus_compact.tex", "".join(_crows))
M += [mac("TcMainPools", _tot["pools"]), mac("TcMainExact", _tot["elig"]), mac("TcMainValue", _tot["vc"]),
      mac("TcMainPolicy", _tot["fc"]), mac("TcMainFiresOp", _tot["f05"]), mac("TcMainFiresTight", _tot["f005"]),
      mac("TcMainFree", _tot["free"]), mac("TcMainOrgs", len(_names))]

write("gen_revision.tex", "\n".join(M) + "\n")
print(f"wrote gen_revision.tex ({len(M)} macros) + 10 fragments; all asserts passed")
