"""Emit generated/gen_r6.tex: surrogate price, threshold-adjacency, Kyverno
exclusion breakdown.  Three reviewer questions, each answered from an archive
or a deterministic re-parse, each claim asserted.
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(str(ROOT), "src"))
OUT = os.path.join(ROOT, "paper", "generated", "gen_r6.tex")


def pct(x, nd=1):
    return f"{100 * x:.{nd}f}\\%"


def main() -> None:
    m = ["% AUTO-GENERATED by scripts/paper/make_gen_r6.py -- do not edit"]

    # ---- 1. exact surrogate price of single-cost always-robustify ---------
    sp = json.load(open(os.path.join(ROOT, "results/e2e",
                                     "surrogate_price.json")))
    ag = sp["aggregate_at_operating"]
    assert ag["n_clear_positive_gap"] == ag["n_clear"], \
        "some screen-clear instance has zero surrogate gap; Section 5.2 " \
        "says the gap is strictly positive on every clearing instance"
    assert ag["infeasible_surrogate"] == 0
    m += [f"\\newcommand{{\\SurrN}}{{{ag['n_instances']}}}",
          f"\\newcommand{{\\SurrClearN}}{{{ag['n_clear']}}}",
          f"\\newcommand{{\\SurrRelMin}}{{{pct(ag['rel_gap_min'])}}}",
          f"\\newcommand{{\\SurrRelMed}}{{{pct(ag['rel_gap_med'])}}}",
          f"\\newcommand{{\\SurrRelMax}}{{{pct(ag['rel_gap_max'])}}}"]

    # ---- 2. threshold adjacency of the gold reading, corpus-wide ----------
    cvf = json.load(open(os.path.join(
        ROOT, "results/conformal", "benchmark_sg", "calib_vs_fixed.json")))
    stab = json.load(open(os.path.join(
        ROOT, "experiments", "live_agent", "ensemble_scores_runcaps_stability.json")))
    sds = []
    for nm in ("psi_run>=2", "psi_run>=3", "psi_run>=4"):
        means = [float(np.mean(p[nm])) for p in stab["panels"]]
        sds.append(float(np.std(means, ddof=1)))
    eps_lo, eps_hi = round(min(sds), 2), round(max(sds), 2)
    # the operating delta level of the source-grounded study
    rules = []
    for fam in ("prometheus", "kyverno"):
        lv = cvf["per_rule"][fam]
        key = "delta_0.1" if "delta_0.1" in lv else sorted(lv)[0]
        rules += lv[key]
    gaps = [abs(r["gold_score"] - r["qhat"]) for r in rules]
    n = len(gaps)
    frac_lo = sum(1 for g in gaps if g <= eps_lo) / n
    frac_hi = sum(1 for g in gaps if g <= eps_hi) / n
    m += [f"\\newcommand{{\\TnN}}{{{n}}}",
          f"\\newcommand{{\\TnEpsLo}}{{{eps_lo:g}}}",
          f"\\newcommand{{\\TnEpsHi}}{{{eps_hi:g}}}",
          f"\\newcommand{{\\TnFracLo}}{{{pct(frac_lo)}}}",
          f"\\newcommand{{\\TnFracHi}}{{{pct(frac_hi)}}}"]

    # ---- 3. what the 260 non-compiling Kyverno rules are ------------------
    os.environ.setdefault("SAORL_CONFORMAL", "1")
    from saorl.benchmark_sg.parse import parse_kyverno
    kept, skipped = parse_kyverno()
    assert skipped["curated_kept"] == len(kept)
    # the re-parse must agree with the archived benchmark counts, and the
    # published 304 = compiling pools + out-of-DSL-with-text
    rep = json.load(open(os.path.join(
        ROOT, "results/conformal", "benchmark_sg", "report.json")))
    kc = rep["counts"]["kyverno"]
    assert kc["skipped"]["unmodelled_validate"] == skipped["unmodelled_validate"]
    assert kc["skipped"]["no_validate"] == skipped["no_validate"]
    assert kc["skipped"]["raw_parsed"] == skipped["raw_parsed"]
    excluded = kc["oodsl_with_text"]
    assert kc["n_pools"] + excluded == 304, \
        "44 + 260 no longer reconciles with the published 304"
    m += [f"\\newcommand{{\\KyvKept}}{{{skipped['curated_kept']}}}",
          f"\\newcommand{{\\KyvRaw}}{{{skipped['raw_parsed']}}}",
          f"\\newcommand{{\\KyvExcluded}}{{{excluded}}}",
          f"\\newcommand{{\\KyvSkipUnmod}}{{{skipped.get('unmodelled_validate', 0)}}}",
          f"\\newcommand{{\\KyvSkipNoVal}}{{{skipped.get('no_validate', 0)}}}"]

    with open(OUT, "w", encoding="utf8") as fh:
        fh.write("\n".join(m) + "\n")
    print("\n".join(m))


if __name__ == "__main__":
    main()
