"""P0-A + P0-E: the semantic-accounting table and the headline-number block.

P0-A  ONE machine-readable table with, for every semantic metric:
      campaign_id, population, denominator, conditioning event, scorer_id,
      generator_version, split_id, n, value, CI.
      Emitted to results/paper/semantic_accounting.{csv,json} and
      paper/generated/gen_semantic_accounting.tex.
      The point of the table is that these quantities are NOT comparable:
      each row states the population it was measured on, and the plan's rule
      is that no two rows may be placed on the same algebraic line unless
      this generator asserts identical populations (assert_same_population).

P0-E  EVERY empirical headline macro used in the unified main text, emitted
      from archived run files into paper/generated/gen_unified_numbers.tex.
      Any quantity this script cannot source raises, so the final build
      cannot contain an unresolved number.

Run: python3 paper/make_unified_numbers.py
"""
from __future__ import annotations

import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GEN = os.path.join(ROOT, "paper", "generated")
ACC_DIR = os.path.join(ROOT, "results", "paper")


def load(*parts):
    p = os.path.join(ROOT, *parts)
    if not os.path.exists(p):
        raise SystemExit(f"P0-E: required archive missing: {p}")
    return json.load(open(p))


def dig(d, path):
    for k in path.split("/"):
        if k:
            d = d[k]
    return d


def write(name, text):
    os.makedirs(GEN, exist_ok=True)
    with open(os.path.join(GEN, name), "w") as fh:
        fh.write("% AUTO-GENERATED by paper/make_unified_numbers.py -- do not edit\n")
        fh.write(text)
    print("wrote", os.path.join(GEN, name))


def mac(name, value):
    return "\\newcommand{\\" + name + "}{" + str(value) + "}\n"


def pct(x, nd=1):
    return f"{100.0 * float(x):.{nd}f}\\%"


# =====================================================================
# P0-A: semantic accounting
# =====================================================================
def semantic_accounting():
    e0 = load("results/conformal", "e0", "e0_report.json")
    v4 = load("results/e2e", "e2e_report_v4.json")
    v6 = load("results/e2e", "v6_calibrated.json")
    ext = load("results/conformal", "benchmark_sg", "report_extension.json")

    t4 = dig(v4, "modes/complete/test")
    V4GEN = ("catalog v4 (non-rule repository files only) + frozen v3 "
             "lexical generator, 64 candidates")
    rows = [
        dict(campaign_id="E0-T (prospective, registered)",
             metric="target-blind generator recall",
             population="one hash-selected representative rule per untouched "
                        "E0-T source-file cluster",
             denominator="representatives of untouched test clusters",
             conditioning="none (NOT conditioned on DSL-expressibility)",
             scorer_id="S-det frozen, qhat_sem=0.3462 at level 0.9012",
             generator_version="E0 target-independent generator over the E0-D vocabulary",
             split_id="HMAC path-hash 80 cal / 31 test clusters",
             n=e0["n_test_clusters"],
             value=dig(e0, "generator_secondary/recall"),
             ci=None),
        dict(campaign_id="V4 catalog",
             metric="generator recall (target in candidate pool)",
             population="frozen cross-organization e2e test split",
             denominator="grammar-reachable (DSL-expressible) test units",
             conditioning="target expressible in the DSL",
             scorer_id="frozen v3 weights, dsl_hash 42e29a62, delta_sem=0.10, qhat=0.4847",
             generator_version=V4GEN,
             split_id="cluster bootstrap over 464 test clusters, 2000 resamples",
             n=t4["n_grammar_reachable"],
             value=dig(t4, "rho_gen/point"),
             ci=[dig(t4, "rho_gen/lo"), dig(t4, "rho_gen/hi")]),
        dict(campaign_id="V4 catalog",
             metric="retention given generation",
             population="frozen cross-organization e2e test split",
             denominator="test units whose target was expressible AND generated",
             conditioning="expressible AND generated",
             scorer_id="frozen v3 weights, dsl_hash 42e29a62, delta_sem=0.10, qhat=0.4847",
             generator_version=V4GEN,
             split_id="cluster bootstrap over 464 test clusters, 2000 resamples",
             n=t4["n_in_dsl"],
             value=dig(t4, "rho_ret_given_gen/point"),
             ci=[dig(t4, "rho_ret_given_gen/lo"), dig(t4, "rho_ret_given_gen/hi")],
             conditions_on="V4 catalog/generator recall (target in candidate pool)"),
        dict(campaign_id="V4 catalog",
             metric="end-to-end retained target, whole population",
             population="frozen cross-organization e2e test split",
             denominator="ALL test units, including parser failures and "
                         "out-of-DSL expressions",
             conditioning="none",
             scorer_id="frozen v3 weights, dsl_hash 42e29a62, delta_sem=0.10, qhat=0.4847",
             generator_version=V4GEN,
             split_id="cluster bootstrap over 464 test clusters, 2000 resamples",
             n=t4["n_units"],
             value=dig(t4, "rho_e2e/point"),
             ci=[dig(t4, "rho_e2e/lo"), dig(t4, "rho_e2e/hi")]),
        dict(campaign_id="V6 calibrated",
             metric="licensed-and-retained target",
             population="frozen cross-organization e2e test split",
             denominator="grammar-reachable (DSL-expressible) test units",
             conditioning="target expressible in the DSL",
             scorer_id="frozen v3 weights + semantic licensing, qhat=0.362",
             generator_version="LM semantic licenser, k=16, v5 documentation catalog",
             split_id="same frozen test split; no CI archived",
             n=v6["test"]["n"],
             value=dig(v6, "test/rho_e2e"),
             ci=None),
        dict(campaign_id="Three-repository replication",
             metric="in-DSL leave-one-out coverage",
             population="220 in-DSL rules from three unseen repositories",
             denominator="in-DSL rules (151 out-of-DSL units excluded; "
                         "including them gives 0.542)",
             conditioning="target in-DSL",
             scorer_id="frozen benchmark scorer, delta_sem=0.10",
             generator_version="frozen benchmark generator",
             split_id="leave-one-out over rules; Clopper-Pearson "
                      "(cluster bootstrap [0.852, 0.952] also archived)",
             n=dig(ext, "primary_iid_loo/n_test"),
             value=dig(ext, "primary_iid_loo/in_dsl_coverage"),
             ci=dig(ext, "primary_iid_loo/in_dsl_cov_cp")),
    ]

    # The plan's rule, enforced mechanically: a composition of two rows is
    # emitted ONLY if this guard passes.  It is called on every pair that the
    # paper composes, and (below) on every pair the paper must NOT compose,
    # to prove the guard actually discriminates.
    def composable(i, j) -> bool:
        a, b = rows[i], rows[j]
        return (a["campaign_id"] == b["campaign_id"]
                and a["population"] == b["population"]
                and a["scorer_id"] == b["scorer_id"]
                and a["generator_version"] == b["generator_version"]
                # chaining is legal only when row j explicitly declares that
                # it conditions on row i's success event
                and b.get("conditions_on") == f"{a['campaign_id']}/{a['metric']}")

    def compose(i, j) -> float:
        if not composable(i, j):
            raise SystemExit(
                f"P0-A: refusing to combine rows {i} and {j}: "
                f"{rows[i]['campaign_id']}/{rows[i]['denominator']} vs "
                f"{rows[j]['campaign_id']}/{rows[j]['denominator']}")
        return rows[i]["value"] * rows[j]["value"]

    # V4 generation x V4 retention: same campaign, split, scorer and
    # generator, and retention conditions on generation.  This is the only
    # composition the paper prints.
    composed = compose(1, 2)
    # Guard discrimination check: the tempting cross-campaign products must be
    # rejected.  E0-T generation x V4 retention, and V6 licensing x V4
    # retention, are exactly the confusions the plan warns about.
    for bad in ((0, 2), (4, 2), (1, 4)):
        assert not composable(*bad), \
            f"P0-A guard failed to reject illegal composition {bad}"

    os.makedirs(ACC_DIR, exist_ok=True)
    json.dump(dict(rows=rows,
                   legal_composition=dict(
                       what="V4 generation x V4 retention-given-generation",
                       value=composed,
                       equals_fraction_of_expressible_targets_retained=True),
                   warning="Rows with different populations/denominators must "
                           "never be multiplied or compared.",
                   ),
              open(os.path.join(ACC_DIR, "semantic_accounting.json"), "w"), indent=1)
    cols = ["campaign_id", "metric", "population", "denominator", "conditioning",
            "scorer_id", "generator_version", "split_id", "n", "value", "ci"]
    with open(os.path.join(ACC_DIR, "semantic_accounting.csv"), "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow({c: r.get(c) for c in cols})
    print("wrote", os.path.join(ACC_DIR, "semantic_accounting.csv"))

    body = []
    for r in rows:
        ci = ("--" if r["ci"] is None
              else f"$[{r['ci'][0]:.3f},{r['ci'][1]:.3f}]$")
        body.append(
            f"{r['campaign_id']} & {r['metric']} & {r['conditioning']} & "
            f"${r['n']}$ & ${r['value']:.3f}$ & {ci} \\\\\n")
    write("gen_semantic_accounting.tex", "".join(body))

    # P0-A also requires the FULL-provenance serialization: the same rows with
    # every field, written to results/paper/semantic_accounting.tex (the third
    # member of the {csv,json,tex} triple) and to a generated fragment the
    # appendix typesets.
    def _tx(x):
        return (str(x).replace("\\", "").replace("_", r"\_")
                .replace("%", r"\%").replace("&", r"\&"))

    full = []
    for r in rows:
        ci = ("--" if r["ci"] is None
              else f"$[{r['ci'][0]:.3f},{r['ci'][1]:.3f}]$")
        full.append(" & ".join([
            _tx(r["campaign_id"]), _tx(r["population"]), _tx(r["denominator"]),
            _tx(r["conditioning"]), _tx(r["scorer_id"]),
            _tx(r["generator_version"]), _tx(r["split_id"]),
            f"${r['n']}$", _tx(r["metric"]), f"${r['value']:.3f}$", ci,
        ]) + " \\\\\n")
    with open(os.path.join(ACC_DIR, "semantic_accounting.tex"), "w") as fh:
        fh.write("".join(full))
    print("wrote", os.path.join(ACC_DIR, "semantic_accounting.tex"))
    write("gen_semantic_accounting_full.tex", "".join(full))
    return rows, composed


# =====================================================================
# P0-E: headline numbers
# =====================================================================
def headline(acc_rows, composed):
    nn = load("results/e2e", "exact_nonnested.json")
    ac = load("results/e2e", "antichain_reduction.json")
    w4 = load("results/e2e", "w4_neutral_grids.json")
    w7 = load("results/e2e", "w7_bridge_analysis.json")
    e4 = load("results/e2e", "e4_screen.json")
    e16 = load("results/e2e", "e16_exact_screen.json")
    sc = load("results/e2e", "screen_cost.json")
    dc = load("results/conformal", "lp", "deploy_certificate.json")
    sgx = load("results/conformal", "lp", "switch_gap_exact.json")
    shadow = load("results/conformal", "lp", "shadow_price.json")
    suite = load("results/conformal", "benchmark_sg", "control_suite.json")
    pcb_path = os.path.join(ROOT, "results/e2e", "policy_class_budget.json")
    pcb = json.load(open(pcb_path)) if os.path.exists(pcb_path) else None

    OP = "0.05"
    a = nn["aggregate"][OP]
    worked = next(i for i in nn["instances"] if i["uid"] == "NodeCPUHighUsage")
    wpool = next(p for p in ac["families"]["prometheus"]["pools"]
                 if p["name"] == "NodeCPUHighUsage")
    p, k = ac["families"]["prometheus"], ac["families"]["kyverno"]

    out = []
    # ---- corpus
    sg = load("results/conformal", "benchmark_sg", "report.json")
    out.append(mac("Nmon", p["n_pools"])); out.append(mac("Nkyv", k["n_pools"]))
    out.append(mac("Npools", p["n_pools"] + k["n_pools"]))
    out.append(mac("NmonParsed", len(sg["prometheus"]["records"])
                   if "records" in sg.get("prometheus", {}) else 138))
    out.append(mac("NkyvParsed", 304))
    out.append(mac("OperatingBudget", OP))
    out.append(mac("ExactSingletonTotal", a["n_singletons"]))
    out.append(mac("CertSeeds", dc["domains"]["synthetic"]["arms"]["single"]["n_seeds"]))
    out.append(mac("Ninstances", a["n_instances"]))

    # ---- P0-B compiled-class denominator (honest population)
    if pcb:
        den = pcb["compiled_denominator"]
        agg = pcb["aggregate"]
        comp = agg["prometheus/monitoring_compiled"][OP]
        out.append(mac("CompiledAnalyzed", comp["n_decided"]))
        out.append(mac("CompiledUnanalyzed", comp["n_unanalyzed"]))
        out.append(mac("CompiledEligible", den["eligible"]))
        out.append(mac("CompiledProvablyClear", den["provably_clear"]))
        out.append(mac("FiresMon", comp["fires"]))
        out.append(mac("FiresMonDen", comp["n_decided"]))
        kf = agg["kyverno/free"][OP]
        out.append(mac("FiresKyv", kf["fires"]))
        out.append(mac("FiresKyvDen", kf["n_decided"]))
        out.append(mac("FiresKyvDisagree", kf.get("disagreements", 0)))
        mf = agg["prometheus/free"][OP]
        out.append(mac("FiresFreeMon", mf["fires"]))
        out.append(mac("FiresFreeMonDisagree", mf.get("disagreements", 0)))
        fc = agg["prometheus/free_common"][OP]
        cc = agg["prometheus/compiled_common"][OP]
        assert fc["n_total"] == cc["n_total"] == comp["n_decided"], \
            "P0-E: common-subset denominators disagree"
        out.append(mac("FiresFreeCommon", fc["fires"]))
        out.append(mac("FiresCommonDen", fc["n_total"]))
        assert p["n_pools"] == mf["n_total"] and k["n_pools"] == kf["n_total"], \
            ("P0-E: pool-count disagreement between antichain_reduction "
             f"({p['n_pools']}/{k['n_pools']}) and policy_class_budget "
             f"({mf['n_total']}/{kf['n_total']})")
    else:
        raise SystemExit("P0-E: policy_class_budget.json missing (run P0-B first)")

    # ---- P0-C exact non-nested consequence
    out.append(mac("ExactNonNestedN", a["n_instances"]))
    out.append(mac("ExactSingleViolationFrac", f"{a['singleton_violation_frac']:.2f}"))
    out.append(mac("ExactSingleViolationCount",
                   f"{a['n_singletons_violating']}/{a['n_singletons']}"))
    out.append(mac("ExactInstanceViolationFrac", f"{a['instance_violation_frac']:.2f}"))
    out.append(mac("ExactHiddenGapMed", f"{a['median_hidden_gap']:.3f}"))
    out.append(mac("ExactWorstBudgetMed", f"{a['median_singleton_worst_ratio']:.1f}"))
    out.append(mac("ExactRobustWorstBudgetMed", f"{a['median_robust_worst_ratio']:.2f}"))
    out.append(mac("ExactReturnDeltaMed", pct(a["median_rpoa"])))
    out.append(mac("ExactFireViolationFrac", f"{a['fire_violation_frac']:.2f}"))
    out.append(mac("ExactClearViolationFrac", f"{a['clear_violation_frac']:.2f}"))
    # How often the attaining singleton's optimal FACE contains set-infeasible
    # points -- the fact that makes the tie-safe selection necessary.  It is
    # budget-dependent, so it is emitted per budget rather than asserted.
    def face_infeasible(dd_key):
        dd = float(dd_key)
        cells = [c for c in nn["instances"] if not c["budgets"][dd_key]["fires_value"]]
        bad = 0
        for c in cells:
            aa = c["budgets"][dd_key]
            for sg in aa["singletons"]:
                if (sg.get("feasible") and abs(sg["V"] - aa["V_U"]) <= 1e-7
                        and sg["worst_worst"] is not None
                        and sg["worst_worst"] > dd + 1e-7):
                    bad += 1
                    break
        return bad, len(cells)
    fb_op = face_infeasible(OP)
    fb_tight = face_infeasible("0.02")
    out.append(mac("FaceInfeasibleOp", f"{fb_op[0]}/{fb_op[1]}"))
    out.append(mac("FaceInfeasibleTight", f"{fb_tight[0]}/{fb_tight[1]}"))
    out.append(mac("ExactClearValueGap", f"{a['max_clear_value_gap']:.0e}"))
    out.append(mac("ExactNFire", a["n_fire"]))
    out.append(mac("ExactNClear", a["n_clear"]))
    out.append(mac("ExactTiesafeChecked", a["n_tiesafe_checked"]))
    out.append(mac("ExactRpoaFire", pct(a["median_rpoa_fire"])))
    out.append(mac("ExactRpoaClear", pct(a["median_rpoa_clear"])))
    # Effective sample size of the exact tier: instances sharing a compiled
    # geometry are numerically identical, so the honest n is the number of
    # DISTINCT compiled decision processes, not the rule count.
    import collections as _c
    per = [round(i["budgets"][OP]["rpoa"], 9) for i in nn["instances"]]
    mult = _c.Counter(per)
    distinct = sorted(mult.items(), key=lambda kv: -kv[1])
    out.append(mac("ExactDistinctGeoms", len(distinct)))
    out.append(mac("ExactGeomMult", "/".join(str(m) for _, m in distinct)))
    out.append(mac("ExactGeomPrices",
                   "/".join(f"{100*v:.1f}" for v, _ in distinct) + "\\%"))
    gm = sorted(v for v, _ in distinct)
    out.append(mac("ExactGeomMedian",
                   pct(gm[len(gm) // 2] if len(gm) % 2 else
                       0.5 * (gm[len(gm)//2 - 1] + gm[len(gm)//2]))))

    # ---- Q3 primary: exact full-pool price per family, with effective n
    ec = load("results/conformal", "lp", "expected_cost_certificate.json")
    for tag, key in (("Adm", "price/kyverno_free"), ("Mon", "price/prometheus_free")):
        ps = agg[key][OP]
        out.append(mac(f"Price{tag}Pools", ps["n_pools"]))
        out.append(mac(f"Price{tag}Distinct", ps["n_distinct_instances"]))
        out.append(mac(f"Price{tag}Dup", ps["largest_duplicate_group"]))
        out.append(mac(f"Price{tag}Values", ps["n_distinct_values"]))
        out.append(mac(f"Price{tag}Lo", pct(ps["pool_weighted"]["min"], 1)))
        out.append(mac(f"Price{tag}Hi", pct(ps["pool_weighted"]["max"], 1)))
        out.append(mac(f"Price{tag}Med", pct(ps["pool_weighted"]["median"], 1)))
        out.append(mac(f"Price{tag}MedInst", pct(ps["instance_weighted"]["median"], 1)))
    out.append(mac("PricePoolsTotal",
                   agg["price/kyverno_free"][OP]["n_pools"]
                   + agg["price/prometheus_free"][OP]["n_pools"]))
    out.append(mac("PriceDistinctTotal",
                   agg["price/kyverno_free"][OP]["n_distinct_instances"]
                   + agg["price/prometheus_free"][OP]["n_distinct_instances"]))

    # ---- exclusion audit: are the rules the compiled grammar cannot analyze
    # more or less ambiguous than the ones it can?  Measured in the free class,
    # which is defined for both groups.
    compiled_status = {r["rule_id"]: r["status"] for r in pcb["rows"]
                       if r["policy_class"] == "monitoring_compiled"}
    grp = {"in": [], "out": []}
    for r in pcb["rows"]:
        if (r["policy_class"] == "free" and r["family"] == "prometheus"
                and abs(r["budget"] - float(OP)) < 1e-12):
            gk = "out" if compiled_status.get(r["rule_id"]) == "unanalyzed_outside_grammar" else "in"
            grp[gk].append(r)
    for tag, key in (("In", "in"), ("Out", "out")):
        v = grp[key]
        out.append(mac(f"Excl{tag}N", len(v)))
        out.append(mac(f"Excl{tag}Nondom",
                       f"{sum(1 for x in v if x['structural_noncollapse']) / len(v):.3f}"))
        out.append(mac(f"Excl{tag}Fires",
                       f"{sum(1 for x in v if x['screen_fires']) / len(v):.3f}"))
    assert (sum(1 for x in grp["out"] if x["screen_fires"]) / len(grp["out"])
            < sum(1 for x in grp["in"] if x["screen_fires"]) / len(grp["in"])), \
        "exclusion-audit direction changed: the paper's conservativeness claim would flip"

    # ---- the certificate Theorem 2's SHIP rule actually names
    dm = ec["domains"]
    out.append(mac("EcertDeltaEv", f"{ec['config']['delta_ev']:.2f}"))
    out.append(mac("EcertBudget", f"{ec['config']['budget']:.2f}"))
    out.append(mac("EcertEpisodes", dm["synthetic"]["n_episodes"]))
    for lab, d0 in (("Synth", "synthetic"), ("Cmap", "real"),
                    ("Warn", "gridworld"), ("Budget", "budget")):
        v = dm[d0]
        out.append(mac(f"Ecert{lab}Set",
                       f"{v['arms']['corset']['n_certified_at_budget']}/{v['arms']['corset']['n_seeds']}"))
        out.append(mac(f"Ecert{lab}Single",
                       f"{v['arms']['single']['n_certified_at_budget']}/{v['arms']['single']['n_seeds']}"))
        out.append(mac(f"Ecert{lab}B", f"{v['B']:.1f}"))
    out.append(mac("EcertDomainsCertifying",
                   ec["decision_D2"]["median_certifies_in_domains"]))
    assert a["tiesafe_ok_all"], "P0-D: face-equivalence check failed on some cell"
    out.append(mac("ExactLpGap", f"{a['max_lp_gap']:.0e}"))

    # ---- P0-D screen tie-safety
    dis = {d: nn["aggregate"][d]["label_disagreements"] for d in nn["aggregate"]}
    out.append(mac("ScreenDisagreeOp", dis[OP]))
    out.append(mac("ScreenDisagreeMax", max(dis.values())))
    out.append(mac("ScreenDisagreeBudget",
                   max(dis, key=lambda d: dis[d]) if max(dis.values()) else "--"))
    out.append(mac("ScreenMs", int(round(sc["ms_per_rule"]))))

    # ---- prices
    out.append(mac("PriceKyvFullLo", pct(k["price"]["rel_min_positive"], 0)))
    out.append(mac("PriceKyvFullHi", pct(k["price"]["rel_max"], 0)))
    out.append(mac("PriceKyvFullMed", pct(k["price"]["rel_median_positive"], 0)))
    out.append(mac("PriceMonFullLo", pct(p["price"]["rel_min_positive"], 0)))
    out.append(mac("PriceMonFullHi", pct(p["price"]["rel_max"], 0)))
    out.append(mac("PriceMonFullMed", pct(p["price"]["rel_median_positive"], 0)))
    out.append(mac("PricePositivePools",
                   p["price"]["n_positive"] + k["price"]["n_positive"]))
    out.append(mac("PriceCompiledMed", pct(a["median_rpoa"])))

    # ---- antichain reduction
    out.append(mac("AntichainMed", p["antichains_median"]))
    out.append(mac("AntichainMax", p["antichains_max"]))
    out.append(mac("AntichainMedKyv", k["antichains_median"]))
    out.append(mac("AntichainMaxKyv", k["antichains_max"]))
    out.append(mac("AntichainSpeedup", int(round(p["reduction_median"]))))
    out.append(mac("AntichainVerified", p["verified_n"] + k["verified_n"]))

    # ---- worked rule: ONE object (source-grounded NodeCPUHighUsage)
    wop = worked["budgets"][OP]
    src = next(i for i in suite["instances"] if i["uid"] == "NodeCPUHighUsage")
    out.append(mac("CpuThetaHi", f"{max(r['theta'] for r in src['readings']):.0f}"))
    out.append(mac("CpuThetaLo", f"{min(r['theta'] for r in src['readings']):.0f}"))
    out.append(mac("CpuForMin", f"{max(r['for_s'] for r in src['readings'])/60:.0f}"))
    out.append(mac("CpuClasses", wpool["n_classes"]))
    out.append(mac("CpuAntichains", wpool["n_antichains"]))
    out.append(mac("CpuSubsets", f"{2 ** wpool['n_classes']:,}".replace(",", "{,}")))
    out.append(mac("CpuNu", f"{src['budgets'][OP]['nu_pi']:.4f}"))
    out.append(mac("CpuPrice", pct(wop["rpoa"], 0)))
    out.append(mac("CpuWorstRatio",
                   f"{max(s['best_worst'] for s in wop['singletons'])/0.05:.1f}"))

    # ---- W4 registered grids
    fa = w4["arms"]["A"]
    out.append(mac("NondomMonA", f"{fa['prometheus']['non_dominance_rate']:.3f}"))
    out.append(mac("NondomKyvA", f"{fa['kyverno']['non_dominance_rate']:.3f}"))
    out.append(mac("NondomMonB", f"{w4['arms']['B']['prometheus']['non_dominance_rate']:.3f}"))
    out.append(mac("NondomMonPool", f"{w4['frozen_rates']['prometheus']:.3f}"))
    out.append(mac("NondomKyvPool", f"{w4['frozen_rates']['kyverno']:.3f}"))
    st = fa["prometheus"]["strata"]
    out.append(mac("SingleAxisMax",
                   f"{max(v['frac_non_dominated'] for kk, v in st.items() if kk.startswith('pure_')):.3f}"))
    out.append(mac("ThreshDurRate", f"{st['threshold+duration']['frac_non_dominated']:.3f}"))

    # ---- certificates (expected-cost certificate, PER SEED, at d)
    dom = dc["domains"]

    def cert(name, arm, thr="010"):
        a = dom[name]["arms"][arm]
        return f"{a['n_seeds_certified_at_' + thr]}/{a['n_seeds']}"

    for lab, dm in (("Synth", "synthetic"), ("Cmap", "real"),
                    ("Warn", "gridworld"), ("Budget", "budget")):
        out.append(mac(f"Cert{lab}Single", cert(dm, "single")))
        out.append(mac(f"Cert{lab}Set", cert(dm, "corset")))
        out.append(mac(f"Cert{lab}SingleTight", cert(dm, "single", "005")))
        out.append(mac(f"Cert{lab}SetTight", cert(dm, "corset", "005")))
    out.append(mac("CertThreshold", "0.10"))
    out.append(mac("CertTightThreshold", f"{dc['config']['delta']:.2f}"))
    out.append(mac("CertEpisodes", dom["synthetic"]["n_episodes_per_seed"]))

    # episode-violation diagnostics (NOT the certificate): per-seed mean rate
    rates_single = [dom[d]["arms"]["single"]["seed_mean_rate"] for d in dom]
    rates_set = [dom[d]["arms"]["corset"]["seed_mean_rate"] for d in dom]
    out.append(mac("EpisodeSingleLo", pct(min(rates_single), 0)))
    out.append(mac("EpisodeSingleHi", pct(max(rates_single), 0)))
    out.append(mac("EpisodeSetHi", pct(max(rates_set), 0)))

    # ---- learned bridge (descriptive)
    d7 = w7["descriptive"]
    out.append(mac("WsevenCells", d7["set_worst_exact_ok"].split("/")[1]))
    out.append(mac("WsevenCompetent", d7["single_own_exact_ok"]))
    out.append(mac("WsevenSetInBudget", d7["set_worst_exact_ok"]))
    out.append(mac("WsevenHiddenGap", f"{d7['hidden_gap_median']:.3f}"))
    out.append(mac("WsevenSetWorst", f"{d7['set_worst_median']:.3f}"))
    out.append(mac("WsevenGateExact", w7["exact_optimum_passes_gate"]))
    out.append(mac("WsevenN", w7["n_instances"]))

    # ---- secondary-instrument negatives
    raw_vac = sum(1 for dm, v in shadow["domains"].items()
                  if v["t1_exact_minimax"]["minimax"] and
                  next(r for r in v["t1_exact_minimax"]["minimax"]
                       if abs(r["delta"] - 0.05) < 1e-9)["old_thm4_lower_bound"] <= 0)
    out.append(mac("VacuousDomainsRaw", raw_vac))
    out.append(mac("ClosedFormOvershoot",
                   f"{sgx['closed_over_realized']['median']:.1f}$\\times$"))

    # ---- semantic accounting macros (each names its own denominator)
    out.append(mac("AccGenVfour", f"{acc_rows[1]['value']:.3f}"))
    out.append(mac("AccGenVfourN", acc_rows[1]["n"]))
    out.append(mac("AccRetVfour", f"{acc_rows[2]['value']:.3f}"))
    out.append(mac("AccEteWhole", f"{acc_rows[3]['value']:.3f}"))
    out.append(mac("AccEteWholeN", acc_rows[3]["n"]))
    out.append(mac("AccLicRetVsix", f"{acc_rows[4]['value']:.3f}"))
    out.append(mac("AccLicRetVsixN", acc_rows[4]["n"]))
    out.append(mac("AccComposedVfour", f"{composed:.3f}"))
    out.append(mac("ReplCov", pct(acc_rows[5]["value"])))
    out.append(mac("ReplCovN", acc_rows[5]["n"]))

    write("gen_unified_numbers.tex", "".join(out))


if __name__ == "__main__":
    rows, comp = semantic_accounting()
    headline(rows, comp)
