"""Emit generated/gen_live_agent.tex (two-row table) and gen_live.tex (macros) for the live
service-agent check of Appendix D.1 from demo/logs/eval_summary.json (the archived live
evaluation: 50 paired sessions per condition, real billed posts to a sandboxed endpoint).
Every printed value is read from the archive and asserted; nothing is typed by hand."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(ROOT, "paper")); GEN = os.path.join(PAPER, "generated")
s = json.load(open(os.path.join(ROOT, "experiments", "live_agent", "logs", "eval_summary.json")))
single, corset = s["conditions"]["single"], s["conditions"]["corset"]
n = s["episodes_per_condition"]
assert n == 50 and single["n_episodes"] == n and corset["n_episodes"] == n, (n, single["n_episodes"], corset["n_episodes"])
ks = sorted(int(k.split(">=")[1]) for k in single["retained_violation_rate"])          # retained burst-cap readings
assert ks == [3, 4, 5, 6, 8] and single["retained_violation_rate"]["psi_calls>=5"]["rate"] == 0.0
tight = [k for k in ks if k < 5]                                                        # readings tighter than the supplied k=5
rate = lambda c, k: c["retained_violation_rate"][f"psi_calls>={k}"]["rate"]
single_tight = max(rate(single, k) for k in tight); corset_tight = max(rate(corset, k) for k in ks)
assert single_tight == 1.0 and all(rate(single, k) == 1.0 for k in tight)              # violates every tighter retained reading in every session
assert corset_tight == 0.0 and rate(corset, 5) == 0.0                                  # the retained-set guard violates nothing
assert single["task_value_mean"] > corset["task_value_mean"]
# session length: every logged session has the same number of posting opportunities
window = {len(json.loads(l)["rewards"]) for f in ("eval_single.jsonl", "eval_corset.jsonl")
          for l in open(os.path.join(ROOT, "experiments", "live_agent", "logs", f)) if l.strip()}
assert len(window) == 1, window
window = window.pop()                           # the set guard pays in task value
mac = lambda k, v: f"\\newcommand{{\\{k}}}{{{v}}}"
M = [mac("LvSessions", n), mac("LvModel", {"gpt-4o-mini": "GPT-4o-mini"}.get(s["model"], s["model"])),
     mac("LvRetainedKs", ",".join(str(k) for k in ks)), mac("LvTightKs", ",".join(str(k) for k in tight)),
     mac("LvSingleValue", f"{single['task_value_mean']:.2f}"), mac("LvSetValue", f"{corset['task_value_mean']:.2f}"),
     mac("LvSingleTightViol", f"{single_tight:.2f}"), mac("LvSetTightViol", f"{corset_tight:.2f}"),
     mac("LvSingleOwnViol", f"{rate(single, 5):.2f}"), mac("LvSetOwnViol", f"{rate(corset, 5):.2f}"),
     mac("LvSinglePosts", f"{single['n_paid_mean']:g}"), mac("LvSetPosts", f"{corset['n_paid_mean']:g}"),
     mac("LvWindow", str(window))]
H = "% AUTO-GENERATED by paper/final/make_gen_live.py from demo/logs/eval_summary.json -- do not edit\n"
rows = (f"Single reading ($k{{=}}5$) & ${single['task_value_mean']:.2f}$ & ${single_tight:.2f}$ & ${rate(single, 5):.2f}$ \\\\\n"
        f"Retained-set guard ($k\\in\\{{{','.join(str(k) for k in ks)}\\}}$) & ${corset['task_value_mean']:.2f}$ & ${corset_tight:.2f}$ & ${rate(corset, 5):.2f}$ \\\\\n")
open(os.path.join(GEN, "gen_live_agent.tex"), "w").write(H + rows)
open(os.path.join(GEN, "gen_live.tex"), "w").write(H + "\n".join(M) + "\n")
print(rows); print("\n".join(M))
