"""Generate the LaTeX table bodies that the paper still reads from the learning-arm and
control-suite archives:

  gen_control_suite.tex / gen_control_suite_caption.tex   the 28 compiled rules (results/conformal/benchmark_sg/control_suite.json)
  gen_bind.tex                                            exact non-nested value screen per geometry (results/e2e/exact_nonnested.json);
                                                          joined with gen_control_suite.tex by make_gen_csuite_bind.py into Table 7
  gen_dsrl.tex / gen_dsrl_seedinfo.tex / gen_dsrlcount.tex  the released offline safe-RL learners on DSRL/OSRL (results/dsrl/), Table 18

Missing sources emit a visible PENDING row so an un-finished build is detectable in the compiled PDF.

Run:  python3 scripts/paper/make_corset_tables.py
"""
from __future__ import annotations

import glob
import json
import re
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GEN = os.path.join(ROOT, "paper", "generated")
os.makedirs(GEN, exist_ok=True)

DOM_LABEL = {
    "synthetic": "Maint.\\ (synthetic)",
    "real": "Maint.\\ (C-MAPSS)",
    "gridworld": "Warning-window",
    "budget": "Budget agent",
}


def newest(dirname):
    files = glob.glob(os.path.join(ROOT, "results/conformal", dirname, "experiments_*.json"))
    return max(files, key=os.path.getmtime) if files else None


def load(dirname):
    f = newest(dirname)
    return json.load(open(f)) if f else None


def fmt(pair, nd=3):
    if pair is None or pair[0] is None:
        return "--"
    return f"${pair[0]:.{nd}f}\\pm{pair[1]:.{nd}f}$"


def fmt1(pair):
    return fmt(pair, nd=1)


def pfmt(p):
    if p is None:
        return "--"
    if p <= 0:
        return "$0$"
    e = math.floor(math.log10(p))
    m = p / 10 ** e
    if abs(m - 1.0) < 0.05:
        return f"$10^{{{e}}}$"
    return f"${m:.1f}{{\\times}}10^{{{e}}}$"


def write(name, text):
    path = os.path.join(GEN, name)
    with open(path, "w") as fh:
        fh.write("% AUTO-GENERATED by paper/make_corset_tables.py -- do not edit\n")
        fh.write(text)
    print(f"wrote {path}")


def pending(name, msg):
    write(name, f"\\multicolumn{{2}}{{l}}{{\\textbf{{PENDING: {msg}}}}}\\\\\n")




def _dedup_runs(records, key_fields):
    """Keep exactly one record per key so a seed present in more than one
    results dir (base sweep + 20-seed top-up, or a straggler resubmit) is NOT
    counted twice in mean/std. Deterministic: callers sort the file order, so
    last-write-wins is stable (duplicates are the same computation -> same
    values). Records missing a key field are dropped."""
    out = {}
    for r in records:
        try:
            k = tuple(r[f] for f in key_fields)
        except KeyError:
            continue
        out[k] = r
    return list(out.values())


def gen_dsrl():
    import statistics as st
    # The 20-seed primary arm (W21/W23) accumulated across SEVERAL cluster rounds:
    # the skip-guard only re-ran not-yet-both-ok cells, so a given (task,learner,
    # seed) lands in exactly one of topup/topup2/topup4/ext_p20seed. ALL of them
    # must be read or seeds are silently dropped. _dedup_runs removes the (large)
    # cross-round overlap, so adding dirs can only ADD seeds, never double-count.
    base_dirs = ["results/dsrl/sweep", "results/dsrl/sweep_caps",
                 "results/dsrl/sweep_cdt", "results/dsrl/sweep_coptidice",
                 "results/dsrl/ext_ext",
                 "results/dsrl/ext_p20seed", "results/dsrl/topup",
                 "results/dsrl/topup2", "results/dsrl/topup4"]
    recs = []
    for d in base_dirs:
        for f in sorted(glob.glob(os.path.join(ROOT, d, "**", "dsrl_sweep_*.json"),
                                  recursive=True)):
            blob = json.load(open(f))
            for r in blob.get("runs", []):
                if r.get("status") == "ok" and tuple(r.get("U", [])) == (10, 20, 40):
                    recs.append(r)
    mp = []
    for f in sorted(glob.glob(os.path.join(ROOT, "results/dsrl", "ext_mp20", "**",
                                           "dsrl_sweep_*.json"), recursive=True)):
        blob = json.load(open(f))
        for r in blob.get("runs", []):
            if (r.get("status") == "ok" and r.get("reading") == "single"
                    and r.get("target_cost") == 20):
                mp.append(r)
    # dedup by seed so base+top-up (or straggler resubmit) never double-count
    recs = _dedup_runs(recs, ("task", "learner", "reading", "seed"))
    mp = _dedup_runs(mp, ("task", "learner", "seed"))
    if not recs:
        return pending("gen_dsrl.tex", "no DSRL records found")

    tasks = ["OfflineAntRun-v0", "OfflineBallCircle-v0", "OfflineCarCircle-v0",
             "OfflineCarRun-v0", "OfflineDroneCircle-v0"]
    tlabel = {t: t.replace("Offline", "").replace("-v0", "") for t in tasks}
    learners = ["bcql", "cpq", "coptidice", "cdt", "caps"]
    llabel = {"bcql": "BCQ-Lagrangian", "cpq": "CPQ", "coptidice": "COptiDICE",
              "cdt": "CDT", "caps": "CAPS"}

    def cell(pool, task, learner, reading):
        rs = [r for r in pool if r["task"] == task and r["learner"] == learner
              and r["reading"] == reading]
        if not rs:
            return None
        rew = [r["normalized_reward"] for r in rs]
        cst = [r["worst_retained_normalized_cost"] for r in rs]
        return (st.mean(rew), st.pstdev(rew), st.mean(cst), st.pstdev(cst), len(rs))

    have_mp = bool(mp)
    rows, viol_cells, improved = [], 0, 0
    mp_viol, mp_overlap, exceptions = 0, 0, []
    n_cells = 0                                # task-learner cells reported in the table
    for t in tasks:
        for ln in learners:
            s = cell(recs, t, ln, "single")
            a = cell(recs, t, ln, "saorl")
            m = cell(mp, t, ln, "single") if have_mp else None
            if s is None or a is None:
                continue
            n_cells += 1
            if m and m[2] > 1.0:
                mp_viol += 1               # c=20 most-plausible violates strictest
            if s[2] > 1.0:
                viol_cells += 1            # c=40 loosest single violates
                if m and m[2] > 1.0:
                    mp_overlap += 1        # ...and c=20 also violates this cell
                if a[2] < s[2]:
                    improved += 1          # CORSET lowers the worst-retained cost
                else:
                    exceptions.append((tlabel[t], llabel[ln], s[2], a[2]))
            num = lambda v: f"{v:.2f}".replace("-", "$-$", 1)   # true minus sign for negatives
            mp_rew = f"{num(m[0])}\\,$\\pm$\\,{m[1]:.2f}" if m else "--"
            mp_cst = f"{num(m[2])}\\,$\\pm$\\,{m[3]:.2f}" if m else "--"
            rows.append(
                f"{tlabel[t]} & {llabel[ln]} & "
                f"{num(s[0])}\\,$\\pm$\\,{s[1]:.2f} & {mp_rew} & "
                f"{num(a[0])}\\,$\\pm$\\,{a[1]:.2f} & "
                f"{num(s[2])}\\,$\\pm$\\,{s[3]:.2f} & {mp_cst} & "
                f"{num(a[2])}\\,$\\pm$\\,{a[3]:.2f} \\\\\n")
        rows.append("\\addlinespace\n" if t != tasks[-1] else "")
    write("gen_dsrl.tex", "".join(rows))

    # ---- data-driven seed-count labels (so no hand-edited "5 seeds" goes stale
    #      after the 20-seed merge; the caption \input's these macros) ----
    def _seed_text(pool, readings):
        percell = []
        for t in tasks:
            for ln in learners:
                for rd in readings:
                    ss = {r["seed"] for r in pool if r["task"] == t
                          and r["learner"] == ln and r["reading"] == rd}
                    if ss:
                        percell.append(len(ss))
        distinct = sorted({r["seed"] for r in pool})
        nd = len(distinct)
        if not percell:
            return "unavailable", nd
        lo, hi = min(percell), max(percell)
        if lo == hi:
            return f"{hi} seeds", nd
        return f"{lo}--{hi} seeds per cell ({nd} distinct)", nd

    main_txt, main_nd = _seed_text(recs, ("single", "saorl"))
    mp_txt, _mp_nd = _seed_text(mp, ("single",))
    # exception cells (violate under c=40 but CORSET does not lower the cost) as a
    # ready-to-typeset LaTeX list, so the caption never names stale cells/values.
    exc_str = ", ".join(
        f"{ln} on {t} (${s:.2f}{{\\to}}{a:.2f}$)"
        for t, ln, s, a in exceptions) or "none"
    write("gen_dsrl_seedinfo.tex",
          f"\\def\\dsrlseedmain{{{main_txt}}}\n"
          f"\\def\\dsrlseedmp{{{mp_txt}}}\n"
          f"\\def\\dsrlcells{{{n_cells}}}\n"
          f"\\def\\dsrlviol{{{viol_cells}}}\n"
          f"\\def\\dsrlimproved{{{improved}}}\n"
          f"\\def\\dsrlmpviol{{{mp_viol}}}\n"
          f"\\def\\dsrlmpoverlap{{{mp_overlap}}}\n"
          f"\\def\\dsrlnexc{{{len(exceptions)}}}\n"
          f"\\def\\dsrlexc{{{exc_str}}}\n")
    nsee = sorted({r["seed"] for r in recs})
    print(f"  [dsrl] main={main_txt} (distinct={main_nd} seeds={nsee}) "
          f"mp={mp_txt} viol={viol_cells} improved={improved} "
          f"mp_viol={mp_viol} mp_overlap={mp_overlap} exc={len(exceptions)} "
          f"mp20_records={len(mp)}")


def gen_control_suite():
    f = os.path.join(ROOT, "results/conformal", "benchmark_sg",
                     "control_suite.json")
    if not os.path.exists(f):
        return pending("gen_control_suite.tex", "control suite not run")
    r = json.load(open(f))
    import numpy as np
    from collections import defaultdict
    by = defaultdict(list)
    for i in r["instances"]:
        by[i["geometry"]].append(i)
    rows = []
    for g in sorted(by):
        insts = by[g]
        ex = insts[0]
        rd = ", ".join(f"($\\theta{{=}}{x['theta']:g}$, {x['for_s']:g}\\,s)"
                       for x in ex["readings"])
        b = ex["budgets"]["0.01"]
        orc = b["oracle_singleton"]
        nofeas = sum(1 for i in insts
                     if i["budgets"]["0.01"]["no_singleton_fullset_feasible"])
        rows.append(
            f"{g} & {len(insts)} & {rd} & ${b['nu_pi']:.4f}$ & "
            f"{nofeas}/{len(insts)} & ${orc['worst']/0.01:.2f}d$ "
            "\\\\\n")
    write("gen_control_suite.tex", "".join(rows))
    p = r["primary_endpoint"]
    nofeas_n = sum(1 for i in r["instances"]
                   if i["budgets"]["0.01"]["no_singleton_fullset_feasible"])
    assert (p["n_instances"], p["n_distinct_geometries"]) == (17, 3), p
    assert p["nu_pi_positive_frac"] == 1.0, p
    assert nofeas_n == 5, nofeas_n
    write("gen_control_suite_caption.tex",
          f"\\newcommand{{\\csuiteN}}{{{p['n_instances']}}}\n"
          f"\\newcommand{{\\csuiteGeoms}}{{{p['n_distinct_geometries']}}}\n"
          f"\\newcommand{{\\csuiteNoFeas}}{{{sum(1 for i in r['instances'] if i['budgets']['0.01']['no_singleton_fullset_feasible'])}}}\n"
          f"\\newcommand{{\\csuiteNuPos}}{{{int(round(p['nu_pi_positive_frac']*p['n_instances']))}}}\n")


def gen_bind():
    """WHEN does set defense bind on real rules? (review #32, item b)

    Rather than reporting 5/17 at one budget and 1/17 at another, this
    characterizes the requirement per instance: an instance needs set defense at
    budget d exactly when no singleton gets its worst-reading cost to d. On this
    suite that is a function of the cap geometry, and it is monotone in d."""
    f = os.path.join(ROOT, "results/conformal", "benchmark_sg", "control_suite.json")
    if not os.path.exists(f):
        return pending("gen_bind.tex", "control suite missing")
    d = json.load(open(f))
    _vf = os.path.join(ROOT, "results/e2e", "exact_nonnested.json")
    if not os.path.exists(_vf):
        return pending("gen_bind.tex", "exact_nonnested (value screen) not run")
    _val = {r["uid"]: r["budgets"] for r in json.load(open(_vf))["instances"]}
    grid = ["0.005", "0.01", "0.02", "0.05"]
    by_geo = {}
    prof_all = []
    for ins in d["instances"]:
        # P0-D: the shipped verdict must be the tie-safe VALUE screen
        # (min_psi V_psi > V_U), not a predicate read off one representative
        # singleton optimum.  Values come from the archived exact study.
        prof = [bool(_val[ins["uid"]][g]["fires_value"]) for g in grid]
        prof_all.append(prof)
        by_geo.setdefault(ins["geometry"], []).append(prof)
    # the requirement must be monotone in the budget, else the story is wrong
    assert all(all(p[i] >= p[i + 1] for i in range(len(grid) - 1))
               for p in prof_all), "non-monotone in budget"
    # and constant within a geometry, which is the finding
    for g, ps in by_geo.items():
        assert all(p == ps[0] for p in ps), f"geometry {g} not homogeneous"
    rows = []
    for geo in sorted(by_geo, key=lambda g: -sum(by_geo[g][0])):
        ps = by_geo[geo][0]
        rows.append(f"\\texttt{{{geo}}} & {len(by_geo[geo])} & "
                    + " & ".join("\\cmark" if x else "\\xmark" for x in ps)
                    + " \\\\\n")
    write("gen_bind.tex", "".join(rows))
    n_always = sum(len(v) for g, v in by_geo.items() if all(v[0]))
    n_never = sum(len(v) for g, v in by_geo.items() if not any(v[0]))


def gen_dsrlcount():
    """The DSRL run count, computed from the release rather than hardcoded.

    The reproducibility statement asserted '1,075 DSRL runs' as a literal, in
    the sentence claiming nothing is hand-transcribed. Three independent counts
    disagreed (1,014 archived JSON files here, ~1,045 by one dedup, 1,075 as
    written), because 'run' was never pinned to a definition. This pins it to
    something a reader can check against whatever ships: per-run JSON files
    under results/dsrl/."""
    import glob as _glob
    d = os.path.join(ROOT, "results/dsrl")
    if not os.path.isdir(d):
        return pending("gen_dsrlcount.tex", "results/dsrl missing")
    n = len(_glob.glob(os.path.join(d, "**", "*.json"), recursive=True))
    assert n > 0, n
    write("gen_dsrlcount.tex",
          f"\\newcommand{{\\dsrlRunFiles}}{{{n:,}}}\n".replace(",", "{,}"))


if __name__ == "__main__":
    gen_control_suite()
    gen_bind()
    gen_dsrl()
    gen_dsrlcount()
