#!/usr/bin/env python3
"""Emit generated/gen_v52.tex (macros, prefix \Vc...) and gen_v52_table_compact.tex from results/e2e/scope_agent_check.json:
the checked deployment route (empirical-Bernstein CHECK) on every learned policy of the agent-service experiment
(REGISTRATION_V52).  Directions the manuscript states are asserted before writing."""
import json, os
import numpy as np
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PAPER = os.environ.get("ARROW_PAPER_DIR", os.path.join(ROOT, "paper")); GEN = os.path.join(PAPER, "generated")
d = json.load(open(os.path.join(ROOT, "results/e2e", "scope_agent_check.json"))); rows = d["rows"]
H = "% AUTO-GENERATED by scripts/paper/make_gen_v52.py -- do not edit\n"
LNAME = {"fqi": "BCQ-FQI-Lagrangian", "cpq": "CPQ", "pid": "PID-Lagrangian", "cql": "CQL-Lagrangian (neural)", "caps": "CAPS", "o3srl": "O3SRL"}; LKEY = {"fqi": "Fqi", "cpq": "Cpq", "pid": "Pid", "cql": "Cql", "caps": "Caps", "o3srl": "Osrl"}
_learners = sorted({r["learner"] for r in rows}); TABLE_ORDER = [l for l in ("fqi", "pid", "o3srl", "cpq", "caps", "cql") if l in _learners]
def pct(x, k=1): return f"{100*x:.{k}f}\\%"
def arm_of(r): return "arrow" if r["is_arrow"] else ("surrogate" if r["arm"] == "surrogate" else "wrong")
M = []
def mac(n, v): M.append(f"\\newcommand{{\\{n}}}{{{v}}}")
mac("VcNEv", f"{d['n_ev']:,}".replace(",", "{,}")); mac("VcDeltaEv", f"{d['delta_ev']:g}"); mac("VcPolicies", f"{len(rows):,}".replace(",", "{,}"))
unsafe_dep = sum(1 for r in rows if r["ship"] and not r["safe"]); assert unsafe_dep == 0; mac("VcUnsafeDeployed", unsafe_dep)
wrong_unsafe = [r for r in rows if arm_of(r) == "wrong" and not r["safe"]]; assert all(not r["ship"] for r in wrong_unsafe)
mac("VcWrongUnsafe", f"{len(wrong_unsafe):,}".replace(",", "{,}")); mac("VcWrongUnsafeRejected", sum(1 for r in wrong_unsafe if not r["ship"]))
pass_arrow = []; dep_arrow = []
for l in TABLE_ORDER:
    for n in sorted({r["n"] for r in rows if r["learner"] == l}):
        for arm in ("arrow", "surrogate", "wrong"):
            sel = [r for r in rows if r["learner"] == l and r["n"] == n and arm_of(r) == arm]; dep = [r for r in sel if r["ship"]]
            ret = float(np.mean([r["ret_frac"] for r in sel])); ps = float(np.mean([r["ship"] for r in sel]))
            dret = float(np.mean([r["ret_frac"] for r in dep])) if dep else None; srej = sum(1 for r in sel if r["safe"] and not r["ship"])
            unsafe = sum(1 for r in sel if not r["safe"])
            label = {"arrow": "\\method{} reading", "surrogate": "single-cost surrogate", "wrong": "wrong reading"}[arm]
            assert len(sel) == (180 if arm == "wrong" else 90)
            if n == 20000:
                key = f"Vc{LKEY[l]}" + {"arrow": "Arrow", "surrogate": "Surr", "wrong": "Wrong"}[arm]
                mac(key + "Pass", pct(ps, 0)); mac(key + "Ret", pct(ret)); mac(key + "Unsafe", unsafe); mac(key + "SafeRejected", srej)
                if dret is not None: mac(key + "DepRet", pct(dret))
                if arm == "arrow": pass_arrow.append(ps); dep_arrow.append(dret)
mac("VcArmPolicies", len([r for r in rows if r["learner"] == "fqi" and r["n"] == 20000 and arm_of(r) == "arrow"]))
# the n = 2,000 ARROW and surrogate policies of the tabular learners, not listed in the compact table
small = [r for r in rows if r["n"] == 2000 and arm_of(r) in ("arrow", "surrogate")]
small_arrow = [r for r in small if arm_of(r) == "arrow"]; small_surr = [r for r in small if arm_of(r) == "surrogate"]
n_tab = len([l for l in TABLE_ORDER if l != "cql"])
assert len(small) == 180 * n_tab and len(small_arrow) == len(small_surr) == 90 * n_tab and all(r["learner"] != "cql" for r in small)
sa_unsafe = [r for r in small_arrow if not r["safe"]]; assert sa_unsafe and all(not r["ship"] for r in sa_unsafe)
mac("VcSmallSurrUnsafe", sum(1 for r in small_surr if not r["safe"])); mac("VcSmallSurrRejected", sum(1 for r in small_surr if not r["ship"]))
mac("VcSmallLearners", n_tab)
mac("VcSmallPolicies", len(small)); mac("VcSmallArrowN", len(small_arrow)); mac("VcSmallArrowUnsafe", len(sa_unsafe)); mac("VcSmallSurrN", len(small_surr))
mac("VcArrowPassLo", pct(min(pass_arrow), 0)); mac("VcArrowPassHi", pct(max(pass_arrow), 0)); mac("VcArrowDepRetLo", pct(min(dep_arrow))); mac("VcArrowDepRetHi", pct(max(dep_arrow)))
cql_arrow = [r for r in rows if r["learner"] == "cql" and arm_of(r) == "arrow"]
assert sum(1 for r in cql_arrow if not r["safe"]) > 0 and all(not r["ship"] for r in cql_arrow if not r["safe"])   # the unsafe CQL runs are all rejected
mac("VcCqlArrowUnsafeRuns", sum(1 for r in cql_arrow if not r["safe"]))
# safe-but-rejected reading policies at the largest n: policies within the budget that the bound could not certify
srej_big = [r for r in rows if r["n"] == 20000 and arm_of(r) == "arrow" and r["safe"] and not r["ship"]]
mac("VcArrowSafeRejected", len(srej_big)); mac("VcArrowRuns", len([r for r in rows if r["n"] == 20000 and arm_of(r) == "arrow"]))
mac("VcArrowSafeRejectedMaxCost", pct(max((r["true_max_rate_over_d"] for r in srej_big), default=0.0), 1))   # as a share of d
full_pass = [LNAME[l] for l in TABLE_ORDER if float(np.mean([r["ship"] for r in rows if r["learner"] == l and r["n"] == 20000 and arm_of(r) == "arrow"])) == 1.0]
mac("VcArrowFullPassLearners", ", ".join(full_pass) if full_pass else "none"); mac("VcArrowFullPassCount", len(full_pass))
# ---- compact table: one row per learner at n = 20,000 (unsafe and pass counts under each training cost, unsafe deployed),
# plus one stress-test row pooling every wrong-reading policy
C = []
for l in TABLE_ORDER:
    cells = []
    for arm in ("arrow", "surrogate"):
        sel = [r for r in rows if r["learner"] == l and r["n"] == 20000 and arm_of(r) == arm]
        cells += [str(sum(1 for r in sel if not r["safe"])), pct(float(np.mean([r["ship"] for r in sel])), 0)]
    both = [r for r in rows if r["learner"] == l and r["n"] == 20000 and arm_of(r) in ("arrow", "surrogate")]
    C.append(f"{LNAME[l]} & " + " & ".join(cells) + f" & {sum(1 for r in both if r['ship'] and not r['safe'])} \\\\")
wrong = [r for r in rows if arm_of(r) == "wrong"]; wdep = [r for r in wrong if r["ship"]]
C.append("\\midrule")
wrong_unsafe_n = f"{sum(1 for r in wrong if not r['safe']):,}".replace(",", "{,}")
C.append(f"wrong readings, all learners ({len(wrong):,} policies) & {wrong_unsafe_n} & {pct(float(np.mean([r['ship'] for r in wrong])),0)} & --- & --- & {sum(1 for r in wdep if not r['safe'])} \\\\")
open(os.path.join(GEN, "gen_v52_table_compact.tex"), "w").write(H + "\n".join(C) + "\n")
open(os.path.join(GEN, "gen_v52.tex"), "w").write(H + "\n".join(M) + "\n")
print("macros", len(M)); print(open(os.path.join(GEN, "gen_v52_table_compact.tex")).read()[:600])
