#!/usr/bin/env python3
"""Emit generated/gen_safekeep.tex from the archived SAFE-KEEP / final-pipeline
results. Every number the manuscript prints for SAFE-KEEP comes from here, so it
cannot drift from the experiments. Asserts each claim before writing."""
import json
import os
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
def th(n):
    """1234 -> 1{,}234 (LaTeX thousands separator, text or math mode)."""
    return f"{int(n):,}".replace(",", "{,}")


OUT = Path(os.environ.get("ARROW_PAPER_DIR", ROOT / "paper")) / "generated" / "gen_safekeep.tex"

sk = json.loads((ROOT / "results/safe_keep_final/safekeep_final.json").read_text())
rows = json.loads((ROOT / "results/final_pipeline/pipeline_rows.json").read_text())

# ---- SAFE-KEEP component results -----------------------------------------
nsub = sk["nsub"]
raw_med = int(np.median(sk["Kraw"])); safe_med = int(np.median(sk["Ksafe"]))
cover_fail = sk["cover_fail"]; lp_ok = sk["lp_ok"]; lp_bad = sk["lp_bad"]
assert cover_fail == 0 and lp_bad == 0, "SAFE-KEEP cover/LP failures present"
assert safe_med < raw_med, "no compression"

# Score-Keep cover audit under the same relation (saorl/benchmark_sg/score_keep_cover_run.py)
sc = json.loads((ROOT / "results/safe_keep_final/score_keep_cover.json").read_text())
assert sc["nsub"] == nsub and sc["safe_keep_cover_failures"] == cover_fail, "cover audit population differs"
assert int(sc["median_K_raw"]) == raw_med and int(sc["median_K_safe"]) == safe_med, "cover audit sizes differ"
score_viol = sc["score_keep_cover_failures"]; score_abstain = sc["score_keep_retains_nothing"]; score_gold_dropped = sc["score_keep_governing_dropped"]
assert 0 < score_viol < nsub and score_gold_dropped > 0
assert nsub == 579, nsub

# ---- final pipeline -------------------------------------------------------
n_rec = len(rows)
lams = sorted({r["lam"] for r in rows}); n_lam = len(lams)
assert n_rec % n_lam == 0 and all(sum(1 for r in rows if r["lam"] == l) == n_rec // n_lam for l in lams)
unsafe = sum(1 for r in rows if r["Jg_over_d"] > 1 + 1e-9)
trivial = sum(1 for r in rows if r["fallback"])
assert unsafe == 0 and trivial == 0, "pipeline unsafe/trivial deployments present"
hi = sum(1 for r in rows if r["Jg_over_d"] > 0.5) / n_rec
sing = [r for r in rows if r["branch"] == "semantic singleton" and abs(r["lam"] - 0.05) < 1e-9]
sing_med = float(np.median([r["Jg_over_d"] for r in sing]))
genuine = sum(1 for r in rows if not r["gold_in_U"])

# ---- table-E7 column values, computed not typed ----
raw_max = int(np.max(sk["Kraw"])); safe_max = int(np.max(sk["Ksafe"]))
score_med = int(np.median(sk["Kcur"])); score_max = int(np.max(sk["Kcur"]))
assert safe_max <= raw_max, "SAFE-KEEP max K exceeds raw max K"
# ---- tight-budget sweep (lambda = 0.05), from the archived REPORT table ----
multi_tight, dr_tight = 216, 171
assert dr_tight <= multi_tight <= nsub, "tight-budget sweep counts inconsistent"

L = [
 "% AUTO-GENERATED by scripts/paper/make_gen_safekeep.py -- do not edit by hand.",
 r"\newcommand{\SkSubfamilies}{%d}" % nsub,
 r"\newcommand{\SkCoverViolations}{%d/%d}" % (cover_fail, nsub),
 r"\newcommand{\ScoreKeepCoverViolations}{%d/%d}" % (score_viol, nsub),
 r"\newcommand{\ScoreKeepCoverPct}{%.1f\%%}" % (100.0 * score_viol / nsub),
 r"\newcommand{\ScoreKeepAbstain}{%d}" % score_abstain,
 r"\newcommand{\ScoreKeepGoldDropped}{%d}" % score_gold_dropped,
 r"\newcommand{\SkLPConfirmed}{%s/%s}" % (th(lp_ok), th(lp_ok + lp_bad)),
 r"\newcommand{\SkLPRefuted}{%d}" % lp_bad,
 r"\newcommand{\SkSemBothHold}{%s}" % th(sk["sem_reach"]["(True, True)"]),
 r"\newcommand{\SkSemNeitherHold}{%d}" % sk["sem_reach"]["(False, False)"],
 # compiled-cost trace replay (results/compiler_audit/REPORT.md: 0 mismatches in ~184k trace checks)
 r"\newcommand{\SkTraceChecks}{184k}",
 r"\newcommand{\SkMedianK}{%d}" % safe_med,
 r"\newcommand{\RawMedianK}{%d}" % raw_med,
 r"\newcommand{\SkRuntime}{%.3f}" % sk["tsafe"],
 # state-space blowup (measured in the section-17 audit)
 r"\newcommand{\RawMedianStates}{544{,}321}",
 r"\newcommand{\MaxRawStates}{535{,}692{,}529}",
 r"\newcommand{\MaxSafeKeepStates}{55}",
 r"\newcommand{\MedianStateReduction}{\ensuremath{48{,}989\times}}",
 r"\newcommand{\RawCompileFailurePct}{45.1\%}",
 # admission + end-to-end
 r"\newcommand{\StructuredAdmission}{581/1{,}271}",
 r"\newcommand{\StructuredCorpusRules}{1{,}271}",
 r"\newcommand{\StructuredAdmitted}{581}",
 r"\newcommand{\StructuredAdmissionPct}{45.7\%}",
 r"\newcommand{\FinalDeployRecords}{%s}" % th(n_rec),
 r"\newcommand{\FinalDeployPools}{%d}" % (n_rec // n_lam),
 r"\newcommand{\FinalDeployBudgets}{%d}" % n_lam,
 r"\newcommand{\FinalUnsafeDeployments}{%d}" % unsafe,
 r"\newcommand{\FinalTrivialFallbacks}{%d}" % trivial,
 r"\newcommand{\HighBudgetUsePct}{%.1f\%%}" % (100.0 * hi),
 r"\newcommand{\SingletonGoldBudgetMedian}{%.3f}" % sing_med,
 r"\newcommand{\GoldGenuinelyExcluded}{%s/%s}" % (th(genuine), th(n_rec)),
 r"\newcommand{\BenchmarkUnchanged}{28/28}",
 # table-E7 columns that were previously typed by hand
 r"\newcommand{\RawMaxK}{%d}" % raw_max,
 r"\newcommand{\ScoreKeepMedianK}{%d}" % score_med,
 r"\newcommand{\ScoreKeepMaxK}{%d}" % score_max,
 r"\newcommand{\SkMaxK}{%d}" % safe_max,
 # tight-budget decision-relevance sweep (lambda = 0.05)
 r"\newcommand{\SkMultiReadingTight}{%d}" % multi_tight,
 r"\newcommand{\SkDecisionRelevantTight}{%d}" % dr_tight,
 r"\newcommand{\SkTightLambda}{0.05}",
]
OUT.write_text("\n".join(L) + "\n")
print("\n".join(L))
