"""Emit gen_v48_surrogate.tex, the exact surrogate-loss distribution by budget that Figure 3
(make_figs_appendix.py) plots, from results/e2e/collapse_readout.json. No numeral is typed.

Run: PYTHONPATH=. python3 scripts/paper/make_gen_v47_51_tables.py
"""
from __future__ import annotations
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
R = os.path.join(ROOT, "results/e2e")
G = os.path.join(os.environ.get("ARROW_PAPER_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "paper")), "generated")


def load(n):
    return json.load(open(os.path.join(R, n)))


def w(name, rows):
    with open(os.path.join(G, name), "w") as fh:
        fh.write("% AUTO-GENERATED by paper/final/make_gen_v47_51_tables.py -- do not edit\n" + "".join(rows))
    print(f"wrote {name} ({len(rows)} rows)")


def pc(x, nd=1):
    return "--" if x is None else f"${100*x:.{nd}f}\\%$"


def f2(x, nd=2):
    return "--" if x is None else f"${x:.{nd}f}$"


# ---- V48: exact surrogate-loss distribution by budget
cr = load("collapse_readout.json")
rows = []
for b, v in cr["a_exact_surrogate_loss_d0.05"]["by_budget"].items():
    rows.append(f"${b}$ & {v['n']} & {pc(v['median'],2)} & {pc(v['mean'],2)} & {pc(v['p90'],2)} & {pc(v['max'],2)} & "
                f"{v['n_above_1pct']} & {v['n_above_2pct']} & {v['n_above_5pct']} \\\\\n")
w("gen_v48_surrogate.tex", rows)

