"""Emit generated/gen_v47_51.tex: every numeral the 2026-09-06 revision adds
to arrow.tex, from the V47-V51 archives, each asserted against its source.

Run: PYTHONPATH=. python3 scripts/paper/make_gen_v47_51.py
"""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
R = os.path.join(ROOT, "results/e2e")
DEST = os.path.join(os.environ.get("ARROW_PAPER_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "paper")), "generated", "gen_v47_51.tex")


def load(name):
    return json.load(open(os.path.join(R, name)))


def pct(x, nd=1):
    return f"{100 * x:.{nd}f}\\%"


def num(n):
    s = f"{int(n):,}"
    return s.replace(",", "{,}")


M = ["% AUTO-GENERATED by scripts/paper/make_gen_v47_51.py -- do not edit"]


def mac(name, val):
    M.append(f"\\newcommand{{\\{name}}}{{{val}}}")


# ---------------------------------------------------------------- V47 / V47b
pc = load("pipeline_compare.json")
pd_ = load("pipeline_compare_delta.json")
dec = pd_["decide"]["0.05"]
assert dec["n_lps_median"] == 4 and dec["n_lps_max"] == 4, dec
assert dec["certified"] == 27 and dec["certified_index"] == [1], dec
mac("PpDecideLps", int(dec["n_lps_median"]))
mac("PpDecideMs", f"{1000 * dec['seconds_median']:.1f}")
mac("PpDecideMsMax", f"{1000 * dec['seconds_max']:.1f}")
# unsafe ships across every pipeline evaluation, both studies
unsafe = 0
cells = 0
for key, a in pd_["aggregate"].items():
    for lab, v in a.items():
        if lab == "timing":
            continue
        unsafe += v["ship_and_unsafe"] * v["n"]
        cells += v["n"]
assert unsafe == 0, unsafe
for key, a in pc["part_b"]["aggregate"].items():
    for lab, v in a.items():
        if lab.startswith("arm_"):
            continue
        unsafe += v["unsafe_ship_rate"] * v["n"]
        cells += v["n"]
assert unsafe == 0, unsafe
mac("PpUnsafeN", num(cells))
# extra runs / samples when the first guess is the other reading (equal split)
runs, samples = [], []
for key, a in pd_["aggregate"].items():
    o = a["equal|seq_other_reading"]; ar = a["equal|arrow"]
    runs.append(o["runs_mean"] - ar["runs_mean"]); samples.append(o["samples_mean"] - ar["samples_mean"])
assert min(runs) > 0.8 and max(runs) <= 1.0 + 1e-9, (min(runs), max(runs))
mac("PpRunsExtraMin", f"{min(runs):.2f}")
mac("PpRunsExtraMax", f"{max(runs):.2f}")
mac("PpSamplesExtraMin", f"{min(samples) / 1000:.0f}")
mac("PpSamplesExtraMax", f"{max(samples) / 1000:.0f}")
mac("PpNSeeds", pd_["aggregate"]["d0.05_n2000_lp"]["equal|arrow"]["n"])
# ship rates at the equal split, d = 0.05 LP (the cell where the pipelines differ)
a5 = pd_["aggregate"]["d0.05_n2000_lp"]
mac("PpShipOther", pct(a5["equal|seq_other_reading"]["ship_rate"]))
mac("PpShipCert", pct(a5["equal|seq_certified_reading"]["ship_rate"]))
mac("PpShipArrow", pct(a5["equal|arrow"]["ship_rate"]))
mac("PpDeltaTot", "0.05")

# ---------------------------------------------------------------- V48
cr = load("collapse_readout.json")
sd = cr["a_exact_surrogate_loss_d0.05"]["all28"]
assert sd["n"] == 28 and abs(sd["median"] - 0.022616345684108) < 1e-12
mac("SgMed", pct(sd["median"], 2))
mac("SgMean", pct(sd["mean"], 2))
mac("SgMax", pct(sd["max"], 2))
mac("SgN", sd["n"])
mac("SgAboveOne", sd["n_above_1pct"])
mac("SgAboveTwo", sd["n_above_2pct"])
mac("SgAboveFive", sd["n_above_5pct"])
mac("SgGeom", len(sd["distinct_values"]))
mg = cr["b_max_gap_instances"]
assert abs(mg["gap"] - sd["max"]) < 1e-12
mac("SgMaxN", len(mg["rule_ids"]))
arms = cr["b_max_gap_learner_arms"]["d0.05_n20000"]["arms"]
lp = arms["lp_tight"]; fq = arms["fqi"]
loss_lp = (lp["decide_single"]["ret_frac_mean"] - lp["surrogate"]["ret_frac_mean"]) / lp["decide_single"]["ret_frac_mean"]
loss_fq = (fq["decide_single"]["ret_frac_mean"] - fq["surrogate"]["ret_frac_mean"]) / fq["decide_single"]["ret_frac_mean"]
assert loss_lp > 0 and loss_fq > 0, (loss_lp, loss_fq)
mac("SgLearnLp", pct(loss_lp))
mac("SgLearnFqi", pct(loss_fq))
mac("SgPermUnsafe", pct(1 - fq["permissive"]["safe_frac"], 0))
cu = load("collapse_utility.json")
ident5 = cu["aggregate"]["d0.05_n20000_lp"]["paired_single_minus_fullset"]["frac_identical_1e6"]
ident2 = cu["aggregate"]["d0.02_n20000_lp"]["paired_single_minus_fullset"]["frac_identical_1e6"]
assert ident5 >= 0.98 and ident2 >= 0.98, (ident5, ident2)
mac("CoIdentA", pct(ident5))
mac("CoIdentB", pct(ident2))
c2 = cr["c_single_minus_fullset"]["d0.05_lp_n2000"]
mac("CoSmallGt", pct(c2["frac_gt_1"]))
mac("CoSmallMean", pct(c2["mean"], 1))
mac("CoBigGt", pct(cr["c_single_minus_fullset"]["d0.05_lp_n20000"]["frac_gt_1"], 1))
ex = cu["aggregate"]["exact_d0.05"]
assert ex["psi_pointwise_dominant"] == 0 and ex["phi_pointwise_dominant"] == 0
assert ex["budget_level_containment"] == ex["n_certified"] == 27
mac("CoCertN", ex["n_certified"])
mac("CoCertTot", ex["n_total"])

# ---------------------------------------------------------------- V49b
an = load("answer_noise_check.json")
mon = an["populations"]["monitoring_free"]
mac("AnPools", mon["n_unsafe_at_0"])
for p, tag in ((0.05, "A"), (0.1, "B"), (0.2, "C"), (0.3, "D")):
    u = mon["summary"]["uniform"][f"flip|{p}|hard"]["unsafe_at_0"]
    g = mon["summary"]["gold"][f"flip|{p}|hard"]["unsafe_at_0"]
    mac(f"AnUni{tag}", pct(u["unsafe_any"]))
    mac(f"AnGold{tag}", pct(g["unsafe_any"], 1))
    mac(f"AnElim{tag}", pct(u["truth_eliminated"], 0))
u1 = mon["summary"]["uniform"]["flip|0.1|hard"]["unsafe_at_0"]
mac("AnAnswersHard", f"{u1['answers_mean']:.1f}")
rep = mon["summary"]["uniform"]["flip|0.1|repeat3"]["unsafe_at_0"]
mac("AnRepUnsafe", pct(rep["unsafe_any"]))
mac("AnRepAnswers", f"{rep['answers_mean']:.1f}")
mac("AnRepHand", pct(rep["handover"], 0))
po = mon["summary"]["uniform"]["flip|0.1|bayes|pa0.2|dp0.05"]["unsafe_at_0"]
mac("AnPostUnsafe", pct(po["unsafe_any"], 2))
mac("AnPostFall", pct(po["fallback"], 0))
mac("AnPostAnswers", f"{po['answers_mean']:.1f}")
ab = mon["summary"]["uniform"]["abstain|0.3|hard"]["unsafe_at_0"]
assert ab["unsafe_any"] == 0
mac("AnAbstainHand", pct(ab["handover"], 0))
mac("AnDraws", an["draws"])

# ---------------------------------------------------------------- funnel
cf = load("coverage_funnel.json")
al = cf["unit_level"]["ALL"]
for st, name in (("raw", "Raw"), ("unique", "Uniq"), ("non_template", "NonT"), ("in_grammar", "Gram"),
                 ("faithful", "Faith"), ("proposed", "Prop"), ("retained", "Ret")):
    mac(f"Fn{name}N", num(al[st]["n"]))
    mac(f"Fn{name}Pct", pct(al[st]["unconditional"], 1))
assert al["raw"]["n"] == 4390 and al["retained"]["n"] == 102
mac("FnGitN", num(cf["unit_level"]["gitlab-runbooks"]["raw"]["n"]))
mac("FnGitPct", pct(cf["unit_level"]["gitlab-runbooks"]["retained"]["unconditional"], 1))
mac("FnTidbPct", pct(cf["unit_level"]["tidb"]["retained"]["unconditional"], 1))
mac("FnGitNonT", num(cf["unit_level"]["gitlab-runbooks"]["non_template"]["n"]))
mac("FnRepos", len(cf["unit_level"]) - 1)
mac("FnGramCond", pct(al["faithful"]["conditional"], 0))
mac("FnPropCond", pct(al["proposed"]["conditional"], 0))
mac("FnRetCond", pct(al["retained"]["conditional"], 0))
mac("FnRetOfGram", pct(al["retained"]["n"] / al["in_grammar"]["n"], 1))
mac("FnGramOfNonT", pct(al["in_grammar"]["n"] / al["non_template"]["n"], 0))

# ---------------------------------------------------------------- V16 taxonomy
tx = load("v16_failure_taxonomy.json")
av = tx["availability"]
assert abs(av["complete_frac"] - 0.22511627906976744) < 1e-12
mac("TxN", num(av["n"]))
mac("TxComplete", pct(av["complete_frac"]))
mac("TxAllComp", pct(av["all_components_frac"]))
mac("TxEff", pct(av["composition_efficiency"]))
ff = tx["first_failure"]["raw"]
mac("TxGroup", pct(ff["group"]))
mac("TxTerm", pct(ff["term"]))
mac("TxShape", pct(ff["shape"]))
mac("TxNumeric", pct(ff["numeric"]))
mac("TxCompOnly", pct(ff["composition"]))
one = tx["by_metric_count"]["single_metric"]["availability"]
two = tx["by_metric_count"]["two_metrics"]["availability"]
three = tx["by_metric_count"]["three_plus"]["availability"]
assert two["all_components"] == 0 and three["all_components"] == 0
mac("TxMultiN", num(two["n"] + three["n"]))
mac("TxMultiPct", pct((two["n"] + three["n"]) / av["n"], 0))
mac("TxOneComplete", pct(one["complete_frac"]))
mac("TxTwoTerm", pct(two["stage_pass"]["term"], 0))
mac("TxThreeTerm", pct(three["stage_pass"]["term"], 0))
mac("TxThreeGroup", pct(three["stage_pass"]["group"], 0))

# ---------------------------------------------------------------- V50 / V51
uc = load("union_calibrated_v51.json")
ta, tf = uc["test"]["all"], uc["test"]["faithful"]
cal = uc["calibration"]
assert abs(cal["v11"]["qhat"] - 0.41) < 1e-9
mac("UnQhatOld", f"{cal['v11']['qhat']:.3f}")
mac("UnQhatNew", f"{cal['union']['qhat']:.3f}")
mac("UnCalCov", f"{cal['union']['cal_retention_at_qhat']:.3f}")
mac("UnRecallOld", pct(ta["v11"]["proposal_recall"]))
mac("UnRecallNew", pct(ta["union_new_q"]["proposal_recall"]))
mac("UnRetOld", pct(ta["v11"]["retention_given_generated"]))
mac("UnRetNew", pct(ta["union_new_q"]["retention_given_generated"]))
mac("UnEteOld", pct(ta["v11"]["retained_recall"]))
mac("UnEteNew", pct(ta["union_new_q"]["retained_recall"]))
gs = ta["union_new_q"]["set_median"] / ta["v11"]["set_median"]
ga = ta["union_new_q"]["maximal_median"] / ta["v11"]["maximal_median"]
assert gs > 1.25 and ga > 1.25, (gs, ga)
mac("UnGrowSet", f"{gs:.2f}")
mac("UnGrowAnti", f"{ga:.2f}")
mac("UnKone", ta["union_new_q"]["K_eq1"])
mac("UnLps", ta["union_new_q"]["decide_lps_total"])
mac("UnAntiOld", num(ta["v11"]["maximal_median"]))
mac("UnAntiNew", num(ta["union_new_q"]["maximal_median"]))
mac("UnSetOld", f"{ta['v11']['set_median']:.2e}".replace("e+07", "\\times10^{7}"))
mac("UnMetricsOld", int(ta["v11"]["retained_metrics_median"]))
mac("UnMetricsNew", int(ta["union_new_q"]["retained_metrics_median"]))
mac("UnFaithRecallNew", pct(tf["union_new_q"]["proposal_recall"]))
mac("UnFaithRetNew", pct(tf["union_new_q"]["retention_given_generated"]))

# ---------------------------------------------------------------- delta_gen anatomy
rows = json.load(open(os.path.join(R, "e2e_test_rows_v11_complete.json")))
assert all(r["pool"] > 0 for r in rows), "some candidate pool is empty; the abstention branch is no longer vacuous"
n_raw = len(rows)
in_gram = [r for r in rows if r["label"] in ("IN_DSL", "GEN_MISS")]
miss = [r for r in in_gram if r["label"] == "GEN_MISS"]
mac("DgEmpty", "0")
mac("DgRawPct", pct(1 - sum(1 for r in rows if r["label"] == "IN_DSL") / n_raw, 1))
mac("DgGramPct", pct(len(miss) / len(in_gram), 1))
gaf = load("guarantee_accounting.json")["accounting"]["grammar_expressible_G0"]["faithful_G0"]
mac("DgFaithPct", pct(1 - gaf["proposal"], 1))
assert gaf["n"] == 315 and gaf["expressible"] == 173

with open(DEST, "w") as fh:
    fh.write("\n".join(M) + "\n")
print(f"wrote {DEST} ({len(M) - 1} macros)")
print("\n".join(M[1:]))
